import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

translations = {
    # common_day6_1.json
    21362: "\"Ahahahaha! So how was it, Kei-chan?\"",
    21363: "\"You went to Rena-san's house! It was incredible, wasn't it!?\"",
    21364: "\"...Ahahahaha... It's not that big a deal, is it...? Right?\"",
    21365: "Unlike my place, which was newly built, the Ryuugu house had apparently been an older building that was renovated.",
    21366: "Well, the house itself was fine.",
    21367: "The problem was the garden.",
    21368: "There it was... filling the entire yard... row upon row of unidentifiable objects!!",
    21369: "And they were all things you might come across just walking through town.",
    21370: "The tongue-wagging mascot from the cake shop.",
    21371: "The bobble-headed frog in front of the pharmacy.",
    21372: "And even the flying elephant ride from the roof of the department store!!",
    21373: "\"I'll grant you those might be kyute, up to a point! But what about that mailbox?! Isn't that going to get someone in trouble!?!?\"",
    21374: "\"...But... hau... it's so kyute...☆\"",
    21375: "She must have just pictured it, because her cheeks flushed with dreamy delight.",
    21376: "\"So bigger just means better to you! As long as it's big!!\"",
    21377: "\"And her room has a dense display of the smaller ones. ...I had the privilege of seeing them once before.\"",
    21378: "\"So a kyute girl like Rika-chan gets locked away in the basement, I suppose.\"",
    21379: "\"...Mm-hm... she'd take anything home...☆ Hau... so kyute...\"",
    21380: "Anything she took a shine to, she simply brought back to her nest. Without any ill will at all.",
    21381: "\"Hey, Rena. You know the Statue of Liberty in New York, right? ...Is that kyute?\"",
    21382: "\"...Yeah, it's kyute... hau... I want it...\"",
    21383: "The US government would probably be wise to start developing countermeasures soon.",
    21384: "At this rate, the Statue of Liberty really would end up making a trip to Hinamizawa in the not-too-distant future...",
    21387: "Speaking of which... Staring at the benevolent face of the Statue of Liberty, my thoughts drifted to Rena's mother.",
    21388: "\"It must have taken quite a long time to appreciate every item on display at Rena-san's house, wouldn't it?\"",
    21389: "\"Yeah. By the time we finished, the sun had loooong since set!\"",
    21390: "After that, Rena had me stay for dinner before heading home.",
    21391: "It was Rena who'd made dinner that evening. Now that I thought about it, her father had said he'd be out late... but what about her mother? It seemed like Rena was the one cooking every day...",
    21392: "\"...Is Rena's mom some kind of high-powered career woman or something?\"",
    21393: "\"Wha——\"",
    21394: "In that instant.",
    21395: "I caught a flicker of shadow pass through the depths of Rena's clear eyes.",
    21396: "\"...Keiichi-kun. Why would you say something like that?\"",
    21397: "Rena was at a loss for words for a moment, then asked me in a low voice that held back just a faint undercurrent of feeling.",
    21398: "\"Ah, no... I just... I didn't see your mom last night. I wondered if maybe she was like mine...\"",
    21399: "\"...Ah.\"",
    21400: "Rena's eyes wavered slightly. I was on the verge of regretting the question, when she turned to me with her usual smile.",
    21401: "\"We don't have a mom at our house.\"",
    21402: "\"Huh...?\"",
    21403: "\"My parents divorced. She's not with us.\"",
    21404: "\"...I'm sorry.\"",
    21405: "\"It's okay, don't worry about it.\"",
    21406: "Even so, that was easier said than done... But then Satoko gave my waist a light pat and stepped in front of me, saying:",
    21407: "\"Oh ho ho ho! I'd love to see how much Rena-san's collection has grown since then! Would it be all right if Rika and I came to visit sometime?\"",
    21408: "\"Hau~~~, yes, of course! Rena will show you her very best and kyutest! So Satoko-chan and Rika-chan, you can stay at Rena's house forever~!\"",
    21409: "\"I — I never said anything about becoming part of the collection... gyuh, gwooooh...!?\"",
    21410: "Rena flashed her usual smile and pressed her cheek against Satoko's with full force. I quietly appreciated Satoko's concern as she writhed in Rena's grip.",
    21411: "Rena's cheerful smile was the same as always. But I felt a faint ache lingering in my chest.",
    21412: "The small shadow I'd glimpsed in the depths of her eyes a moment ago... I couldn't quite shake it.",
    21413: "...Oh, right. I suddenly remembered the pickled vegetables Rena had given me last night.",
    21414: "Every day at Rena's house, she kneaded the rice-bran bed herself and pickled the vegetables. Cucumber, eggplant, turnip, radish... The variety she'd sent home with me as a thank-you had been met with universal acclaim from the entire Maebara household.",
    21415: "There was a time I thought mountain vegetables put store-bought greens to shame, but the rice-bran magic in Rena's pickling crock proved me wrong — whatever vegetables she put in came out with the radiance of a national treasure, the full flavor of the ingredients fully unlocked...!",
    21416: "\"...The pickles you sent me home with yesterday were delicious.\"",
    21417: "I told her honestly. Rena immediately went bright red.",
    21418: "\"R-Really...? Really?\"",
    21419: "\"Absolutely. Rena's pickles are the best in the world.\"",
    21420: "Those words made a little pop sound above Rena's head, and a ring of smoke curled up into the air.",
    21421: "Seeing Rena blush like that left me feeling strangely pleased, which was a funny thing. Still, I couldn't go a day without witnessing it.",
    21422: "\"My, my, things are heating up~. Is this the birth of a lovey-dovey couple~?\"",
    21423: "Mion whistled and teased us.",
    21424: "\"Someone like Keiichi-san, who's hurtling full-speed down the road to no-good, is really quite the perfect match for Rena-san~!\"",
    21425: "Getting teased didn't bother me all that much, but... wait a minute. 'Full-speed down the road to no-good' — what was that supposed to mean!?",
    21426: "Before I could argue, a dull pain shot through my temple.",
    21427: "\"W-Why... why me...!?\"",
    21428: "\"Because Satoko-chan is so kyute~. Hau☆\"",
    21429: "By some law that defied all human understanding, the supersonic Rena Punch had come flying straight at me.",
    21430: "\"...That... doesn't make... any sense...!\"",
    21431: "I pressed my hands to my temple and doubled over in agony. Needless to say, Mion's laughter set everyone else off as well.",
    21432: "\"...Sorry to keep you waiting.\"",
    21433: "Rika-chan had returned.",
    21434: "\"Getting called to the staff room is no fun. Did you do something?\"",
    21435: "\"How rude! Rika is nothing like a troublemaker of your sort, Keiichi-san!\"",
    21436: "\"Ahaha. That's not it, Keiichi-kun. Rika-chan is on the festival committee.\"",
    21437: "\"Festival? Like a school culture festival or something?\"",
    21438: "\"Kei-chan, Kei-chan, I already told you about this. It's the village festival — the Watanagashi.\"",
    21439: "Oh, right — she had mentioned there'd be a festival at the shrine during the next break.",
    21440: "\"So what exactly is this Watanagashi? Is it something like a lantern float?\"",
    21441: "\"I suppose the part where you set things drifting on the water is similar.\"",
    21442: "\"We use worn-out cotton things — old futons, padded cloaks. It's a festival where you express gratitude for their years of service and send them off down the stream.\"",
    21443: "All the villagers of Hinamizawa gather and pile their futons and padded cloaks in the stream...???",
    21444: "That would really back up the current...",
    21445: "Maybe they toss some fish in and hold a fish-wrangling contest.",
    21446: "...Skewer them over a fire with a little salt... Oh, my mouth is already watering...!",
    21447: "\"That's just camping! I never expected Keiichi-san's imagination to be so impoverished~\"",
    21448: "\"Wh-What?! How could you tell I was thinking something silly!?\"",
    21449: "\"...It was written all over your face.\"",
    21450: "What kind of face could possibly have conveyed all that...!?",
    21451: "Rena demonstrated — so that's what my face looked like.",
    21452: "...I see. I can't argue with that.",
    21453: "\"Hahahahaha! Well, it's nothing as exciting as all that. But you should still look forward to it.\"",
    21454: "\"Let's all go together. I'll come get you on the day!\"",
    21455: "I never feel like going to festivals alone. And with this group, there'd be no shortage of entertainment.",
    21456: "\"No shortage of entertainment!? We're doing it again this year!!\"",
    21457: "Mion made the declaration as she swept her gaze around the whole group.",
    21458: "What exactly was about to begin?",
    21459: "...Judging by the way Mion looked... it was probably...",
    21460: "\"Our club's summer tradition!! The Watanagashi Four-Demon Thunderbrawl!!\"",
    21461: "\"Th-That name has zero taste!! What kind of a name is that!?\"",
    21462: "\"...I-I think the name is kind of kyute, though...\"",
    21463: "I was about to shoot it down decisively, but since Rena seemed genuinely happy about it, I decided to let it go.",
    21464: "\"...Since Keiichi is here this year, it'll be the Five-Demon Thunderbrawl.\"",
    21465: "Rika-chan quietly amended it to account for my presence.",
    21466: "\"So how does this pompously-named club activity tie in with the festival?\"",
    21467: "\"Oh ho ho! This is where we exhibit the skills we've honed through our daily club activities!\"",
    21468: "\"Exactly! We demonstrate the full might of an elite who has overcome the daily rigors of rigorous training...!!\"",
    21469: "\"But last year the village chief got angry at us... We need to make sure we don't cause any trouble this time...\"",
    21470: "\"...In other words, we do club activities while wandering the food stalls.\"",
    21471: "...As usual, Rika-chan was the only one who explained it in a way that actually made sense.",
    21472: "So we were going to 'exhibit' our usual chaos at a festival venue. Rena was right — of course the village chief would get angry!",
    21473: "\"Ahaha... but it really is a lot of fun!\"",
    21474: "That, I had no reason to doubt.",
    21475: "It would definitely be fun.",
    21476: "The day of the festival was almost here.",
    21477: "\"Well, that aside. Shall we get today's club activities started! Any objections!?\"",
    21478: "\"None!!\"",
    21479: "Our voices rang out together in perfect unison.",
    21480: "\"When you've got this many people, cards really are the classic option! The very backbone of tabletop gaming!\"",
    21481: "\"Are we using the marked deck again!?\"",
    21482: "\"Fresh new deck today. No marks, so it's completely fair!\"",
    21483: "\"Is it really? I'll be inspecting those cards, if you don't mind!\"",
    21484: "Well, that was only fair. Everyone double-checked the deck to be safe.",
    21485: "\"These look good to me!\"",
    21486: "\"Is everyone satisfied? Then today... let's play President. Five players is a good number!\"",
    21487: "A solid classic of card games.",
    21488: "First one to get rid of all their cards wins.",
    21489: "The basic rule was to play a card stronger than the one before it.",
    21490: "With straights, pairs, reversals, and other techniques in the mix, the game had real depth.",
    21491: "But being such a well-known game, there were regional differences and house rules everywhere.",
    21492: "The name, for one thing.",
    21493: "In my neighborhood back home, we called it 'Millionaire.'",
    21494: "\"Let me just confirm a few details. Are jokers wild? Can you call a reversal with three-of-a-kind in threes?\"",
    21495: "\"No jokers. Twos are highest. Counter-reversal is legal. Reversal requires four-of-a-kind — not three.\"",
    21496: "\"Oh, and you know how the Pauper normally has to offer up a good card? We don't do that here.\"",
    21497: "Satoko eyed me warily as I worked through the rules with practiced ease...",
    21498: "I probably should have played a little more dumb.",
    21499: "I was fairly well-versed in this game!",
    21500: "President, with a brand-new deck. Today... I might actually win!!",
    21501: "I had a handle on the rules now. But surely that wasn't all...?",
    21502: "\"So what's today's penalty going to be!?\"",
    21503: "\"About that — how about everyone writes something on a slip of paper and the loser draws one?\"",
    21504: "Oh, that sounded entertaining!",
    21505: "\"Oh ho ho ho! Then I'll write something deliciously dreadful for Keiichi-san to draw!\"",
    21506: "\"I-If you write something terrible and draw it yourself, you'll be in trouble too.\"",
    21507: "\"Just don't lose, right?\"",
    21508: "\"You understand it perfectly! Oh ho ho!\"",
    21509: "Mion handed out several slips of paper to each of us.",
    21510: "\"Write whatever you like and put it in this bag. When you lose, stick your hand in and draw one.\"",
    21511: "Now, what should I write?",
    21512: "Worst case, you'd end up drawing your own.",
    21513: "...Writing something too extreme would be sawing off the branch I was sitting on.",
    21514: "\"...Writing 'no penalty' — let's make that forbidden.\"",
    21515: "At Rika-chan's quiet suggestion, Mion's hand lurched to a guilty stop.",
    21516: "\"Aaaaah!! That's cheating, Mion-san!! She wrote 'no penalty' and bent the corner of the slip!\"",
    21517: "Well played.",
    21518: "If you happened to lose, you'd just grab the slip with the bent corner and be safe.",
    21519: "...Clever insurance.",
    21520: "Mion, scheming as ever!!",
    21521: "And Rika-chan, seeing right through it — she wasn't to be underestimated either.",
    21522: "She might fly under the radar, but you couldn't take her lightly.",
    21523: "\"Everyone... please don't write anything too awful, okay...?\"",
    21524: "No one agreed to Rena's request. ...Everyone was merciless.",
    21525: "\"It'll be fine, Rena. Just don't lose!!\"",
    21526: "\"...Y-Yeah. That's true.\"",
    21527: "\"All right! I'm going to play hard so everyone draws the penalty I write!\"",
    21528: "Rena seemed gentle enough, but she was utterly ruthless when it counted. Better not underestimate her.",
    21529: "\"Agreed... I'm especially curious about what Rena-san's penalty is...!\"",
    21530: "\"...Everyone's penalties are frightening.\"",
    21531: "Rika-chan's penalty was the most unknowable of all, for what it was worth.",
    21532: "\"In other words — you cannot afford to lose this game!! Is everyone ready!?\"",
    21533: "We all steeled ourselves and gave a firm nod.",
    21534: "Mion confirmed that, and dealt the cards.",
    21535: "...The battle was about to begin!!!",
    21536: "I got off to a decent start.",
    21537: "Card after card was thrown down in the center.",
    21538: "Needless to say, Mion played without hesitation — but so did Satoko and Rika-chan.",
    21539: "The only ones who paused to think were Rena and me.",
    21540: "Rena seemed to be genuinely struggling with her choices... but I was different!",
    21541: "I was like a shark holding its breath for the kill, fangs hidden.",
    21542: "\"Huh? Does this go? Then I play a Three, and I'm out!\"",
    21543: "\"Nine! Anyone? No?! Eight! Seven! I'm out!!\"",
    21544: "\"...Five and Five. I'm out.\"",
    21545: "\"Then I'll play my last card, and I'm out!\"",
    21546: "\"Drat...! I let the moment slip...!!!!\"",
    21547: "The loser in the first round was... Mion, of all people! And now I knew it with certainty.",
    21548: "...Today... I could win!!!",
    21549: "\"Now, now! Mii-chan, reach in and draw one~!\"",
    21550: "Mion accepted her fate and rummaged around in the bag, pulling out a single slip.",
    21551: "\"...Wha!? Who wrote this!? Who wrote thiiis!?\"",
    21552: "Mion shrieked and began to tremble.",
    21553: "\"...Um, what does it say? What does it say? ...Ehhh!?\"",
    21554: "Rena peeked at it and was equally shocked.",
    21555: "...What horrible thing was written on there!?",
    21556: "\"Pet the principal on the head.\"",
    21557: "\"...Hold on. How is this a problem?\"",
    21558: "\"Keiichi-san, can you not tell!?! The principal is deeply ashamed of his thinning hair!!\"",
    21559: "Satoko shouted with deadly earnestness.",
    21560: "But surely not enough to make Mion scream like that.",
    21561: "There had to be something more to it...",
    21562: "\"...The principal is a martial arts master.\"",
    21563: "\"He claims he traveled the world in his youth training in the martial arts and mastered every discipline.\"",
    21564: "\"He reportedly became a teacher because he was troubled by the declining state of education in post-war Japan...\"",
    21565: "He was beyond human. ...Pet that man on the head...?",
    21566: "\"As club president, there's no way I can set a poor example by refusing... Haah.\"",
    21567: "\"...............Ryaaaaaahhhh!!\"",
    21568: "With a battle cry, Mion charged out into the hallway.",
    21569: "\"...Wouldn't it have been better to sneak out quietly and handle it without the fanfare?\"",
    21570: "\"Probably impossible... They say he used to hunt sea slugs by sensing their presence alone.\"",
    21571: "There was nothing to do but wait with bated breath.",
    21572: "THWOOM!! A shockwave rattled the classroom!!",
    21573: "\"...The principal has activated his ultimate technique.\"",
    21574: "KABAAAAM!!!",
    21575: "ZZZING!",
    21576: "BOOOOM!!!",
    21577: "A seamless, flowing combo!? And now he's pressing the attack on a downed opponent!!!",
    21578: "\"...That's Jeet Kune Do, isn't it?\"",
    21579: "\"I-I don't know... I just know I don't want any part of it...!!\"",
    21580: "All I could do was feign composure. ...Now I understood why there were no delinquents at this school.",
    21581: "After a brief silence, Mion staggered back to us on unsteady legs.",
    21582: "\"...Petted him. ...Is that... good enough...!?\"",
    21583: "She said it and keeled over.",
    21584: "\"She's alive, at least. The game can continue!!\"",
    21585: "\"...M... monster...\"",
    21586: "It's rich, hearing that from the person who made club activities like this.",
    21587: "\"But now! The scariest penalty is gone! Right?!\"",
    21588: "Rena laughed, trying to lift the mood, and was met with Mion's vicious smile in return. ...She meant it.",
    21589: "\"No more mercy!!! I'm making all of you regret this!!\"",
    21590: "The pace of the game accelerated to a furious clip. I could feel the temperature rising.",
    21591: "\"Ace! Three, Four, Five!! Out!!\"",
    21592: "\"...I'm also out.\"",
    21593: "\"Heh! I'm out too!\"",
    21594: "\"Three!! I'm out!!\"",
    21595: "\"Eek!! I-I loooost...!?\"",
    21596: "...And fate had chosen Rena as its victim.",
    21597: "\"Wh... What kind of penalty... What kind of penalty...!\"",
    21598: "It was no wonder she was anxious...",
    21599: "Just thinking back to the difficulty level of Mion's very first penalty made me shudder...",
    21600: "And so... trembling, she drew her penalty, and it was...",
    21601: "...Huh.",
    21602: "\"Speak like a maid.\"",
    21603: "\"Ehh!? Wh-What is this!? ...What am I supposed to do?\"",
    21604: "\"...Which means... you have to speak the way a maid would...?\"",
    21605: "\"H... hau... yes... Master...\"",
    21606: "My head went light. ...I had no idea who'd written that penalty, but they were a genius!!!",
    21607: "\"Th-Then, Rena, could you collect the cards and... deal them out to everyone...?\"",
    21608: "\"Y-Yes... Master...\"",
    21609: "Ah, I could die happy right now♪!!",
    21610: "\"A-A-Anyway, let's keep going!! Right, Rena!?\"",
    21611: "\"...Yes, Master...\"",
    21612: "I couldn't help but find myself utterly charmed by my own impulse to keep talking to Rena just to hear her say it.",
    21613: "\"Hoyah!! I'm not losing anymore! Out!\"",
    21614: "\"I absolutely cannot lose either!!\"",
    21615: "\"...I'm out.\"",
    21616: "\"Then with this... I'm oooout!!\"",
    21617: "\"N-Nooooo!! Is it Rena's loss again!?\"",
    21618: "Rena again...! What penalty would it be this time...?",
    21619: "My chest danced with a strange feeling of anticipation.",
    21620: "...Anticipation? No — this was conviction!!",
    21621: "\"Remove one item of clothing from the top and one from the bottom.\"",
    21622: "\"Th-Th-That's outrageous!? Who could have written this!?\"",
    21623: "I went red and bristled. If I didn't yell something out, there was no way I'd be able to hide how flustered I was!!",
    21624: "Ahh, who wrote that!! God, please award that person a Nobel Prize!!",
    21625: "\"That would be the Nobel Prize for Perversion.\"",
    21626: "Uh oh — I'd gone and let my thoughts show on my face again.",
    21627: "\"...Hau... uu... Mii-chan...\"",
    21628: "Rena turned to Mion with wet eyes, silently begging her... but everyone already knew Mion's answer.",
    21629: "\"Nope, nope! No going easy on anyone!! You lost, so face it with dignity!!\"",
    21630: "\"...U-Understood, Master... Hau... I-I'll... undress...\"",
    21631: "Wh-Whaaaat!? I looked around, expecting someone to put a stop to this — but nobody made any move to stop Rena. Not that I was, either!",
    21632: "A rustling sound began... and the sound of a skirt falling to the floor sent my heart leaping into my throat!",
    21633: "\"I-Is this... all right... M-Master...?\"",
    21634: "I averted my eyes like a gentleman.",
    21635: "...B-But these club activities call for ruthlessness...!",
    21636: "\"Ah... O-Oh... Ahahahaha... ha.\"",
    21637: "\"Keiichi-san, whatever were you expecting!? You couldn't very well have her undress if she wasn't wearing her PE clothes underneath!\"",
    21638: "Satoko teased me, but right now her words barely registered...!",
    21639: "\"Not bad, Kei-chan~~!! This old man never saw this angle of attack coming.\"",
    21640: "\"I-I-I-I didn't write that one!!\"",
    21641: "\"D-Did Master... not write this one...?\"",
    21642: "H-Her squirming around in her PE uniform made it impossible not to feel something...",
    21643: "C-Calm down, Keiichi Maebara...!!",
    21644: "This was obviously something Mion had written, designed to make me panic!!",
    21645: "You can't fall into an obvious trap just because you know it's a trap! Clear your head! Stay calm and think your way through this...!!!",
    21646: "I ran the computer in my head at full capacity and forced myself to focus.",
    21647: "...And the answer it produced was extremely simple.",
    21648: "\"I... I WIIIIN!!!!!\"",
    21649: "And so I became a god!!!!",
    21650: "I, who had already ascended to the divine... what obstacle could possibly stand in my way!?",
    21651: "It was as if drawn to me by magnetism... Aces and Twos kept flying into my hand!!",
    21652: "\"...Eek!? How can my luck be this bad!?!?\"",
    21653: "\"Satoko's loss. I'll draw. 'Speak like a little sister'!!!!\"",
    21654: "\"Uuugh!! ...Fine, Onii-chan... ghhk!!\"",
    21655: "Yaaaaas!! The pleasure of making this brat eat humble pie!!",
    21656: "\"Ugh! ...This old man loses again!\"",
    21657: "\"Mion's loss. I'll draw. 'Put on a girl's school swimsuit'!!!!\"",
    21658: "\"Noooooo!! That's the one I wanted Kei-chan to get!\"",
    21659: "Yesssss!! Mion's despair is like the sweetest honey!!!",
    21660: "\"M-Master... I-I lost again...!\"",
    21661: "\"Rena's loss. I'll draw. 'Let the winner rest their head on your lap'!!!\"",
    21662: "\"...H-Hau... In this outfit... Master...?\"",
    21663: "YESSSSS!! She's not wearing a skirt, so it's her bare thighs!!!♪",
    21664: "\"Eek!! Onii-chan... you're too good... sniff.\"",
    21665: "\"Satoko's loss again. I'll draw. 'Serve the winner as commanded'!! How about a nice shoulder massage!?\"",
    21666: "\"Fine, Onii-chan...\"",
    21667: "\"Come on, dig in deeper! Watch the nails!! Bwahahahaha~♪!!\"",
    21668: "I had fully transformed into an evil emperor, and I had never been better!",
    21669: "I felt as though I could bend the cards to my will with sheer force of thought — as if I could decide what suit would appear next simply by wishing it!",
    21670: "...Before I knew it, a full harem had assembled around me.",
    21671: "I lay on Rena's lap — now a bloomer-clad maid — and laughed with reckless abandon.",
    21672: "Satoko wore a collar and had been reduced to little-sister mode.",
    21673: "Mion, in her school swimsuit, was fanning me with a decorative feather fan.",
    21674: "\"Hau... T-Today is Master's overwhelming victory, isn't it...\"",
    21675: "\"...Eep! Please refrain from rolling your head around so much, please...\"",
    21676: "A thought came to me.",
    21677: "...Why does the human heart have no end to its wanting?",
    21678: "With all this — this palace of dreams — what more could I possibly wish for!?",
    21679: "\"...What is it, Keiichi?\"",
    21680: "\"I was lamenting that human desire knows no limit.\"",
    21681: "Right.",
    21682: "Rika-chan hadn't taken first place, but she'd been deftly dodging last place again and again.",
    21683: "\"...Keiichi, you're greedy. They say it's wise to know when enough is enough.\"",
    21684: "\"Oh, I understand it perfectly. ...It's hard to put into words, really. It's more like... I feel like I could die happy right now.♪♪♪\"",
    21685: "\"Eeeek! Master... please stop rolling around... Eeeek!\"",
    21686: "\"...You say you could die happy. ...Then perhaps that can be arranged.\"",
    21687: "She said it with her usual serene calm and her usual quiet smile.",
    21688: "...There was no mistaking it. This was Rika-chan's declaration of war...!",
    21689: "\"Go, Rika-chan!! Take him down~~!!\"",
    21690: "\"Defeat this lecherous Demon King~~~!!!!\"",
    21691: "\"...I may not be able to win... but I will beat him.\"",
    21692: "Such unassuming resolve from this girl who was so easily overshadowed by Satoko!",
    21693: "It would be rude not to meet her head-on.",
    21694: "...Very well — I will face you, little one!!!",
    21695: "Midway through the game I noticed Mion discreetly swapping cards with Rika-chan, but pretended I hadn't seen a thing.",
    21696: "...Do you really think something that trivial can bring down Keiichi-sama right now!?!?",
    21697: "\"...Two. Ace, Ace, Ace. ...Eight, Eight, Eight, Eight. Reversal.\"",
    21698: "Everyone turned to look at me in unison. I was still brimming with confidence.",
    21699: "...Mwahahahaha! All four of them united against me... Is this the best they can do? You're making me laugh!!!",
    21700: "\"That was allowed. ...COUNTER-REVERSAL!!!!!!\"",
    21701: "\"Wha!? How can this be...!?!?!\"",
    21702: "Satoko let out a cry of despair!",
    21703: "...Mwahahaha! Fools!!!",
    21704: "Having played all her strong cards before calling the reversal, Rika-chan had nothing left!!",
    21705: "The match was decided in the blink of an eye.",
    21706: "\"...I... lost...\"",
    21707: "\"Bwahahahahaha!!! You have finally fallen into my hands!!! Now I'll draw!! Uohhhhh!?!?\"",
    21708: "\"Equip cat ears, bell collar, and tail.\"",
    21709: "Mwahahahaha!! Even the penalties were bowing to my will!!!",
    21710: "Rika-chan hung her head and equipped the three sacred artifacts.",
    21711: "I had no idea why such things were in Mion's locker, but since I had no objection, I said nothing.",
    21712: "Uohhh!! Th-This is...!! ...Hau~~!! ...I practically became Rena for a moment... This was definitely... kyu-kyute...♪♪♪",
    21713: "\"Kyute, isn't it?? Isn't it!? ...Hau... Must take home...☆\"",
    21714: "That wasn't me talking. That was the genuine article — Rena herself.",
    21715: "\"...Mew...\"",
    21716: "The moment Rika-chan looked up with teary eyes and gave that little imitation meow, two pops sounded from Rena's ears and twin rings of smoke curled up into the air.",
    21717: "\"...Rika-chan... Take her home, take her home...☆ ...J-Just for a little while.☆ I-I won't do anything strange... nothing strange...☆\"",
    21718: "\"I-I see... I still had this card to play...!!\"",
    21719: "Mion gasped and clapped her hands together.",
    21720: "\"...If Rena really insists... she can take me home.\"",
    21721: "\"After Rena-san beats Keiichi-san she caaan!!!\"",
    21722: "So they figured Rena in full kyute mode could take me down!",
    21723: "Would it really be that easy!?!?",
    21724: "Defying me was the same as defying God!! I would teach them their place!!!",
    21725: "\"How insolent!! Rena can never defeat me... Eep!?\"",
    21726: "For a moment, I had no idea what was happening.",
    21727: "Fifty-two cards swirled and danced through Rena's hands, flowing freely like the moves of a master illusionist!!!",
    21728: "Caught in the heart of that swirling storm of cards, Rena wore an expression of absolute rapture, her head bobbing in circles...!!",
    21729: "\"Sh-Shall we, shall we shall we shall we, Keiichi-kun... Hurry, hurrrry!!!\"",
    21731: "My whole body knew it already. ...I was going... to lose.",
    21732: "\"No play!? Nothing to play, Kei-chan!?\"",
    21733: "\"...Then with this... I'm ouuuut!!!\"",
    21734: "Everyone erupted in a cheer. I was spent.",
    21735: "\"Ha... I have no regrets... God... thanks for the dream, short as it was.\"",
    21736: "\"Now then! I'll draw!?!?\"",
    21737: "\"Keiichi-san's penalty!!! ...This is it!!\"",
    21738: "Everyone crowded around and peered at it, eyes flicking back and forth between the text and my face.",
    21739: "\"I had quite the run today. ...I'll do whatever it is. What does it say?\"",
    21740: "\"All of them.\"",
    21741: "\"Huh?\"",
    21742: "\"Every penalty drawn so far.\"",
    21743: "\"Wha... What the HEEECK!?!?!?\"",
    21744: "\"Keiichi-san, your speech isn't showing little-brother characteristics!?\"",
    21745: "\"Ugh... ...Yes, Onee-chan. ...Uuuugh!!!\"",
    21746: "\"Uwaaah...☆ Th-This really is addictive! Next you can rub my shoulders!!\"",
    21747: "\"Keiichi-kun, you don't have to do the lap pillow... Can you do that other one instead, for me?\"",
    21748: "\"Ugh... Y-Yes, Master...\"",
    21749: "\"Ha-hau...! Keiichi-kun... Th-That's... so kyute... Say it again? Say it again!?\"",
    21750: "\"Ahh~, please have mercy on me, Master...!\"",
    21751: "Rena passed out with a screech of 'hau~~!!', blood gushing from her nose.",
    21752: "My dignity was now worth about a single copper coin.",
    21753: "\"Next up is this old man's! I think I'll have you fan me nice and sloooowly for a while!?\"",
    21754: "Fwoosh fwoosh!!!",
    21755: "\"...Oh, right. You need to be wearing this too, don't you? The school swimsuit.☆\"",
    21756: "\"Wh-What!? That's a girl's swimsuit!! Can't I just wear the boys' version!?\"",
    21757: "\"It says right here, quite clearly, 'Put on a girl's school swimsuit'!!!!\"",
    21758: "Satoko struck me as exactly the type who'd make a great debt collector.",
    21759: "...Although, if I was honest, the sight of myself fleeing into denial was pretty pitiful.",
    21760: "\"B-B-But!? Whose swimsuit am I putting on!? Won't you mind — me wearing one of yours!?\"",
    21761: "\"Ah, this old man doesn't care about that at all.☆ Think of it as a little perk! My figure's not great, so I think even Kei-chan could fit into it!!\"",
    21762: "The executioners closed in, fingers flexing eagerly.",
    21763: "\"Ngh-ngh... NOOOOOOOOO!!!\"",
    21764: "First impression: tight around the waist. Second impression: the chest area had more room... Third impression: please don't make me say any more!!",
    21765: "\"Ahahaha~ Keiichi-kun is... so kyute, so kyute!!\"",
    21766: "\"...Complete the look with the cat ears, collar, and tail.\"",
    21767: "\"Kei-chan, want to look in the mirror? ...It really is something else. Probably worth seeing for yourself.\"",
    21768: "Mion's scientific detachment, lurking beneath the pure amusement on her face, was genuinely frightening.",
    21769: "\"I... respectfully decline, Master...\"",
    21770: "\"Your ensemble is complete!! It would have been perfect if we could send you home dressed like this! Oh ho ho ho!!\"",
    21771: "\"Then... I-Is that enough? Can I change back...?\"",
    21772: "As I reached for the shoulder strap, Rika-chan materialized silently behind me.",
    21773: "\"...Not yet, Keiichi. There's still the very first penalty left.\"",
    21774: "\"...In this... get-up?\"",
    21775: "Rika-chan said nothing and quietly patted me on the head...",
    21776: "\"Yes sir!! Excuse me!!\"",
    21777: "\"Yes. Come in.\"",
    21778: "I stepped into the principal's office. The little bell at my collar jingled with endearing pointlessness.",
    21779: "The principal had frozen solid, smile still on his face, the moment he saw me.",
    21780: "Understandably.",
    21781: "In this sacred place of learning — specifically, the principal's office.",
    21782: "What had politely knocked and entered wearing a school swimsuit, cat ears, a collar, and a tail—",
    21783: "—was a disheveled, unambiguously male student.",
    21784: "...Any person with a normal nervous system would inevitably have their thought processes brought to a complete halt...",
    21785: "But this was a phenomenon that could be explained scientifically.",
    21786: "It was, in essence, the primal principle behind mimicry and camouflage.",
    21787: "Humans can only begin to act once they've confirmed that what they're looking at is another human.",
    21788: "...Meaning that if he could not comprehend what stood before him, then in the moment before he could process it... his mind would be a total blank...!!!",
    21789: "That was my one and only opening — my chance for victory!!!!!",
    21790: "My penalty was—!!",
    21791: "To pet the principal on the head!",
    21792: "\"PrincipaAAAAAAAAL!!! I CHALLENGE YOU... GHK!!!!!!\"",
    21793: "A sharp ringing sound. He went straight for the ultimate move!?",
    21794: "The principal said one thing to me.",
    21795: "\"What does it mean... to be a man...?\"",
    21796: "And in a single heartbeat...",
    21797: "A thunderous sound echoed through the twilight of Hinamizawa...",
    21799: "I understood with every fiber of my being.",
    21800: "The situation was infinitely dangerous! Rena's 'Kyute Mode' had achieved full deployment, every chakra in her body was unlocked, and the great demons had descended upon her!! ...But! I couldn't afford to lose here!!",
    21801: "If it had activated — then I would simply have to seal Rena's Kyute Mode!!!",
    21802: "\"Rena... Listen carefully.\"",
    21803: "I looked straight at Rena and whispered low and close to her ear.",
    21804: "\"Hau, h-h-h-hau hau hau~~? Wh-What is it, Keiichi-kun...?\"",
    21805: "\"If I win... I'll give you a reward worth even more. How about it?\"",
    21806: "\"Something worth even more... a r-reward!? What is it? What is it?\"",
    21807: "Rena's gaze, which had been fixed dreamily on Rika-chan, slowly swiveled toward me.",
    21808: "A small crack had opened in Rena's focus. In that gap of buoyant expectation... I pressed my attack without mercy!",
    21809: "\"Yes... In addition to Rika-chan, I'll throw in Satoko.\"",
    21810: "\"Wh-What!?\"",
    21811: "\"B-Bribery!? Kei-chan, you'd really go that far!?\"",
    21812: "Everyone around me stirred at my offer to Rena.",
    21813: "\"This is not a joke! I am not a free prize to be thrown in with a purchase of caramel!!\"",
    21814: "\"Collect stickers, and a big prize comes guaranteed!\"",
    21815: "\"I keep telling you, I'm not a freebie!!!\"",
    21816: "\"...Th-That's not right, Keiichi-kun... You can't cheat.\"",
    21817: "Rena's eyes had gone a little glassy as they drifted toward Satoko, her new target. But even as she was saying the right things, it was plain to see that her heart was thoroughly rattled.",
    21818: "Right — whether I could actually deliver Satoko didn't matter at this point! The goal was to disrupt Rena's concentration! Scatter her attention in every direction and strip away her razor focus at the crucial moment!",
    21819: "\"Hey... Rena. You haven't forgotten... the debt you owe me for Randy-kun, have you?\"",
    21820: "And as the finishing blow against Rena's already fractured mind, I pulled out the unspoken debt from the past. Just as I'd anticipated — Rena's heart lurched... and the fearsome aura that had surrounded her moments ago visibly deflated!",
    21821: "\"Hah-hau!? R-Randy-kun doll...!?\"",
    21822: "She hadn't forgotten that I'd dug that enormous figure out of a trash heap for her... had she...?",
    21823: "I fixed Rena with a sharp, pointed stare as if to drive the point home. She was already completely thrown.",
    21824: "\"All right then. Let's begin.\"",
    21825: "I launched the game without a beat of pause. Rena had plunged headlong into full panic mode — she didn't even have the composure to hide it.",
    21826: "The ultimate Kyute Mode... defeated!!!",
    21827: "\"Um... 1...!\"",
    21828: "\"Yes, a 2! And then two Fives, and two Eights...!\"",
    21829: "I shed card after card in rapid succession. Rena's hand wasn't bad by any means, but she was too busy watching my face to play any card effectively!",
    21830: "\"Uh... uhhhh~~...!\"",
    21831: "Rena never managed to break free of her panic from start to finish. Of course she didn't. Hit with both a promised reward and an old debt at the same time — no one could hold steady against that.",
    21832: "My 'Kyute Mode Blocker' had worked to perfection!",
    21833: "\"2...! 1...! Two Threes, and — out!!\"",
    21834: "\"H-Hauuu~~!? I-I lost again...!?\"",
    21835: "Rena went down before my Kyute Mode Blocker. And so... a crestfallen Rena reached into the bag and drew her penalty—",
    21836: "\"H-Hauuuu!? K-Keiichi-kun...\"",
    21837: "The moment she saw what the slip said, her eyes flew wide open in dismay, and she looked up at me with fearful, searching eyes. The slip read: 'Do whatever the winner says — one request.'",
    21838: "\"Hmm. Then I give you my order...!\"",
    21839: "\"............\"",
    21840: "Rena's face was taut with tension. Mion, Satoko, Rika-chan — every one of them was waiting for my next words...!",
    21841: "\"Rena. The debt I've been holding over you for Randy-kun — consider it settled.\"",
    21842: "\"...Huh?\"",
    21843: "I smiled back at her bewildered look and replied.",
    21844: "\"I wasn't planning to keep holding that over you forever. ...So — no more debt.\"",
    21845: "\"...Keiichi-kun.\"",
    21846: "Rena's expression had gone soft and dazed. The penalty had clearly taken her completely by surprise.",
    21847: "\"For a finale from someone who used underhanded tactics to win, this is a remarkably clean ending.\"",
    21848: "\"Give me a break.\"",
    21849: "Rika-chan's commentary rolled off me entirely. I was victorious.",
    21850: "Well... I'd thought myself that the tactic might have been a bit much. And besides, the entire objective had been to avoid drawing a penalty — that goal had been achieved. This was enough.",
    21851: "\"B-But then, Keiichi-kun... doesn't that mean nothing has changed for you?\"",
    21852: "\"...Hmm. Then here's a new order. Transform Rika-chan into my ideal maid!\"",
    21853: "\"Hau~!? Oh, that's an easy one~~♪♪\"",
    21854: "Rena's 'Kyute Mode' reignited.",
    21855: "Seal it, then break the seal — even I had to admit, today's strategy was quite elegant!",
    21856: "\"Mi-Mii~! Only one order is allowed~!\"",
    21857: "\"Hau~~!\" Rena shouted, pressing her cheek against Rika-chan.",
    21858: "Rika-chan's screams echoed through the room.",
    21859: "...Rest in peace.",
}

data = json.load(open(BASE_DIR / 'common_day6_1.json'))

count = 0
for entry in data:
    if entry.get('type') in ('MSGSET', 'LOGSET'):
        mid = entry.get('MessageID')
        if mid in translations and 'TextENGNew' not in entry:
            entry['TextENGNew'] = translations[mid]
            count += 1

with open(BASE_DIR / 'common_day6_1.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added TextENGNew to {count} entries in common_day6_1.json")

# Report any missed entries
missed = []
for entry in data:
    if entry.get('type') in ('MSGSET', 'LOGSET') and 'TextENGNew' not in entry:
        missed.append(entry.get('MessageID'))
if missed:
    print(f"Missed {len(missed)} entries: {missed}")
