#!/usr/bin/env python3
"""Translations for taraimawashi_2.json"""
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TRANSLATIONS = {
53538: "\"Mooo-orning, Mi-chan!\"",
53539: "Rena waved as Mion came running over.\nI called out to her too.",
53540: "\"Good morning, Rena! Kei-chan!\nGood work yesterday, both of you!\"",
53541: "\"You too, Mi-chan — thanks for handling the cleanup!\"",
53542: "I wanted to offer Mion some words of appreciation for her hard work.",
53543: "Even for a small village festival, this was a village-wide effort. The scale was nothing to scoff at.",
53544: "\"That must have been quite a lot of work, the cleanup.\"",
53545: "\"It was, let me tell you… we were at it until around three in the morning?\nThen I went home, took a bath, and… went to sleep at four-thirty.\"",
53546: "Her tone was breezy enough that I almost let it slide — but then the meaning of \"four-thirty\" landed and I stared at her.",
53547: "\"F-four-thirty?!\nThat means you barely slept at all!\"",
53548: "If it were me… I would absolutely have declared a personal snow day.\nI was being completely, deeply sincere about that.",
53549: "\"Ahahaha!\nKei-kun, you're making your 'if it were me I'd have stayed home' face!\nHau~\"",
53550: "Ugh… nnkk.",
53551: "Rena had read my mind…",
53552: "\"Ahahahaha!\nKei-chan is just so easy to read!\"",
53553: "According to Mion, the adults had been going at it until dawn.\nYou could see their devotion to the festival.",
53554: "We chatted and laughed as we reached the classroom door and I put my hand on it.",
53555: "…Right at that moment — my internal crisis-management system gave a little ping.",
53556: "I looked up immediately — and sure enough, there was a chalkboard eraser balanced on the door!",
53557: "Mufufufu… how naive.\nI snatched it and stepped triumphantly into the room.",
53558: "But in the next instant, the familiar view in front of me flipped in a single second to the ceiling.",
53559: "I only realized I'd been tripped after I hit the floor, rear-first, with a healthy dose of pain.",
53560: "To make matters worse, the chalkboard eraser landed squarely on my face, releasing a cloud of white powder.",
53561: "I brushed it off and pushed myself upright to see — an abacus sprinting away from under my feet at full speed.",
53562: "\"My, my, Keiichi-san.\nBackflipping the moment you enter the room — what a dedicated entertainer you are!\"",
53563: "I hauled myself to my feet and stalked toward the culprit — step, step.\nFlick. Flick. Snap!",
53564: "My index finger struck the target with tremendous force.",
53565: "\"Fuwaaa-aaah!!\nKeiichi-san flicked me on the foreheaaad!!\"",
53566: "\"You came close, but not yet, I'm afraid.\"",
53567: "Rena writhed in agony at the spectacle; Mion looked exasperated.",
53568: "Everything was… exactly as it always was.\nNo classmates missing; the atmosphere unchanged.",
53569: "The low murmur of unease that had been hovering at the back of my mind since last night dispersed all at once.",
53570: "I looked around the classroom with a relieved expression.",
53571: "A smile might have spread across my face without my realizing it.\n…It was probably creepy from the outside.",
53572: "Rena noticed my strange smile and peeked at my face with a worried look.",
53573: "\"What's wrong, Kei-kun?\nDid you hit your head? …Did you?\"",
53574: "\"My ukemi is impeccable.\nIf you want, I can do it again?\"",
53575: "\"N-no thanks, really…!\"",
53576: "What's with that — what exactly do you mean, \"no thanks\"?",
53577: "\"Alright, Sensei's here~!\nEveryone take your seats~!\"",
53578: "At Mion's call, everyone shuffled into their chairs.",
53579: "\"Good morning, everyone.\nYou had your festival yesterday.\nThank you to everyone who stayed to help with the cleanup.\"",
53580: "\"Now, for the next few days, TV and magazine reporters who came to cover the festival may still be around.\"",
53581: "I had been letting the announcement wash over me as usual, but then the tone in Sensei's voice shifted slightly, and my attention snapped back.",
53582: "\"Some of you may be approached for an interview. Please be careful not to say anything vague or careless.\n…Do you understand?\"",
53583: "Yes~! everyone chorused.",
53584: "She chose her words carefully, but I knew exactly what she meant.",
53585: "After all — this was the fifth year.",
53586: "The fifth-year curse — reporters from tabloid TV shows and second-rate magazines looking for a story would probably be wandering around half-curious.",
53587: "As far as the village was concerned, it only made their reputation worse, and was thoroughly unwelcome.",
53588: "She was telling us not to stoke or feed that appetite ourselves.",
53589: "Now I was one of the people on the inside.",
53590: "And so, understood, I agreed with it.\nFitting yourself to the village's way of doing small things like this — that was the important part of building bonds with the people here.",
53591: "I had assumed club activities would be cancelled today, given how tired everyone must be from last night.",
53592: "Maybe I'd head to the game center in Okinomiya for the first time in a while…",
53593: "I was in the middle of thinking that when Mion clapped me on the shoulder.",
53594: "\"…What are you spacing out for, Kei-chan?\nWe're about to start club activities!\"",
53595: "Oh-ho~?! We're doing it!!",
53596: "Just like that, the plan I'd just been formulating vanished into thin air.",
53597: "No sign of last night's exhaustion anywhere — that's Mion for you!",
53598: "Not just Mion, either. Rika-chan must have had her share of cleanup duty too.",
53599: "Satoko, as Rika-chan's tag-along, had been at the shrine until late into the night.",
53600: "Even so, they all seemed energetic enough — which was impressive — but the invisible fatigue must still be there.",
53601: "This was too good a chance to pass up.\nI was going to grind them into the ground.",
53602: "\"Keiichi.\nWhat are you grinning about?\"",
53603: "\"Ohohohoho!\nI'm sure you think, since everyone is short on sleep, today is your chance to win!\"",
53604: "Gulp… right on the nose.",
53605: "\"Oh, Keiichi.\nYour expression just changed.\"",
53606: "\"Oh~, Keiichi-san?\nLooks like that hit home — ohohohohoho!\"",
53607: "\"Hau~, Kei-kun?\nThat hit home, did it? …Did it?\"",
53608: "\"Keh-keh-keh!\nKei-chan, this club is not so weak or so easy as all that!\"",
53609: "All four pairs of eyes gleamed at once.\nIndeed — these were battle-hardened veterans; they were not to be underestimated…",
53610: "\"Alright, here's today's game!\nToday we'll be playing…!\"",
53611: "Mion slammed a deck of cards down on the desk with a thump.",
53612: "\"A proper mystery game!\"",
53613: "A murmur of interest went around.\nAn imported game, huh… this sounds interesting!",
53614: "\"The rulebook is in English, but the rules themselves aren't so complicated.\"",
53615: "\"This game is no weakness of mine, I assure you!\"",
53616: "\"…I won't lose.\"",
53617: "Rena's color was looking rather poor. She was apparently not great at this kind of game.",
53618: "\"The rules are: whoever identifies the culprit, the murder weapon, and the crime scene wins!\"",
53619: "There were apparently three categories of cards: culprit, weapon, and crime scene.",
53620: "Looking at the culprit cards… there was \"Mion,\" \"Rika\"... everyone's names were on them. Oh — there was already one with my name too!",
53621: "Hmm.\nThere were all sorts of weapon cards!\nAxe, knife, poison…!",
53622: "And the crime scene cards were pretty evocative!\nThe study, the courtyard, the attic… there was even one for \"behind the gym!\"",
53623: "\"So essentially:\none card from each category is removed from the deck.\nThose are the correct answers.\"",
53624: "\"The remaining cards are shuffled and distributed equally among us.\nWe take turns asking each other about our cards, trying to deduce which ones were removed.\"",
53625: "Ah, I see. Whoever holds no card of a given kind — that's the true culprit!",
53626: "\"When you think you've figured out the answer, raise your hand!\nThe game ends and we check if you're right.\"",
53627: "\"Correct answer scores plus one point!\nWrong answer scores minus one point!\nWhether right or wrong the game ends and we reshuffle and start over!\nDo you follow, Keiichi-san?\"",
53628: "\"It'll make sense once you play.\nThis game requires a great deal of thought.\"",
53629: "\"You'll lose track without taking notes~?\nThink you can keep up~? Keh-keh-keh!\"",
53630: "Rena hurriedly produced a notepad. The tension on her face was palpable.",
53631: "\"…So what's the penalty game this time, Mion?\"",
53632: "Everyone's eyes focused on Mion at once!",
53633: "\"Well… \nConsidering some of us are a bit tired from yesterday, today I'll go easy on you: the Errand Sentence. The loser gets a shopping list from everyone and has to run to the store!\"\n",
53634: "\"So the loser has to go out and buy juice and snacks and stuff.\"",
53635: "\"I feel today's penalty is somehow too lenient.\"",
53636: "…Was it though?",
53637: "\"Keiichi does not seem to think so.\"",
53638: "Because you never know what she'll make you buy…",
53639: "With Mion in charge, if you lose, she'd probably put 'hemorrhoid cream' and 'athlete's foot medicine' on your shopping list — a nightmare of bizarre and humiliating purchases!",
53640: "I looked at Mion's face. Her eyes seemed to gleam.",
53641: "Last place was absolutely not an option.",
53642: "\"Alright, let's begin!\"",
53643: "The cards were shuffled at once and dealt out.",
53644: "Since one card from each category had been removed, every card in your hand was by definition \"innocent.\"",
53645: "\"First up is the person who worked hardest last night — Rika-chan!\"",
53646: "\"Thank you.\nMii~ then — 'Satoko,' 'Axe,' 'Courtyard'!\"",
53647: "You choose one each from culprit, weapon, and crime scene, then ask everyone.",
53648: "If anyone holds at least one of the named cards, they must answer \"I have it.\" (The point being that you don't have to say which one.)",
53649: "\"Ah… I've got one.\"",
53650: "\"Rena too.\"",
53651: "\"…Me too.\"",
53652: "\"Oh my, everyone has one, then.\"",
53653: "Three people said they held a 'Satoko,' 'Axe,' or 'Courtyard' card.\nSo all three of those were cleared of suspicion. Note, note…",
53654: "So all three of them — 'Satoko,' 'Axe,' 'Courtyard' — were in the clear. Note, note…",
53655: "\"In that case, I shall try:\n'Keiichi,' 'Knife,' 'Attic'!\"",
53656: "Hmm, only two people said they had one.",
53657: "Which means one of the three — 'Keiichi,' 'Knife,' or 'Attic' — might be the culprit, weapon, or crime scene!",
53658: "Wait, though — 'having' doesn't say how many cards you hold!",
53659: "It's possible that one of the two who answered — Rena or Mion — holds two of the three…!!",
53660: "This was… a psychological game as well.",
53661: "\"Alright, my turn~!\"",
53662: "Wa— wa-wait — I'm still catching up!",
53663: "\"Too slow, Keiichi-san!\nI'm afraid we've left you in the dust!\"",
53664: "\"Ugh, stop! Just hold on!\"",
53665: "…This game was more demanding than I'd expected.\nInside, I was starting to feel the strain… a premonition of struggle!!",
53666: "\"Everyone ready?\"",
53667: "\"…'Rena,' 'Pickaxe,' 'Riverbank'!\"",
53668: "Only one person said they had this one… which meant…",
53669: "Wait, wait — stay calm and think —",
53670: "\"Oh yeah!! Culprit confirmed!!\"",
53671: "As we fumbled along through the game, Mion suddenly raised her hand.",
53672: "\"The culprit is 'Rika-chan'!\"",
53673: "\"The weapon is the 'Dumbbell,' crime scene is 'Behind the Gym'!\nWell?!\"",
53674: "We drew the answer cards from the box to check against Mion's deduction…",
53675: "\"Correct!!\"",
53676: "\"Fuwaaah~!\nI was so close~~!\"",
53677: "\"I couldn't decide between 'dumbbell,' 'poison,' or 'pistol' — I just couldn't narrow it down!!\"",
53678: "\"Dumbbells are heavy.\nI prefer poison — nice and slow.\"",
53679: "Th-that's not the point here??\nSuch a sweet face… still totally ruthless…",
53680: "\"……Keiichi.\nPlease don't look at me with frightened eyes.\nMii~\"",
53681: "Huh? …Was my face that obvious?",
53682: "\"Ohohohohoho!\nKeiichi-san's face is always so easy to read!\"",
53683: "…Even so, this game was harder than I had imagined.\nInside, I was starting to feel real pressure.",
53684: "…And now that I looked, Rena wasn't looking so great either.\nIt seemed like she and I were at a decided disadvantage in this game.",
53685: "Our eyes met.\nShe was thinking the same thing.",
53686: "\"My my, those two~?\nYou look like you're in trouble!\nGoing to tie for last together~? Keh-keh-keh!\"",
53687: "Absolutely not!!\nA pitiful man sent to buy 'hemorrhoid cream' with girls at his side… the very thought made me shudder!",
53688: "\"…Keiichi looks like he has trouble with this game.\"",
53689: "Wh— what?!",
53690: "\"Th-that is absolutely not true!!\nNext round, I'll show you the true abilities of the great detective Maebara!\"",
53691: "\"Oh, you said it!!\nThen I shall demolish you without mercy~!\"",
53692: "\"Satoko… want another taste?\"",
53693: "I gave two or three threatening flicks of my index finger toward her — ping! ping!",
53694: "\"Fuwaaah!!\nKeiichi-san is threatening me~~!!\"",
53695: "\"There there.\n…Keiichi, resorting to force because you're not confident is unfair.\"",
53696: "\"…Yes ma'am.\"",
53697: "When Rika-chan said it, I had no choice but to reconsider.",
53698: "I reluctantly holstered my forehead-flicking weapon.",
53699: "After a few more rounds, I started to get the hang of it — but no matter what I tried, I'd always fall one step behind at the crucial moment.",
53700: "…Mion was apparently reading people's expressions as well as their questions. Just strategy alone wasn't enough to beat Mion, the self-declared 'master.'",
53701: "To overturn this overwhelming disadvantage, I would have to commit to ruthlessness…!!",
53702: "Forget deduction… switch to a winning-at-all-costs club mindset.",
53703: "The important thing wasn't to find the culprit — it was to win!!",
53704: "…Ah-ha!",
53705: "This was the play… the only play!!!",
53706: "\"Oh, sorry.\nJust going to the bathroom.\"",
53707: "I made my bet.",
53708: "Clear my head… get some fresh air, let the mind reset.",
53709: "Two, three times — breathe in~ breathe out~ — deep breaths.\nFor good measure, I extended my arms out front and swung them in wide pendulum arcs, bending deep at the knees for some good squats.",
53710: "One, two, three… focused entirely on loosening up my muscles.",
53711: "When I glanced out, I saw classmates who had also stayed after school playing noisily in the schoolyard.",
53712: "Back in Tokyo I never spent afternoons like this, playing around after school.",
53713: "Looking back on it now, why did my life back then feel, somehow, abnormal?",
53714: "My gaze, without my directing it, drifted off into the distance.",
53715: "I snapped back. I couldn't keep this up.",
53716: "There was a penalty game on the line.\nNow: would this plan work?",
53717: "The success of it would hinge entirely on teamwork.",
53718: "Just then, Rena came out of the classroom, tilting her head curiously.",
53719: "\"…Kei-kun, did you call for me?\"",
53720: "When I had stood up, I had caught Rena's eye on the way out.",
53721: "It had gotten through to her.\nWe really might be well-suited to each other.\nWith this…",
53722: "There was no time, so I asked Rena directly how many points she had at this point.",
53723: "Rena hesitated a moment, then opened her mouth tentatively.",
53724: "\"Um… let's see… points… minus six.\nWhy are you asking?\"",
53725: "I had guessed from her manner, but I hadn't expected quite this bad…",
53726: "\"At this rate, one of us is going to end up last.\"",
53727: "\"Ha-hau~, …so that means Rena's getting the penalty game? …Does it?\"",
53728: "\"Hey, don't give up so easily!\nLet's go for the win, alright?! Let's win!\"",
53729: "\"H-how?!\"",
53730: "I leaned in close to Rena's ear.\nWhisperwhisperwhisper…",
53731: "\"Ehhh~?\nI-is that… allowed? Is it?\"",
53732: "\"Remember, Rena.\nClub rule number two — spare no effort in the pursuit of victory!!\"",
53733: "\"Y-yeah… you're right!\nI'll — I'll do my best~!\"",
53734: "Rena struck a full-body fighting pose.",
53735: "Our strategy required teamwork above all else to succeed.",
53736: "When the game started and everyone was dealt their cards, there was always a brief window where everyone's eyes went to their hand to start taking notes.",
53737: "That was the moment — Rena, who sat next to me, and I would flash our cards to each other under the desk in an instant.",
53738: "Do it under the table, quick.\nKeep your pencil moving; never stop writing.",
53739: "Even if the others looked up, what draws the eye first is movement — that's just human nature.\n…That was the key.",
53740: "If it worked, we'd go undiscovered for quite a while!",
53741: "Having twice as much information as the others meant no weaknesses in our questioning either!!",
53742: "\"Hau~, you're right!\nThis way we might actually win today!\"",
53743: "\"Might win — no.\nWe will win!\"",
53744: "And then we'd send Mion out to buy 'hemorrhoid cream' and 'athlete's foot medicine'! Mufufufufu…",
53745: "\"Kei-kun, your face is… a little scary…\"",
53746: "We're going to win, Rena. A face or two can look however they want.",
53747: "\"R-right… that's also true!\"",
53748: "The two of us shared a grin.",
53749: "By the time Mion caught on, Rena and I would have gone past avoiding last place — we'd have locked up first and second…!",
53750: "This was looking good!! Watch out, Mion!!!",
53751: "After Rena went back to the classroom, I waited a beat, then followed.",
53752: "I tried not to meet Mion's eyes.",
53753: "Because as they say, the eyes say as much as the mouth.",
53754: "Mion had good instincts. If she caught on, our whole scheme would be for nothing.",
53755: "I took the utmost care.",
53756: "Unaware of my conspiracy, Mion declared with great confidence:",
53757: "\"Alright, let's resume the game!\"",
53758: "Mion thrust her arm in the air — and just then, Sensei Chie came in.",
53759: "\"Sonozaki-san.\nMight I have a moment?\"",
53760: "\"What is it, Sensei?\"",
53761: "\"Sorry everyone, just a pause.\"",
53762: "With that she stood, and went to the teacher.",
53763: "\"You have a visitor, Sonozaki-san.\nPlease go to the entrance hall.\"",
53764: "\"A visitor?\nFor me?\"",
53765: "\"That's right.\nGo quickly, please.\"",
53766: "\"Understood.\"",
53767: "\"…Anyway.\nI'll be back in a bit, everyone.\"",
53768: "With that, Mion slipped briskly out of the classroom.",
53769: "\"Who do you think is visiting Mi-chan? …Do you?\"",
53770: "\"Mi-san knows a great many people — someone visits her every now and then.\"",
53771: "\"Yes, Mii knows a lot of people.\"",
53772: "\"…I guess it can't be helped.\"",
53773: "I was watching the direction Mion had gone with a resentful look.",
53774: "What a pain — I was planning to make her cry uncle!",
53775: "…Still, a visitor for Mion — who could it be?",
53776: "\"……………\"",
53777: "We waited for a while.\nBut there was no sign of Mion coming back.",
53778: "\"…Mion-san is taking quite a while to return.\"",
53779: "\"We have nothing to do, like piggies with idle hooves.\nOink oink~\"",
53780: "\"Pi-piggies with idle hooves…? Hau~♪\"",
53781: "\"Haaau~ little piggie Rika-chan is so cuuute~!\nCan I take you hooome~?☆\"",
53782: "\"We're still in the middle of a game, you know.\"",
53783: "\"…Hauuu~?!\nBut but, she's so cute~! Hau~♪\"",
53784: "\"No matter how cute, no until the game is over.\"",
53785: "\"But just a little bit… is that not allowed? …Is it?\"",
53786: "\"After it's over.\"",
53787: "Hmm. This was a problem.",
53788: "Everyone was getting restless — idle-hooved piggies, that is — unable to sit still.",
53789: "\"Can't be helped, let's restart the game!\"",
53790: "At that, everyone's eyes lit up and they nodded.",
53791: "Right… if you think about it, this is the perfect 'while the cat's away'…\nIn a sense, the 'chance' had arrived.",
53792: "And so, with Mion's seat left empty, we shuffled the cards and dealt them out.",
53793: "Rika-chan and Satoko, predictably, put their heads down and began scribbling notes.",
53794: "Rena and I exchanged a glance and, under the pretense of taking notes, showed each other our cards under the desk.",
53795: "'Satoko'… 'Rena'… 'Pistol'… 'Cleaver'… 'Cemetery'… 'Storage Shed'…",
53796: "…Which meant all the other cards were likely to be under suspicion.",
53797: "\"Mufufu… mufufufu…\"",
53798: "Rena hurriedly jabbed her elbow into my ribs.",
53799: "\"What are you laughing about, Keiichi-san?\"",
53800: "\"…That is deeply unsettling.\nMii~\"",
53801: "…No good, no good — this was not the moment to laugh. I needed a plausible cover story…",
53802: "\"Oh… I was just imagining this group actually committing crimes! Keh-keh-keh!\"",
53803: "\"…I don't understand the logic, but somehow I find it deeply unpleasant.\"",
53804: "\"Satoko, don't engage.\nKeiichi is almost certainly trying to lead you astray.\"",
53805: "Satoko and Rika-chan exchanged a glance and giggled — \"ohohoh\" / \"nipaa~\"\nRena was sweating beside them.",
53806: "\"Then it shall be my turn, as I am currently in second place.\nI'll try… 'Rena,' 'Pistol,' 'Attic'!\"",
53807: "\"Oh, I've got one.\"",
53808: "\"Rena too.\"",
53809: "\"I have one as well.\"",
53810: "\"Is that so — everyone has one.\"",
53811: "…Which means the location… and the weapon… is at risk.",
53812: "Let me try a feint here.",
53813: "\"My turn now.\nOkay then — 'Rika,' 'Ashtray,' 'Lounge'!\"",
53814: "\"I have one.\"",
53815: "\"I do too.\"",
53816: "\"…Rena doesn't.\"",
53817: "So that means… not those, but maybe… and if so…",
53818: "As I was putting Xs in my notes, something clicked.",
53819: "\"Yesss, culprit confirmed!!\"",
53820: "\"Wha?!\nAlready?!\"",
53821: "\"Keiichi, men who are too hasty are disliked…\"",
53822: "I thrust my index finger straight up at the ceiling and proclaimed the culprit, weapon, and crime scene in full.",
53823: "\"Culprit: 'Mion'!\nWeapon: 'Axe'! Crime scene: 'Library'!\n…Well?!!\"",
53824: "We drew the answer cards from the box to check my deduction…",
53825: "\"Kei-kun, correct!!\"",
53826: "\"Ungh — and to think it was Mion-san!\"",
53827: "\"An axe is no good.\nPoison — nice and slow — that's the ideal.\"",
53828: "Rika-chan, that's just your personal preference.\nStill — a soft face hiding something hard, through and through…",
53829: "On that note, Rena and I kept up our winning streak — but Rika-chan and Satoko were no fools.",
53830: "Not long after our streak began, they started glancing back and forth between us, with precisely timed attention to our movements.",
53831: "And then, finally…",
53832: "The surprise was — what I'd taken for note-taking: Satoko had a small hand mirror under the desk.",
53833: "Through the mirror, Rika-chan's sharp gaze was staring intently — at me.",
53834: "I scrambled to cover, but it was already too late.",
53835: "\"Oh my… so that's how it was, is it… both of you.\"",
53836: "\"Mii — if that's the case, we have our own plan.\"",
53837: "Rika-chan and Satoko looked at each other and both broke into grins.",
53838: "From that point on, the game became a head-to-head between Team Rena-and-Me versus Team Satoko-and-Rika-chan, a back-and-forth battle with neither side gaining the upper hand.",
53839: "And after about an hour —",
53840: "It was in the middle of our thirteenth round that Mion finally came back.",
53841: "\"…What happened, Mi-chan?\"",
53842: "Rena noticed something and asked.",
53843: "Mion did seem off, now that I thought about it. She seemed somehow less energetic.",
53844: "\"…Hm? No, I'm fine.\"",
53845: "She said that, but the look on her face was dispirited enough that you'd want to ask if she was really all right.",
53846: "…But the next moment —",
53847: "\"Whew. …Wait — wha, whaaaaaaaaat!\"",
53848: "\"What IS thiiiis~~!!\"",
53849: "And no wonder.",
53850: "While Mion was away, the four of us had racked up a staggering number of points, leaving her far behind.",
53851: "The instant she looked at the score sheet, Mion understood: no matter how hard she tried from here, she couldn't overturn anyone's lead.",
53852: "\"Nooo~, I was going to send someone out to do my shopping today~~\"",
53853: "Just as Mion slumped in dejection, a slip of paper fluttered out of her pocket.",
53854: "I picked it up and looked… WHAT??!!",
53855: "\"Wow… there's a lot written on it.\"",
53856: "\"…Two cakes of tofu.\nShampoo and conditioner.\nMirin and fried tofu…\nWhat is this?\"",
53857: "You called it the 'Errand Sentence'…",
53858: "\"W-wait, this is the shopping list people already asked YOU to do!!\"",
53859: "Mion gave an oily little laugh.",
53860: "\"…You started this whole game just to get people to run your errands for you…\"",
53861: "But seeing Mion back to her usual self, I felt a wave of relief.",
53862: "Although — it did seem a little sad that the penalty game had been decided while she was away…",
53863: "But then —",
53864: "\"Here you go, Mi-chan.\nThese are Rena's errands, please and thank you☆\"",
53865: "…Wait, you were writing a shopping list next to me while I was worried about her?!",
53866: "\"Goodness~, we had ours ready too~~!\"",
53867: "\"…How unfortunate.\nMii~\"",
53868: "Even though it was a close thing… when did you even write those lists??!!",
53869: "I felt cold sweat trickling down my spine.\nThese people are demons…",
}

with open(BASE_DIR / 'taraimawashi_2.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for entry in data:
    if entry.get('type') not in ('MSGSET', 'LOGSET'):
        continue
    if 'TextENGNew' in entry:
        continue
    mid = entry.get('MessageID')
    if mid in TRANSLATIONS:
        entry['TextENGNew'] = TRANSLATIONS[mid]
        count += 1

with open(BASE_DIR / 'taraimawashi_2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"taraimawashi_2.json: wrote {count} translations")

with open(BASE_DIR / 'taraimawashi_2.json', 'r', encoding='utf-8') as f:
    data2 = json.load(f)
missing = [e.get('MessageID') for e in data2 if e.get('type') in ('MSGSET','LOGSET') and 'TextENGNew' not in e]
print(f"Still missing: {len(missing)}")
