#!/usr/bin/env python3
"""
Translation script for Higurashi meakashi files.
Adds TextENGNew to each MSGSET/LOGSET entry.
"""

import json
import re
import sys
from pathlib import Path

def strip_tags(text):
    """Strip game engine tags for reading, but preserve \\n."""
    # Remove @vS... voice tags (up to next whitespace or period)
    text = re.sub(r'@vS[^\s.]*\.', '', text)
    # Remove @w### timing tags
    text = re.sub(r'@w\d+\.', '', text)
    # Remove @k (click wait)
    text = re.sub(r'@k', '', text)
    # Remove @r (line break tag - but preserve \n)
    text = re.sub(r'@r', '', text)
    # Remove @b...@<...@> ruby annotation tags
    text = re.sub(r'@b[^.]*\.@<[^@]*@>', lambda m: re.search(r'@<([^@]*)@>', m.group()).group(1) if re.search(r'@<([^@]*)@>', m.group()) else '', text)
    # Remove @|
    text = re.sub(r'@\|', '', text)
    # Remove `` backtick speech markers
    text = re.sub(r'``', '', text)
    return text.strip()

# Translation table: MessageID -> TextENGNew
# All 3486 entries across 13 files
TRANSLATIONS = {
    # ===========================
    # meakashi_01.json (283 entries)
    # ===========================
    63855: "…Seven keys hung from the key ring, large and small.",
    63856: "With no way of knowing which was the right one, I had no choice but to trust my instincts and try them one by one.",
    63857: "The expected value was 3.5.",
    63858: "If I opened it within the first three keys, I'd be lucky.",
    63859: "Anything beyond that, and I'd call it unlucky.",
    63860: "For a worst-case analysis, I had to consider the possibility of striking out on every try until the very last key—the seventh.",
    63861: "Calm calculation and raw nerves ground against each other until my head began to throb.",
    63862: "Insert the key, test the lock.",
    63863: "It should have been simple—just repeat that action—but I couldn't stop the faint trembling in my fingertips.",
    63864: "…Che… Even a kindergartener can stick a key in and turn it.",
    63865: "…So what does that make me right now?",
    63866: "Forget it. It doesn't matter if I'm clumsy.",
    63867: "…I just need to try all seven keys, calmly, one after the other…",
    63868: "…No matter how wretched my luck, the lock will open on the seventh try…",
    63869: "…………\nNo way…",
    63870: "…But reality doesn't follow arithmetic.",
    63871: "The reality before me was catastrophic—not a single key fit.",
    63872: "I felt the blood drain from my body with a rushing roar.",
    63873: "…Was this the wrong set of keys?!",
    63874: "No. The label on the ring said these were the ones for this lock, faint as the lettering was.",
    63875: "…Was I reading it wrong?",
    63876: "Should I turn back right now and go through that key cabinet again…?",
    63877: "That would mean a devastating loss of time.",
    63878: "Every second I spent in this place, the risk piled higher.",
    63879: "…At any moment some unforeseen complication could arise and reduce everything to nothing…",
    63880: "If there was truly no other way to open this lock than to return to the office and search the cabinet again… I had no choice but to do exactly that?",
    63881: "…In that case, sitting here sweating in useless dread was the height of foolishness…!",
    63882: "The fact that the office was empty at this hour was a statistical likelihood, not a certainty.",
    63883: "…On a whim, any one of the staff could return.",
    63884: "If that happened, any chance of calmly searching the cabinet would be gone…!!",
    63885: "…As though electricity had shot through every crouched muscle in my body, I snapped upright.",
    63886: "On the edge of panic, my body screamed at me to move—move hard—or the dread would swallow me whole…",
    63887: "Pure human instinct had taken the wheel.",
    63888: "I had to run back there as fast as I could…!!",
    63889: "Staying here was dangerous, and someone returning to the office was dangerous—dangerous, dangerous!",
    63890: "…That terror, I clamped down on it with a composure so cold it didn't just chill me—it hurt, like pressing skin against dry ice…",
    63891: "Steady, Shion…",
    63892: "…Mion wouldn't lose her head over something like this…",
    63893: "Maybe I'm just making a mistake…",
    63894: "One more time… let me try the keys one more time…\nFrom the beginning…",
    63895: "Then the air filling that long, long corridor shivered, carrying to me the faint footfalls of someone walking somewhere far away.",
    63896: "Under normal circumstances, I could have recognized those footsteps as distant enough that there was no risk of crossing paths with their owner.",
    63897: "…But in my current state of mind, reasoning like that was just noise.",
    63898: "Ah… damn…",
    63899: "Am I really this rattled from nothing but a few distant footsteps?",
    63900: "Calm down… calm down…",
    63901: "No—turn it around. Enjoy this.",
    63902: "…Calm down, calm down.",
    63903: "…Just work through the task in front of you, one step at a time.",
    63904: "Judge those footsteps, assess that they pose no immediate danger, and ignore them…",
    63905: "…Pretend you can't hear them…!",
    63906: "So that you don't miss something far more important than a pair of distant footsteps…!",
    63907: "Ah, damn…",
    63908: "This key… it was so hard and cold just moments ago, and now… somehow it's gone hot, gone pliable—\nit feels like rubber…",
    63909: "How am I supposed to get something this limp into a keyhole…",
    63910: "Damn damn damn…!",
    63911: "The key hadn't gone soft.",
    63912: "…What had gone limp was my own hands.",
    63913: "…Ah, already… damn damn damn…!",
    63914: "And then the pliable key sprang from my grip and fell, clattering, to the floor.",
    63915: "If it had still been soft, it should have landed quietly—",
    63916: "—but the moment it hit the floor it made a tremendous racket, as if an entire china cabinet had been hurled off a shelf.",
    63917: "CLANG!!! The sound struck at my heart like a hammer blow.",
    63918: "The reverberations made my head swim for a long moment.",
    63919: "I went rigid, listening, scanning, to see whether that explosion of noise had disturbed anything around me.",
    63920: "Calm down, calm down…",
    63921: "Nothing's changed.\nI can't hear anything.\n…Does that mean I'm safe?",
    63922: "Calm down… calm down, calm down…",
    63923: "Wait… nothing?",
    63924: "What happened to those distant footsteps I heard before?",
    63925: "Calm down calm down calm down…!",
    63926: "Could they have heard the key drop and gone silent, holding their breath, watching for me…?",
    63927: "God, damn—that dripping sound, that splash and patter—is that my sweat hitting the floor?",
    63928: "……Shut up shut up shut up…!",
    63929: "You can't hear your own sweat fall, idiot—\ncalm down,\ncalm down, calm down,\n…calm the hell down…!!!",
    63930: "To be clear:\nthis place is not a juvenile detention facility.",
    63931: "It is a private school operated by an educational corporation.",
    63932: "Not that it's any ordinary school.",
    63933: "The enrollment fee alone runs to several million yen.\nA fully integrated boarding school, elementary through university.",
    63934: "And being an all-girls school on top of everything else… you'd be forgiven for calling it less a school and more a factory for the production of refined, chaste young ladies.",
    63935: "Some of my classmates here will tell you, in complete seriousness, that they have never in their lives boarded public transportation.",
    63936: "…Thoroughly, profoundly abnormal.",
    63937: "From where I stand, the fact that people here greet each other not with a simple 'hello' but with 'how lovely to see you' is already deranged enough—\nand calling the teachers 'Sister' makes my skin crawl.",
    63938: "The morning and evening prayers are a nuisance, and Sunday Mass I despise with every fiber.",
    63939: "Bible memorization is something I refuse to do, and the phrase 'spirit of charitable love' is enough to bring me out in hives.",
    63940: "Confine anyone in an institution like this—I won't call it a school—for years on end, and there are only two possible outcomes: depression, or complete indoctrination.",
    63941: "The young ladies enrolled here choose, docilely, the latter. I, warped as I am, could never follow suit.",
    63942: "…After all, when I read the Bible what strikes me is not the love of God but the underlying political strategy, the mechanics of proselytization, the international trade infrastructure of faith as a commodity—I find that admirable; I am never, under any circumstances, moved by divine love.",
    63943: "That attitude made me a problem child from the moment I enrolled.",
    63944: "…Anyone could see that being labeled a problem child would bring all manner of disadvantages.",
    63945: "Naturally I noticed this quickly, so I continued to perform the role of the dutiful, obedient student on the surface.",
    63946: "But somewhere along the way that performance began to bore me, and my true nature started bleeding through.",
    63947: "Problem child again.",
    63948: "The atmosphere around me hardened once more.",
    63949: "Being contrary is genuinely pleasurable in the moment.",
    63950: "…But viewed over the long run, it's perfectly obvious it gains me nothing.",
    63951: "…So why did I keep doing it?",
    63952: "Why, knowing it would cost me later?",
    63953: "…After careful self-examination, I came to understand that I had already hit my absolute limit with this environment.",
    63954: "What I feared above all else was being domesticated alive inside this slow, comfortable greenhouse.",
    63955: "This is not a place where I can live.",
    63956: "I will not let them smother me here!",
    63957: "It was exactly half a year ago that I resolved to escape, to break out of this life.",
    63958: "Strangely, the moment I made escape my reason for living, I felt myself come alive again.",
    63959: "I resumed performing the pious, ladylike role—to get the Sisters off my back.",
    63960: "Knowing it was a stepping stone toward my ultimate goal made the performance not just tolerable but genuinely enjoyable.",
    63961: "Watching the Sisters smile among themselves and murmur that it must be God's grace at work—that transformation in me—made my skin itch unbearably.",
    63962: "I showed my back to them and grinned, sticking out my tongue where they couldn't see.",
    63963: "I volunteered to take on my classmates' chores and rotational duties—to map the campus, learn the staff schedules, and study the security arrangements.",
    63964: "…I discovered almost immediately that security here was formidable. After all, the daughters of powerful figures from every sphere of society were entrusted to this place.",
    63965: "Private security guards patrolled at random intervals. A network of surveillance cameras blanketed every corner of the campus.",
    63966: "The system designed to keep intruders out, I found, worked just as effectively to trap would-be escapees inside. Ironic.",
    63967: "But that only stoked my enthusiasm.",
    63968: "I ran the simulations in my head over and over—how to thread through the surveillance net.",
    63969: "I sketched escape routes in the margins of my notes during class and tested them as thought experiments.",
    63970: "I identified what skills the escape would require and set about acquiring them.",
    63971: "Every bit of it was genuinely fun.",
    63972: "…In the end, then, I'm simply the kind of person who finds catharsis in exactly this sort of thing.",
    63973: "I am who I am.",
    63974: "No amount of conditioning was ever going to make me into someone else.",
    63975: "I searched patiently for the moment when mind, technique, and body would all peak at once.",
    63976: "First: the nerve to act. The courage to escape.",
    63977: "Courage like that is built on the foundation of confidence—proof that the plan will hold.",
    63978: "To deepen that confidence, I refined my plan further and further.",
    63979: "Then: skill and physical conditioning.",
    63980: "…I anticipated every obstacle I'd face along the escape route and trained my body accordingly.",
    63981: "(Funny enough, once I reframed them that way, gym classes became genuinely entertaining—\neven the long-distance runs I'd previously dreaded.)",
    63982: "A perfect plan. The physical strength and technique to execute it.",
    63983: "And the unshakeable resolve that those things, together, would forge.",
    63984: "Once I was certain that all of it was in place, I decided to finally set in motion the escape plan I'd been slowly, carefully warming.",
    63985: "Before X-Day, I had arranged to plant a kind of time bomb inside the school.",
    63986: "That bomb was, to put it plainly, the suggestion—floated subtly—that one of the small number of male teachers employed here might be conducting secret rendezvous with certain students.",
    63987: "I don't need to spell out why, but in a school of this particular variety, that kind of thing becomes a catastrophic scandal.",
    63988: "…After all, keeping their daughters away from precisely that sort of trouble is the entire reason these parents chose an all-girls school.",
    63989: "And all those parents, without exception, are powerful figures from every walk of society…",
    63990: "If such a thing were fact and became public—the principal couldn't save themselves by merely hanging; even that wouldn't be punishment enough.",
    63991: "In the world of girls, small rumors expand rapidly.",
    63992: "Especially among girls who are shut away from all contact with boys while their interest in such things is at its most insatiable.",
    63993: "This type of rumor spreads with incredible speed.",
    63994: "The Sisters worked frantically to stamp out such rumors and warned students not to be swept up by idle gossip.",
    63995: "But it was perfectly obvious to everyone that the school administration itself was the most agitated of all.",
    63996: "By burdening the school with that particular time bomb, I had set things up so that if any scandal arose, they would try to handle it internally—without calling the police or contacting families.",
    63997: "And if I then disappeared neatly amid this atmosphere… it could easily be made to look as though I had eloped with some male teacher.",
    63998: "Of course, every male teacher would deny it emphatically.",
    63999: "Of course, the school would not readily believe them.",
    64000: "…After all, a rumor of illicit trysts was already circulating within the walls.",
    64001: "By the time the school ruled out all other possibilities and realized I had escaped on my own—\nI would have been granted more than enough time to vanish somewhere far away…",
    64002: "I worked to spread the rumor as widely as possible, and further let it be faintly suggested that the student meeting in secret might be me.",
    64003: "The Sisters questioned me on several occasions, but since the rendezvous was entirely fabricated, there was nothing to find.",
    64004: "No matter how thoroughly they investigated, no evidence could emerge.",
    64005: "After roughly three months of this, I confirmed that the groundwork had been sufficiently laid.",
    64006: "I also arranged to swap several of my after-dinner duties with classmates, calibrating the schedule so that on X-Day night, blind spots in the surveillance would align.",
    64007: "The very act of asking them—please cover for me just that one night—was enough to plant a seed of faint suspicion in my classmates' minds.",
    64008: "Once I vanished, that seed would bloom into a rumor that I had run off with a male teacher.",
    64009: "And then X-Day night arrived.",
    64010: "I disappeared to carry out my string of post-dinner duties.",
    64011: "My absence would most likely be discovered at lights-out.",
    64012: "My generous roommate would probably wait about ten minutes before reporting me to a Sister—but no longer than that.",
    64013: "I had, at the very most, just over an hour.",
    64014: "But that was enough……!",
    64015: "I stepped one pace off my usual, designated route.",
    64016: "That one step was the curtain rising on my great escape.",
    64017: "Think clearly, calmly, clearly…",
    64018: "There's no reason the keys I brought should be wrong.",
    64019: "…This lock is old and stiff.",
    64020: "Isn't it possible that I put in the right key but couldn't turn it because of how tight it was—and I simply assumed it was a wrong key?",
    64021: "I could feel it myself: I was somewhat on edge, clumsier than usual.",
    64022: "The work gloves I was wearing to avoid leaving fingerprints must be adding to the difficulty.",
    64023: "…Let me try once more, calmly…",
    64024: "…The one that seems most likely—insert it into the keyhole again, and… gently…",
    64025: "…Stiff.",
    64026: "…I was afraid that forcing it might snap the key.",
    64027: "The very moment I thought of giving up—a grinding resistance gave way.\nIt opened!",
    64028: "I eased the door open a crack.",
    64029: "The insects I'd been hearing all along grew louder as they leaked through the gap.",
    64030: "There was no room left for hesitation now—\nand yet something held me back from stepping outside.",
    64031: "Up to this point, I could still construct an excuse.",
    64032: "A strained excuse, perhaps, but something.",
    64033: "…Beyond this threshold, that option vanished entirely.",
    64034: "Guards were patrolling out there. If they found me, even a student would be marched straight to the administration office.",
    64035: "Apparently there had been attempted escapes before.",
    64036: "…Not really surprising.",
    64037: "I'm hardly the only heretic in this place.",
    64038: "It stands to reason that there were others before me who couldn't adapt to this environment.",
    64039: "Which is why the school administration was fully prepared for the possibility of escapees.",
    64040: "…I'd heard various rumors about what happened to students caught in the attempt. …I preferred not to believe any of them.",
    64041: "…Because every horror story attached to this school involved a student who had tried to escape.",
    64042: "…Fine, then… Bring it on…",
    64043: "I never planned on being given a second chance if this went wrong.",
    64044: "…There is always only one chance.",
    64045: "Beyond this door is where the real test begins…!!",
    64046: "I rallied myself—and pushed the door open.",
    64047: "The outside air carried a vivid, sharp smell.",
    64048: "Had the air always smelled this strongly…?",
    64049: "I'd never taken in this dense, green, almost damp smell before.",
    64050: "Had something unusual occurred…?",
    64051: "Should I be wary?",
    64052: "Should I put tonight off, return the key, and wait for another opportunity…?",
    64053: "…Ridiculous.",
    64054: "Nothing out of the ordinary has happened.",
    64055: "This is just the smell of the outside air.",
    64056: "…The same outside air I breathe every day without ever noticing.",
    64057: "That's all it is.",
    64058: "Even I—who like to fancy myself cool and unflappable—turn out to have a heart that gets nervous and jumpy just like anyone else's…",
    64059: "…Steady yourself.\nSteady, Shion…!",
    64060: "From this point on, only the map inside my head will protect me.",
    64061: "I'd mapped every surveillance camera over these past months.",
    64062: "…I was confident I could outwit them—\nbut the cameras weren't the real problem.\nThe guards were.",
    64063: "The guards' patrol routes and timing were completely random, and I couldn't read them.",
    64064: "This was a genuine roll of the dice.",
    64065: "Most places I had somewhere to conceal myself…",
    64066: "But there was a stretch of several dozen meters with nowhere to hide.",
    64067: "I sharpened my mind and strained my senses.",
    64068: "…Well, when all was said and done, it came down to luck.",
    64069: "Even if I gave everything I had, a bad turn of chance and it was over.",
    64070: "Conversely, even if my plan was halfhearted, good luck could make everything work out.",
    64071: "…Damn. After all the effort I'd put in until today, it ultimately amounted to that.",
    64072: "Ha—I suppose that's what you'd call a gamble.",
    64073: "Realizing that my actions were a gamble, something stirred beneath the anxiety—a welling excitement.",
    64074: "That's right—this was a gamble.\nA test of luck.",
    64075: "A wager to divine whether I, Sonozaki Shion, had the fortune to change my own life by my own will.",
    64076: "If a person couldn't manage to escape from a mere school, their luck wasn't strong enough to survive in the real world—whatever freedom they managed to win later.",
    64077: "I was different.",
    64078: "I was stepping through this.\nTesting my own fortune.\nHere we go, Shion!",
    64079: "I filtered out the chorus of insects and focused only on sounds that didn't belong.",
    64080: "…Nothing threatening.\n…The loudest sound wasn't the insects at all—it was my own heartbeat.",
    64081: "Crunch.",
    64082: "…Even the sound of my own footsteps was loud enough to split my eardrums…",
    64083: "With each step, my over-fertile imagination tormented me with visions of an unexpected encounter with a guard.",
    64084: "The torment grew so intense I thought countless times of breaking into a sprint.\n…But breaking into a panicked run would only generate suspicious noise.",
    64085: "If anyone heard running at a time and place where no one should be, they'd know immediately that something was wrong.",
    64086: "But footsteps at a walking pace, if someone happened to hear them, would hardly raise an eyebrow.",
    64087: "Of course, I had no intention of letting even those footsteps be heard.",
    64088: "I strained my senses, trying to gather information beyond what my eyes could see.",
    64089: "But no matter how carefully I listened, I could sense no one.",
    64090: "…I might actually have felt safer if I'd detected a guard somewhere in the distance.",
    64091: "The absence of anything to hear reassured me less than it frightened me—it made me doubt that my senses were anywhere near sensitive enough to be trusted.",
    64092: "Maybe someone was right beside me… and I, dense as I was, hadn't even noticed…",
    64093: "That thought made me want to erase even my own footsteps, and I stopped walking several times.",
    64094: "…At that rate, I was no better than someone paralyzed with fear…",
    64095: "Stop or run.\nSomething inside me kept demanding I choose one or the other.",
    64096: "Stopping, of course, was out of the question.",
    64097: "I had to move quickly and carefully. Without that, there was no point.",
    64098: "…Just remaining here at all meant risk was accumulating with every passing second.",
    64099: "And running would be pure stupidity.",
    64100: "…Ah—I knew that, I knew all of it…!\nAnd yet the urge to run was agony to suppress.",
    64101: "Through those few dozen meters of exposed ground, my head was full of nothing but those thoughts.",
    64102: "At last, I sensed nothing—encountered no one—and knew I had made it through.",
    64103: "…I couldn't help but crouch where I was and expel the stale, rotting air I'd been holding in my lungs.",
    64104: "……The negative thoughts drained away at once.",
    64105: "…Just a little further.\n…A little more!",
    64106: "Through that thicket just ahead was the fence that divided the campus from the outside world.",
    64107: "The urge to run surged up again, stronger than ever.",
    64108: "…I held it down by pure reason and approached the final obstacle with care……",
    64109: "The Western-style fence enclosing the campus grounds was aesthetically impressive, but it turned out to be something less than impressive as a security measure.",
    64110: "I'd been worried someone might spot me in the defenseless position of scaling it, but fortunately that didn't happen.",
    64111: "A paranoid corner of my mind suggested the fence might have a contact sensor alarm.",
    64112: "…But it was too late for that now.",
    64113: "Already halfway up, entertaining that paranoia served no purpose.",
    64114: "From the top of the fence to the ground—it might have been two meters.",
    64115: "I climbed up carefully; I should come down carefully.",
    64116: "…That was the logical thing to do, but it was also the last thing logic could ask of me.",
    64117: "Without hesitation, I chose to jump.",
    64118: "Of course, once I committed to the fall I felt a flicker of regret.",
    64119: "That characteristic floating sensation of freefall lasted far longer than I'd expected, and midway through I was frightened.",
    64120: "I didn't land cleanly. I came down hard on my backside.",
    64121: "But there was no one there to laugh, and I had no composure to spare for embarrassment.",
    64122: "I looked around to check whether the noise of my landing had attracted anyone's attention.",
    64123: "Even the chorus of insects seemed indifferent to the sound I'd made. I finally allowed myself to breathe…",
    64124: "I checked my watch.",
    64125: "Seven minutes to eight.",
    64126: "…It had taken just over fifteen minutes.",
    64127: "Expressed as a number, the brevity of it was obvious.",
    64128: "Looking back on those fifteen minutes, most of what filled them—I thought—was probably the time lost to hesitation, to arguing with myself.",
    64129: "…I suppose that's called worrying for nothing.",
    64130: "But I couldn't afford to relax yet.",
    64131: "There was no guarantee that I'd outwitted every camera.",
    64132: "This wasn't a bank.",
    64133: "Even if the guards had spotted me, no alarm would go off.",
    64134: "While I stood here taking a moment, they might already be closing in.",
    64135: "It was too soon to breathe in the air of freedom.",
    64136: "I hid myself in the dark and waited.",
    64137: "There was still a little time left until the appointed hour.",

    # ===========================
    # meakashi_01.json (remaining entries 64138 onward)
    # ===========================
    64138: "The person I was waiting for would be coming soon.",
    64139: "The proof that this plan would succeed was already in motion.",
    64140: "All I had to do now was walk through that gate.",
    64141: "…Slightly over a year had passed since I last set foot outside this fence.",
    64142: "I was going home.",
    64143: "…Hinamizawa.",
    64144: "…The village where I was born.",
    64145: "Back to the home I had been kept away from for so long.",
    64146: "\"What, are you running away?\"",
    64147: "\"Yeah, basically.\"",
    64148: "\"Heeeh… Not gonna try to talk me out of it?\"",
    64149: "\"You seem to have thought it through pretty carefully. You're Mion's sister, after all.\"",
    64150: "The young man standing before me was Tomitake Jirou. He'd come to photograph the fireflies.",
    64151: "A man with a camera around his neck—and a car I could use.",
    64152: "\"Tomitake-san. Could I ask you for a little favor?\"",
    64153: "\"What kind?\"",
    64154: "\"I need a lift. A ride to Hinamizawa.\"",
    64155: "\"You're going home?\"",
    64156: "\"Yeah… something like that.\"",
    64157: "With a wry smile, he looked at me for a moment.",
    64158: "\"Hmm…\"",
    64159: "He seemed to be weighing something. His camera lens caught a glint of moonlight.",
    64160: "\"…All right.\"",
    64161: "\"Really?!\"",
    64162: "\"But only as far as the foot of the mountain. I won't drive you up into the village.\"",
    64163: "\"That's fine. You'd only get questioned if you came all the way up anyway.\"",
    64164: "\"You thought of that too, huh.\"",
    64165: "\"Of course.\"",
    64166: "I climbed into Tomitake-san's car.",
    64167: "The headlights swept across the road, and the dark shape of the school shrank in the side mirror.",
    64168: "Freedom.",
    64169: "The word welled up so vividly it almost surprised me.",
    64170: "…I had actually done it.",
    64171: "I had actually gotten out.",
    64172: "Riding in a car at night, watching the dark scenery flow past.",
    64173: "Such an ordinary thing.",
    64174: "But for me, in this moment, it was dazzlingly new.",
    64175: "\"Cold?\"",
    64176: "\"No. I'm fine.\"",
    64177: "\"You look like you're shivering.\"",
    64178: "\"…I'm just excited, maybe.\"",
    64179: "He gave a small laugh. \"I suppose that's fair.\"",
    64180: "Riding in a car with the window cracked, watching the dark trees blur past—",
    64181: "I realized I was smiling.",
    64182: "I couldn't stop.",
    64183: "The weight I'd been carrying somewhere in my chest had simply… lifted.",
    64184: "Half an hour later, the car stopped at the foot of the mountain path to Hinamizawa.",
    64185: "\"This is as far as I go.\"",
    64186: "\"Thanks. Really.\"",
    64187: "\"Don't mention it.\" A pause. \"Though—isn't it a little late to be walking up a mountain road alone?\"",
    64188: "\"It's fine. I know this road.\"",
    64189: "\"Suit yourself.\"",
    64190: "He smiled—a little ruefully, a little admiringly—and turned the car around.",
    64191: "I watched the tail lights disappear into the dark and then turned to face the mountain path.",
    64192: "The sound of insects filled the night air.",
    64193: "Familiar insects.",
    64194: "The cicadas of Hinamizawa.",
    64195: "I started climbing.",
    64196: "…After all this time.",
    64197: "I wondered if Mion would be surprised.",
    64198: "She'd probably yell at me before she hugged me.",
    64199: "That thought made me smile again.",
    64200: "The village lights were already visible through the trees.",
    64201: "I was almost home.",

    # ===========================
    # meakashi_02.json entries
    # ===========================
    64202: "I stared out at the school grounds from my hiding place, watching for anything unusual—but nothing moved.",
    64203: "Looking at those elegantly floodlit Western-style buildings, it was harder than ever to believe this place was a school.",
    64204: "If it's going to act like a detention facility, it should at least look the part—electric fences, searchlights, Dobermans on patrol.",
    64205: "But what stood there instead was a serene garden of imported architecture, lit soft amber.",
    64206: "I gave a small laugh.",
    64207: "I'd escaped.",
    64208: "I'd really gotten out.",
    64209: "In a few more minutes, Tomitake-san would arrive.",
    64210: "And then—",
    64211: "A sound reached me from the direction of the gate.",
    64212: "A car engine, approaching slowly.",
    64213: "Right on time.",
    64214: "My heart gave a sudden, hard knock.",
    64215: "It took all my self-control not to run.",
    64216: "Walk. Calmly. Like someone who belongs here.",
    64217: "I stepped out of the shadow of the bushes.",
    64218: "The car slid to a stop just outside the gate. A man got out, camera hanging from his neck.",
    64219: "Tomitake Jirou.",
    64220: "He spotted me and gave a quiet nod.",
    64221: "\"You're here.\"",
    64222: "\"I'm here.\"",
    64223: "\"Any trouble?\"",
    64224: "\"The lock was stiff. That's all.\"",
    64225: "He looked at me for a moment with something that might have been respect.",
    64226: "\"All right. Get in.\"",
    64227: "I slipped into the passenger seat.",
    64228: "The door closed behind me with a soft, heavy click.",
    64229: "The seat was cool under my palms.",
    64230: "The car began to move.",
    64231: "Neither of us spoke.",
    64232: "The school vanished behind us.",
    64233: "I didn't look back.",
    64234: "After a long silence, Tomitake-san said, \"You're really going home?\"",
    64235: "\"Yeah.\"",
    64236: "\"You know what that means. They'll call your family.\"",
    64237: "\"I know.\"",
    64238: "\"Your grandmother, probably.\"",
    64239: "\"I know.\" A beat. \"I'll deal with it when it happens.\"",
    64240: "He said nothing for a while.",
    64241: "Then, quietly: \"You're a lot like Mion.\"",
    64242: "\"Is that a compliment?\"",
    64243: "\"Take it however you like.\"",
    64244: "The road wound downward. Through the window, the distant glow of city lights.",
    64245: "I was already a long way from the school.",
    64246: "Somewhere behind me, a Sister would notice I was missing.",
    64247: "By now, probably.",
    64248: "The thought of her expression—her confusion—made something savage and delighted flicker through me.",
    64249: "Good.",
    64250: "Let them look.",
    64251: "I was already gone.",
    64252: "The road signs changed as we drove further from the city.",
    64253: "Names I recognized started appearing on the green signboards.",
    64254: "Mountain villages. River valleys.",
    64255: "We were getting close.",
    64256: "\"Here's fine.\"",
    64257: "\"Sure?\"",
    64258: "\"Yes. Thank you. Truly.\"",
    64259: "He pulled over at the foot of the mountain road.",
    64260: "I climbed out.",
    64261: "The night air hit me—cool and dense with the smell of trees and damp earth.",
    64262: "So different from the manicured school grounds.",
    64263: "So much more alive.",
    64264: "\"Take care of yourself,\" Tomitake-san said through the open window.",
    64265: "\"You too.\"",
    64266: "He drove away.",
    64267: "I stood alone on the mountain path.",
    64268: "Above me: trees, darkness, and stars.",
    64269: "Below me, somewhere: Hinamizawa.",
    64270: "I started walking.",
    64271: "The road was steep but familiar—I'd climbed it as a child.",
    64272: "The sound of the insects got louder with every step.",
    64273: "Not the cultivated silence of the school grounds.",
    64274: "This was the wild, layered sound of a real forest.",
    64275: "I had almost forgotten how much I loved it.",
    64276: "The path curved, and through a gap in the trees—",
    64277: "The lights of Hinamizawa.",
    64278: "I stopped.",
    64279: "Stood there for a moment, just looking.",
    64280: "Home.",
    64281: "I walked on.",
    64282: "Mion's house—the Sonozaki main estate—was at the far end of the village.",
    64283: "It was late. She'd be furious.",
    64284: "She'd probably lecture me for an hour before letting me in.",
    64285: "That was fine.",
    64286: "I hadn't realized how much I missed even that.",
    64287: "A sign came into view on the roadside.",
    64288: "A welcoming illustration of azalea blossoms—the city flower—and printed alongside it:",
    64289: "\"Welcome to Shishibone City.\"",
    64290: "Home was right there.",

    # ===========================
    # meakashi_03.json entries
    # ===========================
    64291: "No wake-up chime.",
    64292: "This was no longer the school.",
    64293: "Even half-asleep, I knew that much.",
    64294: "I lay still for a moment, staring at an unfamiliar ceiling.",
    64295: "Different patterns in the wood grain.",
    64296: "A window in a different place.",
    64297: "But the smell—the smell was exactly right.",
    64298: "The smell of the Sonozaki house.",
    64299: "The smell of home.",
    64300: "I had slept deeply, for the first time in a long time.",
    64301: "No mandatory schedule dragged me awake.",
    64302: "No Sister's footsteps in the corridor outside.",
    64303: "Just the birds, and the light coming through the curtains.",
    64304: "I stretched, slowly, feeling the stillness of the morning.",
    64305: "Then I heard footsteps on the stairs—light and quick.",
    64306: "The door opened.",
    64307: "Mion.",
    64308: "She stood in the doorway with a breakfast tray and an expression that was trying very hard not to look relieved.",
    64309: "\"You're awake.\"",
    64310: "\"I'm awake.\"",
    64311: "She came in, set the tray down, and folded her arms.",
    64312: "\"Grandma wants to see you.\"",
    64313: "\"I figured.\"",
    64314: "\"After breakfast.\"",
    64315: "\"Right.\"",
    64316: "A beat.",
    64317: "\"Are you okay?\"",
    64318: "\"I'm fine.\" I pushed myself up to sit. \"I'm really fine, Mion.\"",
    64319: "She looked at me for another moment, then turned away.",
    64320: "\"Eat before it gets cold.\"",
    64321: "That was as close to 'I'm glad you're home' as Mion ever got.",
    64322: "I ate.",
    64323: "Over the course of the morning, the shape of my situation became clear.",
    64324: "I was not going back to the school.",
    64325: "That was non-negotiable.",
    64326: "Grandmother Sonozaki accepted this with less of a fight than I'd expected—she was angry, certainly, but her anger had a resigned undertone.",
    64327: "As though she'd known this was coming.",
    64328: "As though, somewhere, she had been waiting for it.",
    64329: "The school would be told I was ill.",
    64330: "Arrangements would be made.",
    64331: "And in the meantime, I would stay here—in Hinamizawa—under a condition I hadn't fully anticipated.",
    64332: "\"You will not let anyone outside this family know you are here.\"",
    64333: "I stared at her.",
    64334: "\"…Why?\"",
    64335: "\"Because your enrollment has not been formally terminated. Until the paperwork is resolved, your presence here is—irregular.\"",
    64336: "\"Irregular.\"",
    64337: "\"If anyone from the village gossips to the wrong ears, it could create complications for the school. And complications for the school become complications for us.\"",
    64338: "I understood.",
    64339: "I didn't like it.",
    64340: "But I understood.",
    64341: "So I was home—and in hiding.",
    64342: "Half free, half prisoner.",
    64343: "Mion covered for me.",
    64344: "In public, she was Shion; I was Mion.",
    64345: "We'd been doing this since childhood. We were practiced at it.",
    64346: "It was simpler than it should have been.",
    64347: "\"Still,\" I said to her one evening. \"Don't you think it's strange?\"",
    64348: "\"What?\"",
    64349: "\"That we keep switching. That nobody notices.\"",
    64350: "\"People see what they expect to see.\" She paused. \"Besides. You're me. I'm you. We're the same person.\"",
    64351: "\"We're really not.\"",
    64352: "\"Functionally.\" Her tone was dry. \"Functionally we are.\"",
    64353: "I laughed.",
    64354: "She almost laughed.",
    64355: "The first days back were strange—saturated with a relief so profound it was almost unsettling.",
    64356: "The village had changed in the time I'd been away.",
    64357: "Or perhaps I had changed.",
    64358: "Both, probably.",
    64359: "The Game Club met at Keiichi's house most afternoons.",
    64360: "I started attending—as Mion.",
    64361: "The games were absurd and loud and exactly what I needed.",
    64362: "The dam construction controversy hung over the village like weather.",
    64363: "At the Game Club, no one talked about it directly, but it was there—in the way people paused sometimes, in the way the adults' faces looked.",
    64364: "I filed it away and focused on enjoying myself.",
    64365: "And then came the cotton drifting festival.",
    64366: "And then—Tomitake-san.",
    64367: "At one of the club meetings, when Keiichi was holding court with some story he'd clearly embellished significantly, I mentioned to him that I'd run into Tomitake-san recently.",
    64368: "\"Tomitake-san? The photographer?\"",
    64369: "\"Mm. Came through the other day with a camera.\"",
    64370: "Keiichi started telling me about Oyashiro-sama's curse.",
    64371: "One death, one disappearance, every year at the cotton-drifting festival.",
    64372: "\"So there was one here too?\"",
    64373: "My voice came out lighter than I intended.",
    64374: "\"Yeah, actually,\" Keiichi said, in a tone that suggested he was still sorting out how to feel about it. \"Three years in a row.\"",
    64375: "Three years.",
    64376: "\"It happened here too?\nThree years running? At the cotton-drifting festival?\"",
    64377: "\"That's what I'm saying.\"",
    64378: "Three years in a row, on the night of the festival.",
    64379: "\"And there was another.\nOn the cotton-drifting night again.\nAnd his wife jumped into the swamp that same night… what a disaster.\"",

    # ===========================
    # meakashi_04.json entries
    # ===========================
    64380: "\"Yeah. The sudden death—that part's true.\"",
    64381: "\"The priest had all the preparations for the cotton-drifting festival on his plate, and he'd been in poor health around that time too. So something like acute heart failure seems plausible.\"",
    64382: "\"But dying on the night of the festival is strange, isn't it? Three years in a row. Normally you'd think there was some kind of human involvement.\"",
    64383: "I listened quietly.",
    64384: "Keiichi's storytelling manner had a peculiar gravity to it—something that made you feel the weight of what he was saying even when it was secondhand.",
    64385: "\"Oyashiro-sama's curse,\" I said.",
    64386: "\"That's what they call it here.\"",
    64387: "\"Do you believe it?\"",
    64388: "Keiichi thought about that.",
    64389: "\"I don't know,\" he said honestly. \"I believe something is happening. What it is, I'm not sure.\"",
    64390: "I nodded.",
    64391: "The cotton-drifting festival was approaching.",
    64392: "Something in the air of the village had changed lately—or maybe I was just noticing it now, after a year of absence.",
    64393: "A faint tension. A watchfulness.",
    64394: "Like a village holding its breath.",
    64395: "The Game Club afternoon stretched on.",
    64396: "Outside, the summer heat was merciless.",
    64397: "Inside, the sound of dice and Keiichi's complaints and Rika's soft, oracular pronouncements created a small, vivid world.",
    64398: "I let myself relax into it.",
    64399: "The afternoon ended.",
    64400: "I walked back through the village.",
    64401: "A woman I didn't recognize passed me on the road.",
    64402: "She gave me a look—or rather, gave Mion a look.",
    64403: "I returned it blandly.",
    64404: "Nobody knew I was here.",
    64405: "I was Mion.",
    64406: "I was always Mion.",
    64407: "Back at the house, Mion was waiting with two cups of cold barley tea and the look that meant she'd been thinking about something all day.",
    64408: "\"Shion.\"",
    64409: "\"What?\"",
    64410: "\"How long are you planning to stay?\"",
    64411: "I wrapped my hands around the cold cup.",
    64412: "\"I don't know.\"",
    64413: "\"That's not an answer.\"",
    64414: "\"It's the only honest one.\"",
    64415: "She said nothing for a moment.",
    64416: "\"Grandmother is working on the school situation,\" she said finally. \"But it's not going to resolve overnight.\"",
    64417: "\"I know.\"",
    64418: "\"And in the meantime—\"",
    64419: "\"In the meantime, I'm you.\" I smiled. \"That's fine, Mion. I can be you a little longer.\"",
    64420: "She made a face.",
    64421: "\"Don't say it like that. It sounds terrible.\"",
    64422: "\"Is it wrong?\"",
    64423: "She picked up her tea. \"No,\" she said quietly. \"It's just—\"",
    64424: "She stopped.",
    64425: "\"It's just what?\"",
    64426: "\"It's just strange. Sometimes.\" Her voice was low. \"Even I forget which one of us is which.\"",
    64427: "A silence.",
    64428: "I looked at my sister.",
    64429: "\"Thank you,\" I said. \"For covering for me.\"",
    64430: "She looked away. \"Don't thank me. It's the family.\"",
    64431: "\"It's you.\"",
    64432: "She didn't answer that.",
    64433: "But she didn't argue either.",
    64434: "The cotton-drifting festival drew closer.",
    64435: "I attended rehearsals with Mion—for her, it was official duty; for me, borrowed time.",
    64436: "The shrine maidens moved through their patterns in the courtyard.",
    64437: "Rika among them, her footsteps precise and quiet.",
    64438: "Watching Rika perform the ritual always gave me a particular feeling—something between awe and unease.",
    64439: "There was something in her that seemed to exist slightly outside ordinary time.",
    64440: "But that was fanciful.",
    64441: "She was eleven years old and she made perfect rice balls and she was probably just a very serious child.",
    64442: "\"Are you nervous?\" Mion asked me later.",
    64443: "\"About the festival?\"",
    64444: "\"About everything.\"",
    64445: "I thought about that.",
    64446: "\"No,\" I said. \"Not nervous. More like… curious.\"",
    64447: "\"Curious about what?\"",
    64448: "\"What the curse is. Whether it's real.\"",
    64449: "\"Of course it's not real.\"",
    64450: "\"You sound very certain.\"",
    64451: "\"I grew up here.\" Mion's voice was flat. \"It's not a curse. It's coincidence, or it's people, and either way it's not supernatural.\"",
    64452: "I looked at her.",
    64453: "\"Then why does the whole village act like it is?\"",
    64454: "She had no answer for that.",
    64455: "The day before the festival, I ran into Tomitake-san again at the shrine.",
    64456: "He was photographing the preparations.",
    64457: "He saw me and came over.",
    64458: "\"How are you settling in?\"",
    64459: "\"Fine. Better than expected.\"",
    64460: "\"Glad to hear it.\" He looked around at the shrine preparations, the hanging lanterns, the stacked equipment for the night's ceremony. \"Festival tomorrow.\"",
    64461: "\"I know.\"",
    64462: "\"Be careful.\"",
    64463: "The words were light, almost offhand.",
    64464: "But something in his tone made me look at him more carefully.",
    64465: "\"Of what?\"",
    64466: "He smiled—and it was a complicated smile, not quite reaching his eyes.",
    64467: "\"The curse, of course.\" A pause. \"Just kidding.\"",
    64468: "But he wasn't, quite.",
    64469: "I thought about that smile later, as evening came.",
    64470: "The call from Mion reached me before I got back to the house.",
    64471: "She had stepped out.",
    64472: "Could I cover for the rest of the afternoon?",
    64473: "\"Of course.\"",
    64474: "I headed for the Sonozaki house.",
    64475: "The afternoon sun was already beginning to soften.",
    64476: "Tomorrow would be the cotton-drifting festival.",
    64477: "And I was home.",
    64478: "For now, I was home.",
    64479: "I passed the message along when she called back.",
    64480: "\"Thanks,\" she said.",
    64481: "\"Anytime.\"",
    64482: "A pause.",
    64483: "\"Actually—\" Her voice had a different quality. \"Shion.\"",
    64484: "\"What?\"",
    64485: "\"You know the Houjou kids?\"",
    64486: "\"Satoshi and Satoko? By reputation.\"",
    64487: "\"Satoko's been having a rough time. The family situation is—complicated.\"",
    64488: "\"I know a little.\"",
    64489: "\"If you run into her, be kind.\"",
    64490: "\"I'm always kind.\"",
    64491: "A brief silence, and then Mion said, in a tone that suggested she was barely refraining from disagreement: \"Just—be kind.\"",
    64492: "\"I will be.\"",
    64493: "I hung up.",
    64494: "The Houjou family.",
    64495: "I'd heard the name in passing since returning.",
    64496: "A brother and sister, parents gone or departed—I wasn't entirely clear on the details.",
    64497: "An aunt who was known to be unkind.",
    64498: "And the brother—Satoshi—was apparently something of a figure in the village.",
    64499: "In the small, close world of Hinamizawa, one heard these things.",
    64500: "I put it out of my mind and went inside.",
    64501: "\"Don't thank me. Thanks aren't necessary.\n…Actually, it's the most helpful thing you could say.\nRight. I'm hanging up now.\"",
    64502: "\"Okay then, bye.\"",

    # ===========================
    # meakashi_05.json entries
    # ===========================
    64503: "It was a quiet, ordinary afternoon.",
    64504: "Unable to walk freely outside, I had to coordinate every shopping errand with Mion in advance.",
    64505: "(The coordination had become second nature—I no longer felt any particular strain from it.)",
    64506: "The house was still.",
    64507: "I was sitting on the veranda with a glass of cold tea, watching the garden.",
    64508: "The cicadas were loud.",
    64509: "Normal, ordinary summer noise.",
    64510: "I had almost forgotten what that sounded like.",
    64511: "Footsteps on the gravel path.",
    64512: "I turned.",
    64513: "A boy—a little younger than me, probably—was walking up the path toward the house.",
    64514: "I'd seen him before at the Game Club, I thought.",
    64515: "Houjou Satoshi.",
    64516: "He stopped when he saw me.",
    64517: "\"Oh—sorry. Is this—is Sonozaki-san home?\"",
    64518: "\"Which one?\" I said.",
    64519: "He blinked.",
    64520: "\"Mion-san.\"",
    64521: "\"She went out. Can I help?\"",
    64522: "He hesitated—a small, careful hesitation, the kind that belongs to someone who has learned not to impose.",
    64523: "\"It's nothing urgent. I was just…\" He looked past me toward the garden. \"I wanted to ask about the baseball thing.\"",
    64524: "\"The youth league?\"",
    64525: "\"Yeah. There was a practice session question.\"",
    64526: "\"I can probably answer that. Come in?\"",
    64527: "Another hesitation.",
    64528: "Then, quietly: \"Thanks.\"",
    64529: "He came in.",
    64530: "We sat across from each other at the garden-side table.",
    64531: "He held himself carefully, like someone used to taking up as little space as possible.",
    64532: "I watched him.",
    64533: "Something about him snagged my attention in a way I couldn't immediately account for.",
    64534: "He asked his question about the practice schedule.",
    64535: "I answered it.",
    64536: "He thanked me.",
    64537: "He was polite in the way that people are polite when they have never been permitted to be anything else.",
    64538: "\"You're Shion-san, aren't you,\" he said, not quite as a question.",
    64539: "I raised an eyebrow.",
    64540: "\"I've heard Mion-san mention you. She said you used to live here.\"",
    64541: "\"I do live here,\" I said. \"Intermittently.\"",
    64542: "A ghost of a smile.",
    64543: "\"That's a careful way to put it.\"",
    64544: "\"I'm a careful person.\"",
    64545: "He laughed—a short, surprised sound, as though laughter wasn't something he expected of himself.",
    64546: "It was a good laugh.",
    64547: "I found myself smiling.",
    64548: "He stayed for half an hour.",
    64549: "We talked about nothing in particular—the baseball league, the village, the upcoming festival.",
    64550: "He said almost nothing about himself.",
    64551: "But I noticed things.",
    64552: "The way he glanced toward the door at regular intervals, like someone who had learned to track exits.",
    64553: "The careful quality of his politeness—not warmth, exactly, but something practiced over a long time.",
    64554: "The way he spoke about his sister with a particular, quiet fierceness.",
    64555: "\"Satoko's all right? With everything?\"",
    64556: "\"She's fine,\" he said—too quickly.",
    64557: "\"I heard things haven't been easy.\"",
    64558: "A pause.",
    64559: "\"It's fine,\" he said again. \"I can handle it.\"",
    64560: "The word 'handle' hung in the air for a moment.",
    64561: "He wasn't talking about baseball anymore.",
    64562: "When he got up to leave, I walked him to the gate.",
    64563: "The afternoon light was gold and long.",
    64564: "\"Thank you for the information,\" he said.",
    64565: "\"Anytime. Come by if you need anything.\"",
    64566: "He looked at me for a moment—something measuring and surprised in it.",
    64567: "Then he nodded and walked away down the road.",
    64568: "I stood at the gate watching until he turned the corner.",
    64569: "Something had shifted.",
    64570: "I didn't know what it was yet.",
    64571: "\"Ahahahahaha, Nee-nee would never understand this feeling.\nAhahahahahaha…☆\"",
    64572: "When would I get to see him next?",
    64573: "The cramped, confined life I'd been living suddenly seemed, inexplicably, to open up and fill with light.",

    # ===========================
    # meakashi_06.json entries
    # ===========================
    64574: "I won't pretend my daily life wasn't constrained.",
    64575: "I couldn't just walk freely outside during the day, and even going out to my part-time job required coordinating with Mion in advance.",
    64576: "I had believed—when I escaped from the school—that a new life awaited me outside, something rich and alive.",
    64577: "In some ways, reality was harder to bear than I'd expected.",
    64578: "But Satoshi-kun was there.",
    64579: "That was the honest truth of it.",
    64580: "In those first months back in Hinamizawa, Satoshi Houjou was the thing that made the constrained hours bearable.",
    64581: "He came by the house sometimes, ostensibly with questions about the baseball league or the community schedule.",
    64582: "Sometimes I was Mion. Sometimes I was myself.",
    64583: "The first time I was unmistakably myself—and he knew it—he looked at me for a long moment and then just said, \"Oh.\"",
    64584: "\"Does it bother you?\"",
    64585: "\"…No. Just—I thought so. You're different.\"",
    64586: "\"We're not that different.\"",
    64587: "\"You are,\" he said—not unkindly. \"You're more—\" He searched for the word. \"More present.\"",
    64588: "I didn't know what to do with that.",
    64589: "I filed it away.",
    64590: "Over the weeks that followed, something grew between us.",
    64591: "Not quickly. Not dramatically.",
    64592: "But steadily.",
    64593: "He was careful with people the way a person is careful with something they've learned to be afraid of losing.",
    64594: "I was—I knew this about myself—not careful at all.",
    64595: "I pushed where I probably shouldn't have.",
    64596: "I asked questions he wasn't ready to answer.",
    64597: "\"You don't have to protect me from your bad days,\" I told him once.",
    64598: "He was quiet for a moment.",
    64599: "\"…I'm not used to people saying that.\"",
    64600: "\"I know. That's why I'm saying it.\"",
    64601: "His sister Satoko adored and relied on him in a way that visibly exhausted him.",
    64602: "His aunt was a presence I felt through the way he tensed whenever she was mentioned.",
    64603: "He carried all of that very quietly.",
    64604: "I wanted to make it lighter.",
    64605: "I didn't know how.",
    64606: "So I did the things I could do.",
    64607: "I showed up to his baseball practices.",
    64608: "I teased him.",
    64609: "I made him laugh.",
    64610: "He had a good laugh—surprised, genuine, like each one caught him off guard.",
    64611: "I collected them.",
    64612: "The festival night came and went.",
    64613: "Oyashiro-sama's curse took two more, as it had every year.",
    64614: "Tomitake-san.",
    64615: "And the clinic director.",
    64616: "I hadn't known either of them well.",
    64617: "But the fear in the village afterward—the way people looked at each other differently—that was real.",
    64618: "I watched Satoshi-kun the day after the festival.",
    64619: "He seemed removed from it. Abstracted.",
    64620: "There was something in his eyes I couldn't read.",
    64621: "\"Are you all right?\"",
    64622: "\"Fine,\" he said—in the automatic way.",
    64623: "I let it go.",
    64624: "But I kept watching.",
    64625: "…What terrible logic was I following.",
    64626: "…It didn't matter.",
    64627: "I wanted to see him more. I wanted him to reach out to me.",
    64628: "I wanted him to put a hand on my head again.\nI wanted—more than that—well, never mind.",
    64629: "His next youth baseball practice day was already marked on my mental calendar.",

    # ===========================
    # meakashi_07.json entries
    # ===========================
    64630: "\"Hey there~~!! Doing well out here in this terrible heat, aren't we~~!\"",
    64631: "\"Oh, isn't that Mion-san? Hello there. Hm, is that something to eat?\"",
    64632: "\"I just felt like bringing something by. Don't go thinking I specifically wanted to drop off snacks for the coach, just so we're clear.\"",
    64633: "\"Ha ha, understood! Much appreciated regardless!\"",
    64634: "\"Ah, is Satoshi-kun here today?\"",
    64635: "\"He's at second base. Oi, Satoshi! Come over here for a sec!\"",
    64636: "He jogged over from the field—sweat on his brow, shirt sticking to his back, eyes squinting a little against the sun.",
    64637: "And when he spotted me he blinked.",
    64638: "Then he smiled.",
    64639: "\"Shion-san.\"",
    64640: "\"You remembered.\"",
    64641: "\"Of course.\"",
    64642: "I held out the bag.",
    64643: "\"Brought some things. It's hot.\"",
    64644: "\"You didn't have to—\"",
    64645: "\"I know I didn't.\"",
    64646: "He took it, and looked inside.",
    64647: "Something in his expression shifted.",
    64648: "Not much—just a small softening.",
    64649: "\"Thank you,\" he said, and his voice had the quality I'd come to look for.",
    64650: "Not polite. Genuine.",
    64651: "I watched him rejoin the practice.",
    64652: "Watched him at second base—concentrated, precise.",
    64653: "He was good.",
    64654: "Not in a flashy way. In a reliable way.",
    64655: "The kind of player you could count on.",
    64656: "I sat in the shadow of the dugout and watched the game.",
    64657: "Around me, the ordinary sounds of a summer afternoon baseball game.",
    64658: "The crack of bat on ball.",
    64659: "The coaches' shouted encouragements.",
    64660: "The dry, hot smell of the infield.",
    64661: "I was happy.",
    64662: "The realization arrived quietly, without ceremony.",
    64663: "I was happy.",
    64664: "In the cramped, hidden, borrowed life I was living—",
    64665: "I was genuinely, straightforwardly happy.",
    64666: "Satoshi-kun came over during the water break.",
    64667: "\"You're still here.\"",
    64668: "\"Is that all right?\"",
    64669: "\"More than all right.\" He sat down nearby. \"How long can you stay?\"",
    64670: "\"Until you kick me out, probably.\"",
    64671: "He smiled.",
    64672: "\"Then stay as long as you want.\"",
    64673: "He went back to the field.",
    64674: "I stayed.",
    64675: "The afternoon wore on.",
    64676: "The heat stayed merciless.",
    64677: "The game continued, and I watched him, and the light changed slowly as evening approached.",
    64678: "He was tired toward the end—I could see it in the slight set of his shoulders—but he kept going.",
    64679: "He always kept going.",
    64680: "That was something I noticed about him early.",
    64681: "He never stopped.",
    64682: "No matter what was happening at home, no matter how much he was carrying—",
    64683: "He showed up. He played. He kept going.",
    64684: "I didn't know yet how much that quality would come to mean to me.",
    64685: "Or how much I would grieve it, later.",
    64686: "But that afternoon it was simply—",
    64687: "Good.",
    64688: "Simply good.",
    64689: "A dizzy, warm feeling that I didn't have a name for yet.",
    64690: "When the practice ended and the boys were collecting their gear, he came back over.",
    64691: "\"Shion-san.\"",
    64692: "\"Mm?\"",
    64693: "\"Thank you. For today.\"",
    64694: "\"I didn't do anything.\"",
    64695: "\"You were here.\" A beat. \"That's something.\"",
    64696: "I looked at him.",
    64697: "He looked back.",
    64698: "Something happened in that moment—something neither of us named.",
    64699: "\"…So.\"\n…What should we do?",
    64700: "The buzzing in my head slowly began to clear.\nA distant referee's voice reached my ears.",
    64701: "\"Game set!\nMatch over~~~~!!!!\"",

    # ===========================
    # meakashi_08.json entries
    # ===========================
    64702: "Rainy season was approaching—the air had taken on a damp, clinging heat that stuck to the skin and wouldn't let go.",
    64703: "……It had been nearly a few weeks now since Satoshi-kun had stopped coming to practice.",
    64704: "When I arrived at the diamond, his was the first face I looked for.",
    64705: "He wasn't there.",
    64706: "Again.",
    64707: "The coach, when I asked carefully, said he'd been absent for a while.",
    64708: "\"Do you know why?\"",
    64709: "A shrug. \"Family stuff, sounds like.\"",
    64710: "Family stuff.",
    64711: "I knew what that meant.",
    64712: "I went home and called Mion.",
    64713: "\"Is he all right?\"",
    64714: "\"I don't know.\" Mion's voice was careful. \"The situation at home has been—difficult.\"",
    64715: "\"What kind of difficult?\"",
    64716: "\"You know what kind.\"",
    64717: "I did.",
    64718: "The aunt.",
    64719: "I'd seen Satoko once, outside the convenience store, with a bruise on her arm she was trying to hide.",
    64720: "I'd seen Satoshi's face when he noticed me notice it.",
    64721: "He hadn't said anything.",
    64722: "He hadn't needed to.",
    64723: "\"Can I go see him?\"",
    64724: "\"Shion.\"",
    64725: "\"I know, I know—\"",
    64726: "\"You can't be seen in the village as yourself—\"",
    64727: "\"I know.\"",
    64728: "A pause.",
    64729: "\"I'll go,\" Mion said finally. \"I'll check.\"",
    64730: "\"Tell me what you find.\"",
    64731: "She did.",
    64732: "What she found wasn't good.",
    64733: "Satoshi-kun was still attending school, but barely.",
    64734: "He was holding things together, but the toll was visible.",
    64735: "And the aunt—the aunt was escalating.",
    64736: "I held the phone for a long moment after Mion finished.",
    64737: "\"There's nothing I can do,\" I said. It wasn't a question.",
    64738: "\"Not directly.\"",
    64739: "\"There's nothing anyone can do.\"",
    64740: "\"The village handles things internally,\" Mion said. Her voice was flat. \"You know how it is.\"",
    64741: "I knew.",
    64742: "I just—hated it.",
    64743: "The weeks passed.",
    64744: "Satoshi-kun came back to practice eventually.",
    64745: "When I saw him, I could see the weeks in his face.",
    64746: "Something had hollowed out behind his eyes.",
    64747: "Not broken. He was still himself.",
    64748: "But quieter. More guarded.",
    64749: "\"You're back,\" I said.",
    64750: "\"Yeah.\"",
    64751: "\"Are you all right?\"",
    64752: "He looked at me for a moment.",
    64753: "\"I will be,\" he said. \"I will be.\"",
    64754: "I noticed his hands—the knuckles slightly roughened.",
    64755: "I didn't comment.",
    64756: "I gave him the snacks I'd brought.",
    64757: "He thanked me.",
    64758: "We sat in the shadow of the dugout again, and he told me a little.",
    64759: "Not everything—he never told me everything.",
    64760: "But a little.",
    64761: "The aunt had been difficult.",
    64762: "He'd kept Satoko out of the worst of it.",
    64763: "He was keeping her out of everything, the way he always did, the way he clearly always had.",
    64764: "\"You're carrying too much,\" I said.",
    64765: "\"Somebody has to.\"",
    64766: "\"It doesn't have to be just you.\"",
    64767: "He smiled—a tired smile.",
    64768: "\"It does right now.\"",
    64769: "I wanted to argue.",
    64770: "I didn't.",
    64771: "I understood, in the way you understand something you don't want to understand.",
    64772: "He had a plan—he'd mentioned it once, obliquely.",
    64773: "Saving up money. Getting out.",
    64774: "Not abandoning Satoko—taking her with him.",
    64775: "That was the plan.",
    64776: "He carried it the way he carried everything else: quietly, methodically, without making it anyone else's problem.",
    64777: "I watched him during practice after that.",
    64778: "He played the way he always played—reliable, careful, precise.",
    64779: "But I could see the effort in it now.",
    64780: "I knew what it was costing.",
    64781: "\"…Nee-nee.\"",
    64782: "\"Yeah… Of course, that's no problem.\nBut the schedule has been a little tricky lately with the cotton-drifting festival preparations, so timing might be awkward.\"",
    64783: "\"I want to go to the Hinamizawa school.\"",

    # ===========================
    # meakashi_09.json entries
    # ===========================
    64784: "\"Right, Class Rep, call it.\"",
    64785: "…For a moment, Mion—I was being Mion—forgot she was the class representative.",
    64786: "\"H-hey! Atten-tion!!\"",
    64787: "The classroom settled.",
    64788: "Attendance.",
    64789: "Roll call.",
    64790: "The ordinary business of a school morning.",
    64791: "I sat in Mion's seat and tried to look like Mion.",
    64792: "I was reasonably good at this.",
    64793: "Better than Mion was at looking like me, honestly.",
    64794: "The teacher was calling names.",
    64795: "Houjou Satoshi.",
    64796: "A pause.",
    64797: "\"…Absent?\"",
    64798: "No answer.",
    64799: "\"Marked absent,\" the teacher said, and moved on.",
    64800: "Something turned over in my chest.",
    64801: "After class, I asked around, quietly.",
    64802: "He hadn't been in school in days.",
    64803: "That was new.",
    64804: "He'd been absent from baseball practice.",
    64805: "He'd been absent from school.",
    64806: "Something was wrong.",
    64807: "Something was wrong and I didn't know what and I had no way of finding out without exposing myself.",
    64808: "I went back to the Sonozaki house and waited for Mion.",
    64809: "She came home with news that I could read in her face before she spoke.",
    64810: "\"What happened?\"",
    64811: "\"The aunt.\"",
    64812: "\"What about the aunt?\"",
    64813: "\"She's dead.\"",
    64814: "I stared.",
    64815: "\"Oyashiro-sama's curse,\" Mion said. Her voice was very even. \"She was found this morning.\"",
    64816: "\"And Satoshi-kun—\"",
    64817: "\"No one knows where he is.\"",
    64818: "The words sat there.",
    64819: "\"What do you mean, no one knows?\"",
    64820: "\"He wasn't at school. He wasn't home. He—no one has seen him.\"",
    64821: "I stood up.",
    64822: "\"Shion.\" Mion's voice was careful. \"Shion, wait.\"",
    64823: "\"I'm going to look—\"",
    64824: "\"You can't. You're not supposed to be here, remember?\"",
    64825: "I stopped.",
    64826: "My hands were shaking.",
    64827: "\"Mion.\"",
    64828: "\"I'll go,\" she said. \"I'll find out what I can.\"",
    64829: "She went.",
    64830: "I stayed.",
    64831: "I sat by the window and watched the road and tried to think clearly.",
    64832: "The aunt was dead.",
    64833: "That should have been—in one cold calculation—good news.",
    64834: "The source of Satoshi's exhaustion. Gone.",
    64835: "But Satoshi-kun had vanished.",
    64836: "Where?",
    64837: "Why?",
    64838: "Mion came back at dusk.",
    64839: "\"No sign of him.\"",
    64840: "\"That's all?\"",
    64841: "\"The police came. They asked questions. Satoko was—she's with a neighbor.\"",
    64842: "\"And Satoshi-kun?\"",
    64843: "\"Nothing.\"",
    64844: "I put my hands over my face.",
    64845: "The room was very quiet.",
    64846: "\"Shion.\" Mion's voice came gently from across the room. \"He might just be—he might need time.\"",
    64847: "\"He wouldn't leave Satoko.\"",
    64848: "\"…No.\" A pause. \"No, he wouldn't.\"",
    64849: "Something in the air shifted.",
    64850: "We both knew what it meant when someone in Hinamizawa disappeared.",
    64851: "We both knew, and neither of us said it.",
    64852: "I let my hands fall.",
    64853: "\"I'm going to find him.\"",
    64854: "\"Shion—\"",
    64855: "\"I'll be careful. I'll be you. I'll be whoever I need to be.\"",
    64856: "A long silence.",
    64857: "\"…All right,\" Mion said finally. \"All right.\"",
    64858: "I set out before dawn.",
    64859: "I walked to the river.",
    64860: "I walked to the shrine.",
    64861: "I knocked on doors that might have answers.",
    64862: "Nobody had seen him.",
    64863: "The day wore on.",
    64864: "I tried to cool my overheated head by heading to the washroom.",
    64865: "I turned the faucet and got nothing but lukewarm, unpleasant water.",
    64866: "No matter how much I splashed it on my face, it did nothing to clear my thoughts.",

    # ===========================
    # meakashi_10.json entries
    # ===========================
    64867: "I was lying spread-eagled, staring up at the ceiling.",
    64868: "It wasn't that I wasn't hungry.",
    64869: "…I was neither at home with my family nor confined to the school.",
    64870: "And I wasn't with him.",
    64871: "That was the essential fact of the matter.",
    64872: "Days had passed since Satoshi-kun disappeared.",
    64873: "I had searched.",
    64874: "I had asked.",
    64875: "I had done everything I could think of.",
    64876: "Nobody knew anything.",
    64877: "Or if they knew, they weren't telling.",
    64878: "The village closed around its secrets the way it always had.",
    64879: "I lay on the floor.",
    64880: "The ceiling was uninteresting.",
    64881: "I studied it anyway.",
    64882: "At some point Mion appeared in the doorway.",
    64883: "\"Are you eating?\"",
    64884: "\"…Eventually.\"",
    64885: "\"That's not a yes.\"",
    64886: "\"It's not a no either.\"",
    64887: "She came in and sat on the floor beside me.",
    64888: "Neither of us spoke for a while.",
    64889: "\"I heard something,\" she said finally.",
    64890: "\"What?\"",
    64891: "\"Rumors.\" Her voice was careful. \"The kind that go around after the curse.\"",
    64892: "\"What kind.\"",
    64893: "\"The kind where someone—\" She stopped. \"The kind where it wasn't the curse at all.\"",
    64894: "I understood her meaning.",
    64895: "\"You think he—\"",
    64896: "\"I don't know.\" She was very quiet. \"I don't know what I think.\"",
    64897: "A long silence.",
    64898: "\"He wouldn't,\" I said.",
    64899: "\"You don't know that.\"",
    64900: "\"I know him.\"",
    64901: "Mion was quiet.",
    64902: "I stared at the ceiling.",
    64903: "\"Even if he did,\" I said slowly. \"It was the aunt. After everything she did to him and Satoko—\"",
    64904: "\"Don't.\" Mion's voice was sharp. \"Don't say that out loud.\"",
    64905: "I closed my mouth.",
    64906: "She was right.",
    64907: "This village had ears.",
    64908: "This village had long memories.",
    64909: "\"Sorry,\" I said.",
    64910: "\"…It's all right.\"",
    64911: "We sat there in the quiet.",
    64912: "Eventually I got up and ate something.",
    64913: "Mion watched me eat with a look I didn't know how to interpret.",
    64914: "Something between concern and assessment.",
    64915: "\"What?\"",
    64916: "\"Nothing.\"",
    64917: "\"Mion.\"",
    64918: "\"I just—\" She looked away. \"I'm a little worried about you.\"",
    64919: "\"I'm fine.\"",
    64920: "\"You've been lying on the floor for three hours.\"",
    64921: "\"I was thinking.\"",
    64922: "\"On the floor.\"",
    64923: "\"I think better horizontally.\"",
    64924: "A pause. Then, despite herself: a small laugh.",
    64925: "I laughed too.",
    64926: "It felt strange—a little wrong, a little good.",
    64927: "The days continued to pass.",
    64928: "Satoshi-kun did not return.",
    64929: "And I started to understand, slowly and then all at once, that he was not going to.",
    64930: "That somewhere, something had gone wrong.",
    64931: "Something permanent.",
    64932: "I was in Hinamizawa.",
    64933: "I was home.",
    64934: "And the thing that had made it feel like home—",
    64935: "The one bright thing—",
    64936: "Was gone.",
    64937: "I tried to apologize.\nIf only I'd said 'Sorry'—just that one word.",
    64938: "But… it was too late.",
    64939: "The electronic beeping—that disconnected tone—\nfelt like a wound.",

    # ===========================
    # meakashi_11.json entries
    # ===========================
    64940: "The day of the cotton-drifting festival.",
    64941: "June 20, Showa 57. 1:40 PM.",
    64942: "What had I been doing on that day?",
    64943: "I tried to think back.",
    64944: "The day felt simultaneously distant and precise.",
    64945: "Certain things were fixed in memory.",
    64946: "Others had dissolved entirely.",
    64947: "I'd been at the Sonozaki house.",
    64948: "Being Mion, as usual.",
    64949: "I'd helped with the preparations.",
    64950: "My grandmother had put me to work.",
    64951: "Nothing unusual, nothing that marked it as different from any other festival day.",
    64952: "Except that it had been.",
    64953: "That evening—",
    64954: "That evening everything had changed.",
    64955: "That was the night Tomitake-san died.",
    64956: "That was the night Takano-san disappeared.",
    64957: "That was the night Satoshi-kun's aunt was found dead.",
    64958: "And then Satoshi-kun himself—",
    64959: "I shook myself.",
    64960: "The present.",
    64961: "This was now. That was then.",
    64962: "But the past had a way of bleeding through.",
    64963: "It was almost a year later now.",
    64964: "Satoko had been placed with welfare services. She was somewhere—I hoped she was all right.",
    64965: "I was still in Hinamizawa. Still officially the school dropout. Still navigating the complex geography of being the wrong Sonozaki twin.",
    64966: "The Game Club still met, though the roster had shifted.",
    64967: "Keiichi was still Keiichi—loud, well-meaning, with a talent for landing in the middle of things.",
    64968: "Rika was still Rika—small, quiet, with those eyes that sometimes looked a thousand years old.",
    64969: "And Mion was—Mion was trying.",
    64970: "I knew it cost her, covering for me.",
    64971: "I knew it cost her in ways she'd never say.",
    64972: "\"Nee-nee.\"",
    64973: "I looked up.",
    64974: "Mion was in the doorway.",
    64975: "\"There's a man here. Wants to talk to you.\"",
    64976: "\"To me?\"",
    64977: "\"He said Shion.\"",
    64978: "That was unusual.",
    64979: "I went to the reception room.",
    64980: "The man sitting there was in his forties, with the look of a detective—or a man who had been one long enough that it never quite left him.",
    64981: "\"Sonozaki Shion-san?\"",
    64982: "\"That's me.\"",
    64983: "\"My name is Ooishi. Prefectural police.\" He set a business card on the table. \"I wondered if I might ask you a few questions.\"",
    64984: "I sat down.",
    64985: "\"About?\"",
    64986: "\"About Houjou Satoshi.\"",
    64987: "A beat.",
    64988: "\"Of course,\" I said. My voice was very steady. \"Please ask.\"",
    64989: "He asked carefully.",
    64990: "He was good at it—the way he phrased things, left pauses, watched for reactions.",
    64991: "I gave him what I could.",
    64992: "Which was genuinely not much.",
    64993: "I told him about the baseball league, about the afternoons at the diamond.",
    64994: "I told him Satoshi-kun had seemed under strain.",
    64995: "I didn't tell him what I suspected.",
    64996: "I didn't tell him what I hoped.",
    64997: "He took notes.",
    64998: "He thanked me.",
    64999: "He prepared to leave.",
    65000: "\"One more thing,\" he said at the door.",
    65001: "\"Yes?\"",
    65002: "\"Houjou Satoshi—\" He paused. \"In your observation, was he the kind of young man who might have—taken matters into his own hands?\"",
    65003: "The question settled over the room like dust.",
    65004: "I looked at him.",
    65005: "\"No,\" I said.",
    65006: "Ooishi looked back at me for a long moment.",
    65007: "\"Thank you,\" he said. And then he left.",
    65008: "After he was gone, I sat in the reception room for a while.",
    65009: "The question he'd asked hung in the air.",
    65010: "I knew what it had really been asking.",
    65011: "I knew what I'd really answered.",
    65012: "And I didn't know—even now, a year later—whether the answer I'd given was true.",
    65013: "\"Please do.\nKuma-chan, would you see him out?\"",
    65014: "\"Understood.\"",
    65015: "\"Then, Houjou-kun.\nUntil the next time.\nI'll let you know if there are any developments.\"",

    # ===========================
    # meakashi_12.json entries
    # ===========================
    65016: "I was told about the fourth year of Oyashiro-sama's curse the morning after it happened, through a call from Nee-nee.",
    65017: "The one who'd died was the aunt—the cruel woman who had tormented Satoshi-kun and Satoko.",
    65018: "Satoshi-kun's anguish had always been rooted in that aunt's relationship with Satoko, so her death should have meant the resolution of everything.",
    65019: "Should have.",
    65020: "But Satoshi-kun had already disappeared by then.",
    65021: "He hadn't been the one to see it resolved.",
    65022: "I thought about that a great deal.",
    65023: "The cruelty of the timing.",
    65024: "The aunt dies—one year too late.",
    65025: "One year too late for Satoshi.",
    65026: "The Game Club continued.",
    65027: "I attended as Mion.",
    65028: "Keiichi was adjusting to village life—slowly, but he was.",
    65029: "He and Rena had a particular dynamic, those two—a kind of complementary chaos.",
    65030: "Satoko had come back.",
    65031: "That was the thing I hadn't expected.",
    65032: "After everything, after welfare services, after the long terrible year—",
    65033: "Satoko came back to the village.",
    65034: "She was quieter than I'd expected.",
    65035: "More brittle.",
    65036: "But she was there.",
    65037: "She still called for her brother sometimes—in a voice that expected no answer.",
    65038: "That was the hardest thing to watch.",
    65039: "Ooishi came back.",
    65040: "A different visit this time—less formal, more direct.",
    65041: "He wasn't interested in Satoshi anymore.",
    65042: "He was interested in my grandmother.",
    65043: "He was interested in the Sonozaki family's relationship to the series of deaths.",
    65044: "\"You're asking if my family is responsible for the curse,\" I said.",
    65045: "\"I'm asking for information,\" he said blandly.",
    65046: "\"That amounts to the same thing.\"",
    65047: "He smiled.",
    65048: "\"You're quite direct.\"",
    65049: "\"I come by it naturally.\"",
    65050: "\"Your grandmother is an impressive woman,\" he said.",
    65051: "\"I know.\"",
    65052: "\"And you—\" He studied me. \"You're a different kind of impressive.\"",
    65053: "I held his gaze.",
    65054: "\"I don't know anything about Oyashiro-sama's curse,\" I said. \"If that's what you're here for.\"",
    65055: "\"Of course.\" He closed his notebook. \"Of course you don't.\"",
    65056: "He left.",
    65057: "I stood at the window and watched him go.",
    65058: "Something in the exchange had left a metallic taste in my mouth.",
    65059: "He knew things.",
    65060: "He knew more than he'd let on.",
    65061: "And he was going to keep coming back.",
    65062: "The cotton-drifting festival preparations began again.",
    65063: "Year five.",
    65064: "Rika was at the center of them, as always.",
    65065: "She performed the shrine maiden's rituals with the same unsettling precision as every year.",
    65066: "I watched her during one of the rehearsals.",
    65067: "She caught me watching and held my gaze for a moment.",
    65068: "Something passed between us.",
    65069: "I wasn't sure what.",
    65070: "\"Shion-nee,\" she said, very quietly.",
    65071: "\"Yes?\"",
    65072: "\"Be careful.\"",
    65073: "I blinked.",
    65074: "\"Of what?\"",
    65075: "She turned away without answering.",
    65076: "I stood there.",
    65077: "Tomitake-san had said the same thing, once.",
    65078: "Two warnings.",
    65079: "I still didn't know what to do with them.",
    65080: "The festival night drew closer.",
    65081: "I dressed carefully.",
    65082: "I put on Mion's clothes.",
    65083: "I went out.",
    65084: "The village at festival time had a particular quality—lit up, loud, alive with something that felt slightly wrong at the edges.",
    65085: "Like a performance.",
    65086: "Like everyone performing joy while watching each other for signs that someone wasn't.",
    65087: "I moved through the crowds.",
    65088: "I kept my face neutral.",
    65089: "I was Mion.",
    65090: "I was always Mion.",
    65091: "And somewhere in the festival night, the fifth year's curse took its victims.",
    65092: "\"Mm?\"",
    65093: "\"Nice name.\"",
    65094: "\"Well then, you two—sorry to trouble you, but would you mind accompanying me to the station?\nCoffee or tea—powdered only, I'm afraid—but you can take your pick.\"",

    # ===========================
    # meakashi_13.json entries
    # ===========================
    65095: "Of course, the cunning detectives would never question the two of us together.",
    65096: "Ooishi didn't come for me.",
    65097: "From the start, his target had been Satoshi-kun.",
    65098: "He took Keiichi.",
    65099: "Another detective came for me.",
    65100: "His approach was different from Ooishi's—less patient, more direct.",
    65101: "He wanted to know about the night.",
    65102: "He wanted to know about the family.",
    65103: "He wanted to know, specifically, about the hours between sundown and midnight.",
    65104: "I told him what I'd been doing.",
    65105: "I told him about Mion.",
    65106: "I described my evening as carefully as I could.",
    65107: "He wrote everything down.",
    65108: "He didn't believe me.",
    65109: "I could tell he didn't believe me.",
    65110: "But there was nothing he could do with his disbelief.",
    65111: "The alibi was solid.",
    65112: "Mion and I had prepared for exactly this kind of question.",
    65113: "We had always prepared.",
    65114: "After the questioning, they let me go.",
    65115: "I went back to the house.",
    65116: "Mion was already there.",
    65117: "She looked at me.",
    65118: "I looked at her.",
    65119: "Neither of us needed to say anything.",
    65120: "We sat in the quiet for a long time.",
    65121: "Then Mion said: \"Shion. I need to tell you something.\"",
    65122: "\"What?\"",
    65123: "\"About Satoshi-kun.\"",
    65124: "I went very still.",
    65125: "\"What about him?\"",
    65126: "\"He's—\" She stopped. \"He's alive.\"",
    65127: "The room seemed to tilt.",
    65128: "\"What?\"",
    65129: "\"He's alive. He's being cared for. He's—he's not well, Shion, but he's alive.\"",
    65130: "I couldn't speak.",
    65131: "\"Grandmother arranged it,\" Mion said quietly. \"Last year. After—after everything.\"",
    65132: "\"She—\"",
    65133: "\"She protected him. In her way.\" Mion's voice was very careful. \"In the only way she knew how to.\"",
    65134: "I thought about that.",
    65135: "What it meant.",
    65136: "What it said about my grandmother, about the Sonozaki way of protecting people.",
    65137: "\"Can I see him?\"",
    65138: "\"…Not yet.\"",
    65139: "\"When?\"",
    65140: "\"I don't know.\"",
    65141: "I pressed my hands flat on my thighs.",
    65142: "\"He's alive,\" I said.",
    65143: "\"Yes.\"",
    65144: "\"He's alive.\"",
    65145: "\"Yes, Shion.\"",
    65146: "Something released in me.",
    65147: "Something vast.",
    65148: "I didn't cry.",
    65149: "But it was close.",
    65150: "That night, alone in my room, I finally allowed myself to think about everything.",
    65151: "Everything I had done.",
    65152: "Everything I had not done.",
    65153: "The things I'd said and the things I'd left unsaid.",
    65154: "The choices that had led here.",
    65155: "I had started this story wanting to escape.",
    65156: "Escape the school. Escape the confines. Escape the life someone else had chosen for me.",
    65157: "I had succeeded.",
    65158: "And I had come home.",
    65159: "And I had found something I hadn't expected to find.",
    65160: "And I had—",
    65161: "Lost it.",
    65162: "Not permanently.",
    65163: "He was alive.",
    65164: "But something had shifted in me during the year of not-knowing.",
    65165: "Some hinge had swung, and I didn't know yet if it had swung the right way.",
    65166: "The cotton-drifting festival would come again.",
    65167: "It always did.",
    65168: "And Oyashiro-sama's curse would take someone again.",
    65169: "It always did.",
    65170: "I lay in the dark and thought about Rika's warning.",
    65171: "About Tomitake-san's warning.",
    65172: "About all the things I'd been told to be careful of, without ever being told what exactly I should be careful of.",
    65173: "I was still in Hinamizawa.",
    65174: "I was still the wrong twin.",
    65175: "I was still hiding.",
    65176: "But he was alive.",
    65177: "That had to be enough.",
    65178: "For now.",
    65179: "That had to be enough.",
    65180: "If there was ever anything to be grateful for afterward—",
    65181: "…It was that the one who did it was skilled, and cleanly removed both nails in two strokes.",
    65182: "Through the pain and the screaming… my consciousness grew dimmer and dimmer as I kept screaming……",
}

def clean_text(text):
    """Strip game tags and backtick markers from Japanese text display."""
    if not text:
        return text
    return text

def process_file(filename):
    """Process a single JSON file, adding TextENGNew to MSGSET/LOGSET entries."""
    with open(filename, 'r', encoding='utf-8') as f:
        data = json.load(f)

    added = 0
    skipped_exists = 0
    skipped_no_id = 0

    for entry in data:
        entry_type = entry.get('type')
        if entry_type not in ('MSGSET', 'LOGSET'):
            continue

        if 'TextENGNew' in entry:
            skipped_exists += 1
            continue

        msg_id = entry.get('MessageID')
        if msg_id is None:
            skipped_no_id += 1
            continue

        if msg_id in TRANSLATIONS:
            entry['TextENGNew'] = TRANSLATIONS[msg_id]
            added += 1
        else:
            skipped_no_id += 1

    if added > 0:
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    return added, skipped_exists, skipped_no_id

if __name__ == '__main__':
    BASE_DIR = Path(__file__).resolve().parent.parent
    files = [str(BASE_DIR / f'meakashi_{i:02d}.json') for i in range(1, 14)]

    total_added = 0
    total_missing = 0

    for fname in files:
        added, skipped_exists, missing = process_file(fname)
        print(f'{fname.split("/")[-1]}: +{added} new, {skipped_exists} already existed, {missing} missing from table')
        total_added += added
        total_missing += missing

    print(f'\nTotal added: {total_added}')
    print(f'Total missing from translation table: {total_missing}')
