#!/usr/bin/env python3
"""Translations for miotsukushi_omote_02.json"""

translations_02 = {
121996: "When lunchtime arrived, the classroom erupted at once into cheerful noise. Everyone spread out their lunchboxes and picked at each other's side dishes in their little clusters of friends.",
121997: "Naturally, we club members were no exception.",
121998: "\"Yes! Lunch, lunch! Alright, Rena—push the desks together!\"",
121999: "I swept my textbook and notebook away and spun my desk around. Rena, who had clearly been waiting for exactly this, snapped her desk right up against mine and pulled out a noticeably large lunchbox from her bag.",
122000: "\"Woah, that's a big lunchbox today, Rena!\"",
122001: "There was no way a single person could eat all of that. Not that any of us had expected her to—so we crowded noisily around the lunchbox.",
122002: "\"Ahahahaha! Today I made it big because I wanted everyone to share! Today's lunch is Rena's special meatballs!\"",
122003: "Saying that, Rena lifted the lid with a bright, beaming smile.",
122004: "\"Oh... OHHH!!\"",
122005: "What color, what gloss, what aroma! A mountain of meatballs arranged beautifully without a single one out of place, the vegetables around them a perfect complement—it was practically blinding!!",
122006: "\"What do you think? I did the prep work last night and they came out super cute! I got a little carried away and made too many.\"",
122007: "A little... that's hardly the word for it. \"Heaping\" would be more accurate.",
122008: "But! Against a hunger this fierce and demonic, this quantity is nothing! With my ravenous heart, I could demolish it in seconds!",
122009: "\"Leave it to me, Rena! I'll eat every last one of these masterpieces myself!\"",
122010: "\"N-not all of them~? I made them for everyone...\"",
122011: "\"Right, right, hoarding is bad, Kei-chan? Club rule number nine: 'Even under competitive principles, opportunity is equal!' \"",
122012: "\"Hey, I've always wondered—how many of those club rules are there exactly? Recite them all for me sometime.\"",
122013: "\"Ahahahaha!!\"",
122014: "Mion just laughed it off. ...She probably made them up on the spot and forgot most of them. Some of them probably overlap, too. Almost certainly.",
122015: "\"Mii-chan, try one too? I'm really proud of these today!\"",
122016: "\"Oh~ now that's something. If you put it that way, this old-timer would love to have one. Here, Satoko—desks, desks!\"",
122017: "\"Oho-ho-ho! How unfortunate for you, meatballs happen to be one of my favorite things! Prepare yourself, Keiichi-san—not a single one shall pass your lips!!\"",
122018: "\"What on earth are you babbling about?!\"",
122019: "Trading insults, I watched Satoko out of the corner of my eye—she hadn't even gotten her chopsticks out yet—and moved first to pluck up a meatball coated in glossy sauce.",
122020: "\"Ha, Satoko! First strike is mine—!!\"",
122021: "\"Ah! Chie-sensei is walking around without any clothes on!\"",
122022: "\"What?!\"",
122023: "\"—Nom.\"",
122024: "By the time I thought 'wait—'",
122025: "The meatball that had been on the end of my chopsticks had been stolen clean away by Satoko.",
122026: "Sh-she got me?!",
122027: "Satoko, you little—she found the one opening in my guard and struck!!",
122028: "\"Oho-ho-ho! Mind the gap, as they say! The very first meatball has a flavor that simply cannot be beaten!!\"",
122029: "\"Y-you little brat, Satoko!! Liars are thieves in the making, you know?!\"",
122030: "\"...I mean, I think the bigger idiot here is the guy who actually fell for that, Kei-chan.\"",
122031: "\"Ugh...?!\"",
122032: "\"Keiichi-kun... you're such a boy... hau.\"",
122033: "\"I-it can't be helped, alright?! A pure boy's heart that can't help chasing even the slightest 'what if' and 'maybe'—can't you at least try to understand that?!\"",
122034: "\"Ah, yes, yes. A pure and indecent boy's heart. Got it, got it.\"",
122035: "\"...Gross.\"",
122036: "H-hey, hold on!!",
122037: "Don't look at me with those dead eyes!!!",
122038: "\"Oho-ho-ho! Now, while Keiichi-san is taking damage, I shall help myself to yet another meatball!\"",
122039: "\"What?!\"",
122040: "\"Then, allow me to—\"",
122041: "\"Well, tough luck. That's not happening, Satoko.\"",
122042: "\"Guh?!\"",
122043: "A hand shot out and grabbed Satoko by the collar just as she was lunging toward the pile of meatballs. Satoko spun around in surprise—and found Shion standing there with a grin on her face.",
122044: "\"Sh-Shion-san?! A-are you here again today?!\"",
122045: "\"I told you. I said I'd look after you for a while, to keep your diet in order. ...Here.\"",
122046: "With that, Shion held up a furoshiki-wrapped jūbako she was carrying. The moment Satoko saw it, her face twisted and she backed away toward the wall in a very precise and practiced-looking maneuver.",
122047: "\"Eeeek?! Wh-what's inside that... don't tell me...?!\"",
122048: "\"It's quite clear that your vegetable intake has been lacking recently, Satoko. So I've specially prepared a kabocha bento.\"",
122049: "\"Ngah?!\"",
122050: "\"Shion, that's basically torture...\"",
122051: "As I said it, though, Shion—who had just delivered divine retribution on my behalf—looked, for the very first time in my life, like an agent of justice.",
122052: "So God really did exist. Namu-amida-butsu, namu-amida-butsu, hidebu.",
122053: "\"Come on, Satoko! Your lunch is over here~!\"",
122054: "Meanwhile, Satoko shook her head back and forth with a pale, Munch's Scream face and teary eyes.",
122055: "\"Nooo~ I hate kabocha—!! Waaaa!!\"",
122056: "\"Now, now, that attitude about kabocha won't do! Kabocha has excellent nutritional value, you know. A growing girl like Satoko needs to pay special attention to nutrition!\"",
122057: "\"As long as I'm around, I won't allow picky eating. Please keep that in mind.\"",
122058: "\"Hm~... Shion is actually making sense for once.\"",
122059: "\"That's rude of you, Nee-san. Here, everyone else come help yourselves too. Steaming kabocha is sweet and delicious, you know~?\"",
122060: "We accepted the jūbako that Shion offered, opened the lid, and each popped one in our mouths.",
122061: "...Oh? This is actually...",
122062: "\"...Oh, you're right. It's soaked in nice broth!\"",
122063: "\"Yes, so sweet and yummy!\"",
122064: "Mion and Rena both made sounds of appreciation. Never underestimate simmered kabocha—without just the right amount of broth soaked in, you could never achieve this texture and flavor.",
122065: "Well done, Shion...! The first time she brought that kabocha salad, it was basically raw, crunchy vegetable, and even I felt pity for anyone who had to eat it—but she's come this far!",
122066: "\"Now that's something. The sweetness of the kabocha is subtle and yet just perfect! Satoko, you can go without—it'd be wasted on you!!\"",
122067: "\"Wh-what do you meeeeann!! I don't like kabocha, but I'm not going to stand for being spoken to like that!!\"",
122068: "\"Go on, go on! Just open wide and take a big bite!\"",
122069: "It was obviously a transparent provocation, but Satoko Houjou was not a person who could back down once cornered. She puffed her brow into a deep scowl, steeled herself, and bit down.",
122070: "\"Mmph, mmph...?\"",
122071: "\"See? Pretty good, isn't it?\"",
122072: "\"...Nnnn, well... it's not... inedible...\"",
122073: "Tilting her head with a slightly surprised expression, Satoko wavered with her chopsticks in midair, weighing whether to go for another one.",
122074: "Watching that, Shion broke into a huge grin and gave a triumphant fist pump—but when her eyes happened to meet mine, she cleared her throat with a small sheepish air and settled back into her usual sardonic smile.",
122075: "\"So? A bit of a change of heart?\"",
122076: "\"...W-well, if it's about this good, I suppose just a little...\"",
122077: "\"Well, the first one was pretty intense. To have come this far in such a short time is impressive!\"",
122078: "\"Of course. I research night and day on how to help Satoko get over her kabocha phobia. Now, at this pace, we'll work our way through eggplant, green pepper, and asparagus by the end of the year.\"",
122079: "\"Gblah?!\"",
122080: "Satoko choked and coughed violently. Shion smiled her gracious demon smile and offered her a cup of tea, making a great show of it.",
122081: "\"Easy, easy. There's still a mountain of kabocha left, so no need to rush.\"",
122082: "\"No, no, no—that is not funny at all!! What have I done to deserve a penance during my precious lunch break—?!\"",
122083: "\"It's not a penance, you know? The supervisor used to say: 'If you're feeling like it's hard, just imagine you're a maid undergoing strict training. Everything will start to feel perfectly happy.' \"",
122084: "\"So Satoko—just imagine you're a maid, and everything's solved!\"",
122085: "The supervisor... what kind of logic is that...? ...Is she starting a maid religion or something?",
122086: "I got to know her through that baseball situation and genuinely think she's a good person, but... I'm getting increasingly worried about whether youth education is safe in her hands.",
122087: "\"H-hauuu~! Maid Satoko-chan, I wanna take you home~☆\"",
122088: "And then there's this one...",
122089: "\"So, Satoko! With the mindset of a maid, let's challenge everything!\"",
122090: "\"Wh-what on earth is that! I have never seen, heard, or tasted such peculiar and preposterous logic in my life!!\"",
122091: "\"Don't think. Feel.\"",
122092: "\"Shion... when exactly did you attain enlightenment?\"",
122093: "\"Ah, about a year ago...\"",
122094: "A slick comeback—but come on, there's no such convenient shortcut to enlightenment in this world. Did something snap in her head?",
122095: "\"A-and besides! Why is Shion-san from another school here during class hours in the first place?! Before you go managing other people, manage yourself!\"",
122096: "Finding herself backed into a corner, Satoko had pulled out the most reasonable argument she had.",
122097: "But of course—this was the one logic least effective on Shion, who had always operated outside normal rules, and in response Satoko merely got a derisive snort and let out a frightened 'eep!'",
122098: "\"B-but Shii-chan, this has been going on for a whole week now. I'd think Okinomiya school would have started saying something by now... are you okay?\"",
122099: "\"Oh, that's fine. They've agreed to adjust my attendance record accordingly.\"",
122100: "\"Adj-adjust... are you seriously—?!\"",
122101: "\"Heh heh heh... with the Sonozaki name and power behind you, one little school is nothing.\"",
122102: "\"Extraterritorial measures...?!\"",
122103: "Shion dropped that terrifying statement with a perfectly nonchalant face.",
122104: "W-well, with the Sonozaki influence, it would be easy to do anything...",
122105: "No—it's Shion we're talking about. She's definitely got dirt on not just the homeroom teacher but the principal too!",
122106: "She really is... terrifying as an enemy...",
122107: "\"So anyway, worry not about Satoko. Don't give it a second thought.\"",
122108: "\"Then—then I'll transfer to Okinomiya school myself!!\"",
122109: "\"Oh, that would be even more convenient, actually. You're welcome to use my driver to commute.\"",
122110: "\"Hau?!\"",
122111: "\"Shall we commute together... to my school? ...'Together,' ♪\"",
122112: "\"N-no thank you, nabe-chanko—I am absolutely not having that~~~!!\"",
122113: "\"...Oh, come on! You never make any progress, do you!\"",
122114: "Every last argument shot down, Satoko fled in half-tears. Shion sprang ahead to cut off the exit and backed the flailing Satoko inch by inch into the corner of the classroom.",
122115: "\"Ahahaha! It's lively as ever today! It is!\"",
122116: "Yes—a scene that had become familiar lately.",
122117: "By now there was even an unofficial pool running among the students—trading cards featuring baseball players and anime characters—betting on how many minutes it would take for Satoko to get caught.",
122118: "The teacher's podium was occupied by Mion, who had promptly chalked an odds table on the board and was herding a crowd of underclassmen with the air of a genuine professional bookie.",
122119: "\"Step right up—three to one if she's caught within three minutes! Five to one for ten minutes! And if she actually escapes, an unbelievable five hundred to one! Last call for card submissions~!\"",
122120: "Even here, you're running this, Mion...",
122121: "While I was saying that, Satoko had already been backed against the lockers with no way to go left, right, or back—checkmate imminent.",
122122: "Shion was someone even Mion couldn't match. No matter how sharp Satoko was, she had no hope of coming anywhere near her—let alone touching her shadow.",
122123: "\"A-auauauau~!\"",
122124: "\"Give it up, Satoko... you've met your match. Shion, let her off soon.\"",
122125: "\"No can do. Satoshi-kun asked me to look after her, so health management is my job. No picky eating—and that's final!\"",
122126: "...That level of dedication is genuinely admirable, but did Satoshi really ask for all that? For a moment I could vaguely picture the face of Satoko's brother—someone I'd never met—shaking his head vigorously in denial.",
122127: "\"But lately Shii-chan really is like a big sister to Satoko-chan!\"",
122128: "\"Ahh~, if you want, I'll trade you. I've got no use for mine—toss.\"",
122129: "\"Ahahaha! But the 'ends justify the means' part is definitely something only Mii-chan's sibling could say!\"",
122130: "Rena, is that meant as a compliment...? Even Mion is making a supremely sour face.",
122131: "\"...What's wrong, Mii-chan? Did I say something weird? Did I?\"",
122132: "\"There's no point getting mad at someone who doesn't know any better... I'm nothing like that high-handed diplomacy of hers! Being compared to that is an absolute insult!!\"",
122133: "\"Ahahaha! Nee-san is definitely running headlong down the pushover road, after all~!\"",
122134: "\"Who are you calling a pushover, huh?!\"",
122135: "\"Well, in this world, by Nee-san's own logic, 'winners are always right'! The whole point of a trump card is to have as many as possible and then actually use them! Don't you agree?\"",
122136: "\"—? (twitch)\"",
122137: "...At that moment, someone reacted to those words.",
122138: "One was Mion. And the other was...!",
122139: "\"Oh...? You stand by those words?\"",
122140: "\"?? Yes, I do. What of it?\"",
122141: "\"Then Satoko—it's decided!\"",
122142: "\"...?\"",
122143: "Shion tilted her head at Mion's meaningful smile, then turned her face back toward Satoko, whom she had cornered. And Satoko—head lowered, arms behind her back against the locker—was pulling something out.",
122144: "\"Shion-san... you said it, did you not? 'A trump card only has meaning when it's used'...\"",
122145: "\"...Satoko?\"",
122146: "\"Then...how about...this?!\"",
122147: "And Satoko—with an expression of triumph that made her earlier near-tears look like another lifetime—thrust the thing in her hand right into Shion's face!",
122148: "\"......Eep?!\"",
122149: "The instant she registered what the thing was, Shion's smile vanished and her face went white.",
122150: "What Shion was frightened of was... a tin can labeled... 'Premium Beef Curry'?!",
122151: "\"N...! S-Satoko?!\"",
122152: "\"Oho-ho-ho! The tables have turned!!\"",
122153: "Satoko declared her plan's success with a triumphant peal of laughter.",
122154: "Normally, Satoko would have bolted only to be caught by Shion immediately and force-fed vegetables amid tears and wailing.",
122155: "...But today, she had been darting around the classroom deliberately—letting herself seem to be cornered, luring Shion to this spot near the locker—all just for this?!",
122156: "\"Now! You said moments ago that you won't allow picky eating, didn't you? Then you must eat this tinned curry as well, Shion-san!\"",
122157: "\"And then I will eat eggplant, green pepper, asparagus—whatever you like!\"",
122158: "\"Ugh... urk...!\"",
122159: "\"Now! Now, now, now—NOW!!\"",
122160: "It was a peculiar spectacle. Satoko, who had seemed all but defeated, brandished the tin can like Mito Koumon's seal of authority—and the apparently invincible Shion took a step back, then another, her ground crumbling...",
122161: "And its contents were curry—loved by nearly every person in the class?!",
122162: "\"W-what's the matter, Shii-chan...? Do you... hate curry?\"",
122163: "\"Heh heh heh...!\"",
122164: "\"Ah, Rena didn't know. Shion absolutely hates canned food~.\"",
122165: "At those words, Shion's shoulder gave a sharp 'twitch!'",
122166: "\"...S-so, Nee-san... you told Satoko about that—\"",
122167: "\"Club rule number two! In the name of victory, anything goes~!!\"",
122168: "\"Damn...! Nee-san! What did I ever do to deserve this?!\"",
122169: "\"Hmm~, the grievances I have against you are literally uncountable... but mostly I thought it'd be funny.\"",
122170: "Right... right, Mion... that's just the kind of person you are...",
122171: "\"Oh, and I've got my money on 'Satoko escapes.' Sorry~!\"",
122172: "\"Mi-Mii-chan... that's... insider trading...\"",
122173: "\"No problem, all within expected parameters.\"",
122174: "Mion just whistled serenely, utterly unruffled by Rena's retort.",
122175: "\"Oho-ho-ho-ho! Let this be a lesson to you! The trump card is something you keep for the very last moment!!\"",
122176: "\"Urgh...?!\"",
122177: "\"Go, Satoko! Today's the day for your first win!!\"",
122178: "\"Now! Please eat it, Shion-san! Picky eating is very bad form~!\"",
122179: "\"Ugh...!\"",
122180: "\"Go on!\"",
122181: "\"Uugh...!\"",
122182: "\"Come on, come on!\"",
122183: "\"Kuh...! S-something so nutritionally unbalanced and junk—I don't need it even without the can!!\"",
122184: "\"Idiot—you IDIOT!!\"",
122185: "\"Ah...\"",
122186: "\"...\"",
122187: "\"...\"",
122188: "\"...She said it.\"",
122189: "\"...Hm?\"",
122190: "DODODODODODODODODODODODODODODODODODODODODODODODODODODODO—!!",
122191: "SUPLERAAASSSHHH!!!!",
122192: "The moment we saw who was standing beyond the door flung violently open—",
122193: "\"——\"",
122194: "\"...\"",
122195: "\"Ahwa... ahwawa...\"",
122196: "\"...?\"",
122197: "Every person in this classroom—no, everyone except one—wished the same thing in their hearts.",
122198: "They prayed for the soul of one poor lamb who had blasphemed against God.",
122199: "\"You are... Sonozaki Shion-san?\"",
122200: "\"Huh? Ye-yes... that's me, but...?\"",
122201: "Silently, smoothly.",
122202: "No—more than smooth, with a movement so instantaneous it was like teleportation: Chie-sensei closed the distance until her face was approximately five millimeters from Shion's nose, eyes bulging, and stared directly at her.",
122203: "Shion flinched back—but Chie-sensei caught the back of her head in a firm grip and didn't let go.",
122204: "\"Ah, aaaaa, um um um—!\"",
122205: "\"You really are the spitting image. Of Mion-san. I wonder if the personality and thinking are the same too—?\"",
122206: "Saying that, and with a neck rotation that would not have looked out of place in an exorcism, Chie-sensei turned to face Mion beside her.",
122207: "The moment their eyes met, Mion—though she was not the one being accused—stood rigid at attention and broke into a torrential sweat.",
122208: "\"I-i-i-i-it's not me! That one and I are completely—poles apart! Oil and water! Hydrogen and oxygen, mix and explode, eat and die—!!\"",
122209: "\"—I see.\"",
122210: "And Chie-sensei turned back to Shion with a smile—a gentle smile that would have flash-frozen the magma of an active volcano.",
122211: "Shion, the only one in the room who had not known the terror of this great lord of fear, finally sensed a mortal threat, and with a face drained of all color, began trying to explain herself.",
122212: "\"A-aaaa-um-um-um-um! T-today is Okinomiya school's founding anniversary! So I'm definitely not skipping class!!\"",
122213: "\"——\"",
122214: "\"A-and if you don't believe me please check with the principal of Okinomiya school!! My coming to visit this school, S-Sonozaki Shion's visit, was done through completely proper legal channels!!\"",
122215: "...Shion, making a desperate case.",
122216: "Honestly, I was impressed. She could still speak under Chie-sensei's Medusa smile... oh, that's terrifying.",
122217: "\"Th-th-th-that's why, today I was, um, that is, um—!!\"",
122218: "\"—That is neither here nor there.\"",
122219: "\"...Ha... huh?\"",
122220: "\"Another school, or an American high school transfer student, or a prototype maid robot from some research facility on a test deployment—I would be perfectly OK with any of those. Quite the contrary—no problems whatsoever. Welcome. Hehe.\"",
122221: "A very generous and warm set of words from Chie-sensei. In proportion, the temperature of the classroom steadily dropped. No one, however, said anything about it. They couldn't.",
122222: "\"Oh, th-that's... is that so? Th-thank goodness... a, ahaha.\"",
122223: "\"However.\"",
122224: "\"Eep?!\"",
122225: "\"Just now... it was unmistakably your voice, your intonation, your phrasing that let fall a certain remark I happened to catch... Curry, you said—what was it, exactly?\"",
122226: "\"Huh... um... I... don't remember what I said...\"",
122227: "\"A... ahaha...\"",
122228: "\"It may be that I misheard. So please recall it once more, clearly, loudly, word for word, honestly and without deception. Now, go ahead.\"",
122229: "\"Ah, um um um, um—!\"",
122230: "\"I should mention that lying carries a severe penalty. Please take after Washington who cut down the cherry tree, and answer honestly.\"",
122231: "\"And if I answer honestly...?\"",
122232: "\"That is my wish. However, being too honest carries the possibility of ending in seppuku, like Sen no Rikyu. So please bear that in mind, as a prior warning.\"",
122233: "...Either way there's no way out?!",
122234: "\"A-um, uh, Se-sensei, please, calm down a little...\"",
122235: "\"I am calm. I am in an exceptionally clear and cool frame of mind right now. Rest assured.\"",
122236: "Sensei... that's not cool. More like cold. No—frozen.",
122237: "The terrifying sight had the entire class rooted to the spot. Even Mion and Satoko were rattled by the completely unexpected collateral damage.",
122238: "This is bad...? If this keeps up, Shion is genuinely in danger.",
122239: "I...",
122240: "Dammit, I'm a man! ...So resolved, I raised my hand and rose to my feet.",
122241: "\"Chie-sensei!\"",
122242: "\"—What is it, brave Maebara-kun...?\"",
122243: "A chill ran down my spine.",
122244: "Even Medusa of legend could not have been this frightening—so I genuinely believed. Chie-sensei turned to face me with that same absolute-zero smile.",
122245: "And the flame of courage that had blazed hot within me froze on the spot and shattered into pieces.",
122246: "\"Ah, aaaa-um, so—!\"",
122247: "D-don't give in...! From some children's book I read once, I was sure there was a scene where the hero coming forward at this moment was what earned him his manhood...",
122248: "\"Sensei, I said it!\"",
122249: "\"Huh? ...K-Kei-chan?!\"",
122250: "\"...I'm sorry, Kei-chan! For doing this to you...!\"",
122251: "\"I can't let you be hurt, can I?\"",
122252: "\"Kei-chan...!\"",
122253: "...Wait a moment.",
122254: "Think carefully. It's Shion.",
122255: "\"Sensei, I said it!\"",
122256: "\"That's right, Sensei—Kei-chan said it!!\"",
122257: "\"Wh-what?!\"",
122258: "\"Ah~, such a pushover, aren't you, Kei-chan? Well, you've saved me. Ahahahah!\"",
122259: "\"Sh-Shion...?! ...thud\"",
122260: "...On second thought, forget it.",
122261: "Still, leaving her to die doesn't sit right. Can't be helped.",
122262: "\"Se-sensei... I, um... didn't hear anything...?\"",
122263: "\"Is that so?\"",
122264: "\"I... really didn't...\"",
122265: "\"...\"",
122266: "Like a rokurokubi apparition, Chie-sensei craned her neck toward me with a long, rubbery stretch. ...Is this person actually human?!",
122267: "\"—Is that so. It seems I must have imagined it. Everyone, enjoy your lunch.\"",
122268: "With that, Chie-sensei smiled sweetly and walked out of the classroom. The instant she did, Shion crumpled boneless to the floor, released at last from the torments of hell.",
122269: "Fortunately, Chie-sensei had her back turned to me. Noticing that, I seized the moment to pull a notebook from my desk, scrawl a message, and hold it up where Shion could see.",
122270: "The message read: 'Just praise curry!! '",
122271: "\"...C-curry is...\"",
122272: "\"—Curry?\"",
122273: "\"...a wonderful thing. The crystallized wisdom of human civilization...!\"",
122274: "Shion finally managed that much, probably the most thoughtful praise she could come up with.",
122275: "\"—Indeed, that is an immutable axiom since the dawn of humanity. Now then, please share with us your thoughts and feelings on the subject of curry. ...Yes, go ahead.\"",
122276: "\"Ngah?! Uh, um, um—!\"",
122277: "\"...\"",
122278: "\"...A-au, au, au...!\"",
122279: "\"...\"",
122280: "\"......Ma-master, kar-curry rice... large portion, four servings...!\"",
122281: "...Whatever had compelled that bizarre and senseless answer, the whole class was left blinking with a collective 'huh??'",
122282: "But perhaps there was some cipher shared among curry lovers, because Chie-sensei's mood lifted all at once, and the taut atmosphere dissolved into something easy and soft. And then—",
122283: "\"—Very well. It seems I did imagine it. Everyone, enjoy your lunch.\"",
122284: "With that, Chie-sensei smiled sweetly and walked out of the classroom. The instant she did, Shion crumpled boneless to the floor.",
122285: "\"Are you okay, Shii-chan?!\"",
122286: "\"...I've lost at least a quarter century off my lifespan...!!\"",
122287: "Even that wasn't an exaggeration. In a manga, Shion's hair would have gone completely white by now.",
122288: "\"Really... I wish you'd think before you speak. I was worried for a moment there...\"",
122289: "\"Whose fault do you think it is, WHOSE!!\"",
122290: "\"Eeeek?! G-get any closer and I'll use—wha?!\"",
122291: "Satoko made a grab for the tin can—her trump card—but her hand closed on empty air. She blinked and looked back.",
122292: "And there, sure enough—",
122293: "\"Might this be the item you were looking for...?!\"",
122294: "Smiling with her mouth but not her eyes, Shion brandished the tin can she had snatched at some point, menace in every syllable.",
122295: "\"...Kuh...!\"",
122296: "Look closely—her brow was deeply furrowed and a cold sweat was beading on her forehead. She really hated canned food that much?!",
122297: "\"In any case—this can go right here.\"",
122298: "Shion tossed the tin can out the window.",
122299: "\"Wha—?! You can't litter cans, Shion-san!!\"",
122300: "\"Haah... you're right.\"",
122301: "\"But seeing as we've come this far, I suppose I'll get serious too—\"",
122302: "GOGOGOGOGO——!!",
122303: "Blue-silver fighting spirit poured from her entire body as Shion slowly advanced.",
122304: "With every step she took, the floor let out not a creak but a 'hssss...!' with an unbearable smell—or so it seemed. I'd like to believe it was my imagination. Yes.",
122305: "\"Prepare yourself... Satokooooo!!\"",
122306: "\"Ah... AAAAAHHH?!\"",
122307: "Murdered—she was definitely going to be murdered!! Cowed by that overwhelming presence, Satoko bolted in the most literal possible sense—but",
122308: "\"Tomita! Okamura!!\"",
122309: "\"\"Yes!!\"\"",
122310: "At Shion's signal, Tomita and Okamura simultaneously leapt up and positioned themselves in front of the exit.",
122311: "\"What?! T-Tomita-san and Okamura-san??\"",
122312: "\"Sorry, Hojo!\"",
122313: "\"No hard feelings, but we can't help this!\"",
122314: "\"How...? Wh—?!\"",
122315: "Satoko spun around with a start—and a few paces behind her, Shion was dangling a colorful piece of paper near her lips.",
122316: "Printed on the paper in large, eye-catching letters were the words... 'DESSERT FESTA ALL-YOU-CAN-EAT INVITATION'!!",
122317: "\"Allow me to return those words. 'The trump card is something you keep for the very last moment.' Heh heh heh~♪\"",
122318: "\"A-auauauauauauauau...\"",
122319: "...Elapsed time eighteen minutes: Satoko Hojo surrenders.",
122320: "As a footnote: the pool ended with no winners.",
122321: "\"Aww~, this was supposed to be my chance to pocket the whole house take~~!\"",
122322: "Mion returned to her seat looking frustrated and popped a meatball in her mouth.",
122323: "\"Mi-Mii-chan...\"",
122324: "A devil. There's a little devil here.",
122325: "Even Rena managed only a strained smile, a complicated mix of exasperation and other things.",
122326: "\"Mion, that was really a bit much though...?\"",
122327: "\"It's fine, it's fine. Satoko's a club member too—if she can't endure this much of a trial, she's not pulling her weight, right?\"",
122328: "\"And as for Shion—she's far more out of the question, this is nothing for her!\"",
122329: "\"Nee-san... I pray divine punishment finds you someday.\"",
122330: "Shooting a resentful glare, Shion handed Satoko a paper napkin.",
122331: "Moved by Rena's suggestion that 'a kabocha-only lunch is too cruel' and pardoned for fighting spirit that had at least landed one good blow—Satoko had scored a generous haul of meatballs, and any trace of her earlier near-tears was long gone.",
122332: "She was rubbing her stomach with a satisfied grin.",
122333: "Well... when all is said and done, they make a good pair. Surprising, maybe, but if anyone were told they were real sisters, I don't think anyone would doubt it.",
122334: "\"But with Shion around it's so lively! Maybe you should just officially transfer over here!\"",
122335: "\"Ahahaha! I'd love nothing more, but there's no way Grandma would allow it.\"",
122336: "\"Please spare me! Even the occasional visits cause huge scenes—my body can't take it if it's every day and every hour! Bleh.\"",
122337: "\"Shall we do asparagus bento tomorrow? Raw, naturally—with just mayonnaise.\"",
122338: "\"Nooooo~!! R-Rena-saaaan, Shion-san is being horrible to meee~~!!\"",
122339: "\"H-hauuu~! Satoko-chan's crying face is so cuu~te☆ It's okay, Rena will—\"",
122340: "\"Oh my, look what I happen to have here. A Dessert Festa invitation~♪\"",
122341: "SWOOM!!",
122342: "\"You should listen to your big sister, shouldn't you? Hau~♪\"",
122343: "That was fast—she switched that fast?! And she's already holding the ticket! ...Has Shion also mastered how to handle Rena by now?!",
122344: "\"That's cheating! Buying someone's attention with things!\"",
122345: "\"Ahaha, the sound of a loose dog is just so pleasant~!\"",
122346: "\"Sh-Shion-san is such a tyrant! Rika~, say something too—\"",
122347: "\"Ah...\"",
122348: "\"...\"",
122349: "\"...\"",
122350: "\"...\"",
122351: "\"...\"",
122352: "Yes—this lively, chaotic lunch hour.",
122353: "And beyond that: the fun afternoons of teasing each other and competing earnestly at the club.",
122354: "One member who should have been there—quiet, but a definite presence—had been outside the circle for about a week now.",
122355: "When she first transferred in, she used to team up with Satoko to tease me, and at the same time looked out for me in all sorts of ways.",
122356: "But then, for some reason—from a certain day onward—she had quietly pulled away.",
122357: "Had I done something to make her dislike me...? I'd even asked Mion, but apparently not.",
122358: "And it wasn't just me she had gone quiet with—it was Mion, Rena, and most of all Satoko, her own housemate.",
122359: "\"...I wonder what's wrong with Rika-chan...\"",
122360: "\"Mm... well, they say this year's cold is a nasty one. If we make too big a fuss and end up pressuring her, that's no good either.\"",
122361: "...Mion said that—but everyone really understood.",
122362: "That Rika-chan was downcast because something was weighing on her mind.",
122363: "And that was precisely why, even though they wanted to help, no one knew what was really troubling her, and the helpless waiting had gone on and on.",
122364: "\"So where is Rika-chan right now?\"",
122365: "\"Hmm... her bag's still here, so I don't think she's gone home.\"",
122366: "\"...\"",
122367: "\"Ah, Sato—\"",
122368: "Noticing Satoko slumped in dejection beside her, Shion started to speak—but Satoko, as if shaking off her dark mood, raised her face and said with a bright smile:",
122369: "\"Well, there's no need to worry so much! She ate dinner properly last night, so I think her cold will be better before long!\"",
122370: "\"Satoko-chan...\"",
122371: "\"...Yeah. If Satoko says so, it must be true! Alright—when the cold's gone, let's all throw a get-well party!!\"",
122372: "\"Yes! Yes! And when that happens, Rena will cook to her heart's content!!\"",
122373: "\"Ahahaha! Then this old-timer will prepare something grand and delicious too!\"",
122374: "\"Ohhh! Mion's grand cooking~~ drool~! Naturally Satoko gets none! I'll have it all!!\"",
122375: "\"Oho-ho-ho-ho! Keiichi-san, you never improve! Do you really think I, trained by the terrible Shion-san, would concede victory so easily?!\"",
122376: "\"Who are you calling terrible, WHO?!\"",
122377: "\"Waaah!! I-it hurts, it hurts, it hurts, it huurts~~!! A knuckle noogie is against the rules~~!!\"",
122378: "\"Ahahahahaha!!!\"",
122379: "And so, noisily, the lunch break passed.",
122380: "Rika-chan... I don't know what you're worrying about, but we're all here, waiting for the day you'll share it with us.",
}
