#!/usr/bin/env python3
"""Translations for taraimawashi_1.json"""
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TRANSLATIONS = {
53142: "The cotton drifted along lazily downstream.\nThe Watanagashi ceremony must still be going upstream.",
53143: "I had been staring absently at the current, lost in thought, and sometime in the middle of it all I had wandered away from Rena and the others.",
53144: "Not that I was anxious about it.\nThis was my village now — a place I was beginning to call home.",
53145: "So I decided to take it easy and wait where I was until someone came looking for me.",
53146: "When I glanced up, I noticed a figure standing at the edge of the riverbed.",
53147: "Squinting into the dark… it looked like a girl.\nTall and slender, with long hair.",
53148: "I couldn't make out her face from behind, so I walked over on a vague impulse.",
53149: "She must have heard the crunch of gravel underfoot — she turned toward me.",
53150: "…Mion?",
53151: "\"Oh. — Good evening, Kei-chan.\"",
53152: "No… it was Shion, her twin sister.",
53153: "Since the Angel Mort incident, Shion had started visiting Hinamizawa every now and then — but even now, I had trouble telling them apart at a distance.",
53154: "\"Well, what do you know — Shion, you came too.\"",
53155: "\"Was I not allowed to?\nI'm part of this village too, you know.\"",
53156: "She gave me a mischievous little smile as she said it.\n…An odd way to put it, really.",
53157: "\"I suppose that's true.\nOnce-a-year village festival and all.\"",
53158: "\"——Yes…\"",
53159: "She turned her face just slightly toward the surface of the river as she answered, her voice dropping a shade.",
53160: "Something felt subtly off.\n…Had I said something strange?",
53161: "\"That's not it.\n…But…\"",
53162: "But… what?",
53163: "\"No… it's nothing.\"",
53164: "…She said it was nothing, but her expression said otherwise.\nIf anything, it seemed to be saying that there was very much something.",
53165: "\"What is it?\"",
53166: "\"……………\"",
53167: "Shion kept her eyes downcast, turning something over in her mind.",
53168: "Every so often her lips moved slightly — but I couldn't make out what she was saying.",
53169: "\"——Kei-chan.\"",
53170: "She suddenly looked up and fixed her gaze on me, then asked something strange.",
53171: "\"If… something happened… once a year, always on the same day.\nWhat would you think of that, Kei-chan?\"",
53172: "\"…What do you mean?\"",
53173: "\"Something like… an accident… or an incident.\"",
53174: "\"…That doesn't sound very peaceful.\nAre you saying that something happens to everyone who comes to this festival?\"",
53175: "\"No, it's not everyone exactly.\"",
53176: "An oddly roundabout way of putting it.\nAnd though I'd meant it as a joke, she hadn't denied it outright.",
53177: "…Not everyone? So there's a specific target — someone particular it happens to?",
53178: "Neither of us spoke for a while. Silence passed between Shion and me.",
53179: "I was starting to feel the need for air, and was just about to open my mouth when —",
53180: "\"Kei-chan… do you believe in curses?\"",
53181: "Curses…?!",
53182: "The sudden question made me look at Shion without thinking.",
53183: "\"Did I startle you? I'm sorry — that was a strange thing to ask out of nowhere.\"",
53184: "She offered a light recovery, but… I couldn't laugh it off, and the words caught in my throat.",
53185: "The gravity in her expression gave me an uncanny feeling — a disquiet I couldn't shake.",
53186: "\"The Watanagashi festival traces back to an offering meant to appease Oyashiro-sama's curse.\"",
53187: "\"To quell the curse of that god, people float cotton down the river once a year — that's what this is.\"",
53188: "…That much I had heard before, from Mion and the others.",
53189: "Even so — a curse. What did that actually mean? Was Oyashiro-sama not a god of blessings, but a god of calamity?",
53190: "\"Don't tell me, Shion — you actually believe in curses?\"",
53191: "\"Well, I… it's complicated.\nBut even among younger people in this village, there are quite a few.\nWho believe.\"",
53192: "\"…Is that so.\"",
53193: "Given her personality, I had expected a flat denial — so the ambiguity left me more unsettled than anything.",
53194: "In this day and age, with all the advances modern science had made — I found it hard to believe that young people still held such things to be real.",
53195: "\"And every year, after the festival… it happens.\nWithout fail, right around this time.\"",
53196: "\"…Something happens — what, exactly?\"",
53197: "\"On the night of the Watanagashi… someone in this village…\"",
53198: "She paused a moment there, glancing around as if checking whether anyone could hear, then dropped her voice.",
53199: "\"…dies.\"",
53200: "\"——!?\"",
53201: "I had thought I had already found my footing in Hinamizawa.\nBut there was still so much I didn't know.",
53202: "Things about the past — terrible things — that people went quiet about whenever I asked.",
53203: "I had known that Rena and Mion were hiding something from me.",
53204: "Still, I had told myself: they probably just didn't want a newcomer to get the wrong impression of Hinamizawa… that was how I had made my peace with it.",
53205: "Even so — even if it was all in the past — as someone who now lived here, I wanted to know the village's darker side too.",
53206: "Grateful as I was for their protectiveness… I found, almost despite myself, that I was strangely drawn in.",
53207: "So… wanting to hear more, I stepped closer to Shion.",
53208: "\"Three years ago, on the night of the Watanagashi — that was when it started.\nA couple on a trip fell into a flooded ravine.\nThe husband died, and the wife's body was never found.\"",
53209: "\"A fall… that was an accident?\"",
53210: "\"…That's what the police said.\"",
53211: "The skepticism in her voice gave everything she'd said a far more ominous cast.",
53212: "\"The night of the Watanagashi the following year, the head priest of the shrine died without warning — cause unknown.\nAnd that same night, his wife waded into a pond and drowned herself.\nHer body was never found either…\"",
53213: "\"The head priest — of this shrine?\"",
53214: "In answer, Shion gave a silent nod.",
53215: "\"And the year after that — also on the night of the Watanagashi, of course.\nThis time, a woman from the village was found beaten to death.\"",
53216: "Beaten to death — the words sent a chill through me.\n…And yet what struck me even more was a strange, nagging skepticism.",
53217: "A travel accident, a sudden illness… they were too mundane for a curse, too accident-prone to be anything but coincidence — or so it felt to me.",
53218: "\"But… all the people who died were deeply connected to something.\"",
53219: "\"Something\"… what?",
53220: "\"…A terrible incident, one at the heart of this village.\"",
53221: "Hearing that, I found myself saying out loud something that Tomitake-san had once told me — almost without realizing I was doing it.",
53222: "\"The dam construction… in Hinamizawa?\"",
53223: "\"How do you know about that?!\"",
53224: "Her reaction was stronger than I expected — it put me off balance.\n…Was it really so strange that I knew?",
53225: "\"Yes, it is a surprise.\nEveryone keeps that story hidden from people who don't already know.\nI never would have thought you'd be aware of it, Kei-chan.\"",
53226: "…She might have had a point.",
53227: "\"Is that right, you already knew… \nAll of these people were either in favor of bringing in the dam, or were passive in opposing it.\"",
53228: "…So that meant… the guardian deity had struck down the ones who stood to drown Hinamizawa — that was how the people here saw it.",
53229: "That was what they believed.",
53230: "Everyone who had died after the Watanagashi was connected to the dam — to Oyashiro-sama.",
53231: "But… the beating stood apart from the others. Because that one was murder.",
53232: "Which made me wonder — what connection did the murdered woman actually have?",
53233: "\"This woman who was killed — what was her involvement?\nWas she connected to the dam opposition as well?\"",
53234: "\"Her husband was the younger brother of the man who died in that travel accident.\"",
53235: "The tenuous connection made it all the more terrifying.\nA relative of a dam supporter was enough — enough to be cursed to death?!",
53236: "How deep did this curse run, to spread so wide through the village…\nAnd that thought made me suddenly recall the other incident.",
53237: "The one that had happened at the dam construction site — yes, that gruesome murder of the site foreman.",
53238: "\"At the time, the debate over whether to continue construction had grown heated.\nScandals kept surfacing and the situation kept unraveling…\nThe dismemberment murder was the event that brought the dam project to its final end.\"",
53239: "Coming from Shion's lips, the word \"murder\" resonated with a strange, lingering echo.",
53240: "\"It happened deep in the night on the night of the 1979 Watanagashi.\nSix men, after an argument, turned on the victim together.\"",
53241: "\"They say they hadn't meant to kill him at first.\nBut when the victim started swinging a shovel, the others grabbed whatever was at hand — and it escalated, all at once, into slaughter.\"",
53242: "Uoooooh——!! Uaah——uaah——!!",
53243: "The men's shouts intertwined, shovels and pickaxes clashing with showers of sparks.",
53244: "The victim — the foreman of the construction site…",
53245: "\"According to the suspects, the foreman had been tormenting those six men for a long time.\nThat night the drinking ran too deep, tempers frayed, and it turned into an argument…\"",
53246: "\"At first they only meant to get back at him — but in the end, all of them together…\"",
53247: "Uoooooh——!! Uaah——uaah——!! Gyaaah——!!",
53248: "The men's shouts rang like hallucinations in my inner ear, and the sparks flying from shovels and pickaxes against the dark flashed — flash… flash-flash — playing out deep inside my skull like a scene projected from memory.",
53249: "\"When they came to themselves, what lay there could not, by anyone's eyes, be called alive.\"",
53250: "A dark liquid spreading across the ground. A stifling, cloying stench. And on the shovels, the pickaxes they each held — not dirt but something else…",
53251: "Wasn't that enough already.",
53252: "And yet the suspects — they went further — what they did to the foreman was…",
53253: "\"They dismembered him.\"",
53254: "…Why?! Why such a brutal thing…",
53255: "\"I've heard that the men did initially consider turning themselves in.\nBut the ringleader was the one who proposed hiding the body.\nAnd the remaining five, who had hesitated…\"",
53256: "…Gradually came to feel that they couldn't let themselves be caught.",
53257: "They weren't alone. There were five others sharing the crime with them — if everyone kept silent, they could keep it hidden.",
53258: "Anyone would have reached the same conclusion. And besides…",
53259: "\"There was no shortage of places to hide a body on a construction site.\nThey were supposed to hide it and leave quickly.\"",
53260: "I could picture the five men, faces desperate.\nThey must have been desperate to get out of there.",
53261: "But then — there was more.",
53262: "\"The ringleader, it seems, was afraid the other five would panic and confess, and the whole affair would come to light.\nSo he took steps to ensure their silence.\"",
53263: "\"…How, exactly?\"",
53264: "She fell quiet there.\nShe seemed to be deciding whether to say it.",
53265: "\"…What is it, Shion?\"",
53266: "I urged her to continue past the hesitation.\nAnd haltingly, choosing her words, Shion — said it.",
53267: "\"He proposed cutting the body into pieces corresponding to the number of men, and having each one hide their own portion…\"",
53268: "\"Wha——?!\"",
53269: "So that was the truth behind the dismemberment — they needed to divide it by the number of men.",
53270: "Force each of them to carry the weight of what they'd done — even in what came after.",
53271: "I couldn't help thinking it was diabolical.",
53272: "\"The men wept, they trembled — not one of them could refuse.\nThere were some who resisted, but they must have feared being killed by the ringleader in turn.\nIn the end, I've heard that every single one of them took part.\"",
53273: "…For a while, I couldn't close my mouth.",
53274: "The battle over the dam that had placed Hinamizawa's very existence in the balance.\nAnd at the height of that battle, a murder of breathtaking brutality.",
53275: "That was all I had known — and all I had thought I wanted to know.",
53276: "But it hadn't been all there was.",
53277: "Murder. Accidental death. Natural death. Suicide. Bludgeoning. — Kill, kill, kill, KILL, KILL…",
53278: "…I was, at my core, a child of the modern age. I didn't want to believe in curses.",
53279: "But… after that horrific incident, a strange pattern of deaths — every year, on the Watanagashi, always someone tied to the dam…?!",
53280: "It would be easy enough to call any one of them a coincidence.",
53281: "But… as they piled up, one after another…",
53282: "…Calling it coincidence began to feel like the more irrational response.",
53283: "I don't believe in curses.",
53284: "…But… whatever you call it — there is, without question, some kind of intent behind the pattern — something that makes things happen on the Watanagashi every year.",
53285: "\"Wait — so you're saying this year too, on the night of the Watanagashi, someone's going to die?\nWho is it this time?\"",
53286: "\"There's no way to know something like that…\"",
53287: "…Right. If anyone knew, they'd try to stop it.",
53288: "A sickly-warm gust of wind passed through.",
53289: "\"No one says it out loud… but I think everyone is afraid.\nAfraid that something will happen again tonight.\"",
53290: "\"Then everyone being at the festival is…\"",
53291: "…Out of fear of the curse?",
53292: "\"In the end, everyone is… scared.\nOf Oyashiro-sama's curse.\"",
53293: "\"……………\"",
53294: "I was at a loss for words.",
53295: "In this day and age.",
53296: "When every field of knowledge had made astonishing advances, lighting up the dark corners of ignorance and the unknown.",
53297: "Black-and-white televisions were extinct. Rockets had carried human beings to the moon.",
53298: "And yet… in this modern world…?",
53299: "I felt like I was beginning to understand why Rena and Mion had been so reluctant to tell me.",
53300: "If nothing happened at this year's Watanagashi, they could have kept me in the dark forever.",
53301: "…If nothing happened, that would be fine. Then everything would just be unfounded worry.",
53302: "I could have gone on pretending I'd never known anything. And they would have acted as if nothing had ever happened.",
53303: "…And then our ordinary days would have come back.",
53304: "Right. If I just told myself I never knew any of this, then…",
53305: "\"…Should I not have told you?\"",
53306: "\"No, it's not that —\"",
53307: "I forced out those words with every bit of composure I had — but I couldn't fully conceal the turmoil welling up inside me.",
53308: "Whether she knew it or not, Shion continued.",
53309: "\"…But you know, Kei-chan.\nAfter the Watanagashi, it's not only the dead.\"",
53310: "\"You may have already noticed…\"",
53311: "\"Along with them, someone always disappears.\"",
53312: "…In the foreman murder four years ago, the ringleader…",
53313: "In the travel accident, the dead man's wife was swept away into the river…",
53314: "After the shrine priest's death from illness, the wife who was said to have drowned herself was also still…",
53315: "Someone disappears alongside the dead…",
53316: "\"I mentioned a woman who was beaten to death earlier.\nAfter that incident, her child too…\"",
53317: "\"Went missing?\"",
53318: "\"Truly… without any warning…\"",
53319: "— Shion's voice dropped another note.",
53320: "The murmur of the stream must have still been there.\nBut it no longer reached my ears.",
53321: "Instead, the cry of the higurashi — ringing out as if at the wrong time — cut into my hearing with an uncanny edge.",
53322: "\"The incident was around nine in the evening on June 20th of last year.\nThe woman was found face-up in the road, drenched in blood.\nAt first they couldn't tell anything except that it was a middle-aged woman.\"",
53323: "That couldn't be right.",
53324: "This wasn't some big city like Tokyo.\nIf you asked a neighbor, you'd know whose household she belonged to in an instant.",
53325: "That may have been the natural question to ask.\nBut Shion's answer was cruel — and devastating.",
53326: "\"Yes, you'd think so.\n…But her face had been completely destroyed.\"",
53327: "For a moment, my thoughts stopped.",
53328: "…For a brief instant, I considered: if her face was destroyed, maybe it would take time to identify her.",
53329: "But something prickled all the hair inside my ears — an almost subliminal wrongness. For just a fraction of a second, like rewinding tape, the words repeated themselves.",
53330: "Destroyed… what was destroyed… her face…",
53331: "Goosebumps rose across every inch of my skin, and through those pores, cold sweat seeped out.",
53332: "\"The police believed the attack was motivated by personal hatred.\nApparently, the killer had beaten the back of the head to a pulp, then deliberately flipped the body face-up and destroyed the face.\"",
53333: "\"……………\"",
53334: "It had been early summer. The warm weather must have made the thick smell of blood all the more suffocating.",
53335: "The image of it — the smell of it — welled up in me, and I felt suddenly nauseated.",
53336: "\"And after that incident, the woman's child went missing.\"",
53337: "The child of a woman whose face had been obliterated — gone without a trace…",
53338: "What possible connection was there between the two? Was there any logic, any equation, that could make sense of it to a human mind?",
53339: "\"Before he disappeared, the boy had been saying something.\n'…Someone is watching me… I'm being followed.'\"",
53340: "Paranoia — the state of flinching at every shadow — is something any mind can fall into. If it was said that the boy had simply been like that, I had no strong argument to the contrary.",
53341: "But if he had sensed the harbingers of the incident before it happened, that was another story entirely.",
53342: "He had perceived both the calamity that would befall his family and the one that would befall himself — with certainty.",
53343: "\"Someone says it: 'That was a harbinger of Oyashiro-sama's curse.' 'That child must have had some part of his heart that wanted to abandon Hinamizawa and run — Oyashiro-sama wouldn't forgive that.'\"",
53344: "A deity who would not permit the abandonment of the village — could such a thing exist?",
53345: "I couldn't believe in a god who demanded that kind of love under threat.",
53346: "\"So… surely, tonight again, someone will be sacrificed —\"",
53347: "\"——Kei-chaaaan!!\"",
53348: "She had been about to say something when a voice called my name.\nI turned, and saw Mion running toward us, waving her arm widely.",
53349: "\"Oh, sorry, sorry, left you all alone!\nWait — …Shion?\"",
53350: "\"Good evening, Sis.\nSomething you need?\"",
53351: "\"Something I need — do I need a reason to come over?\"",
53352: "It was only an instant.",
53353: "In Mion's voice I felt something — a hot breath like what a beast exhales, blood-warm, sending a creeping chill down my spine.",
53354: "That hot breath seemed to fill the whole space between us, and I felt every hair on my body stand on end.",
53355: "Was I the only one who felt it?\nI stole a glance at Shion's profile.",
53356: "I didn't miss it — the way Shion's eyes went slightly narrow.",
53357: "It was plain that she had sensed something in Mion's words.",
53358: "Yet Shion appeared to let it pass without so much as acknowledging it, and with a light, breezy manner, she shrugged and answered.",
53359: "\"I was just wondering whether there was something you needed.\nThat's all.\"",
53360: "As if deliberately rubbing against the grain —",
53361: "\"Oh well, ha-hahahahaha!\"",
53362: "In the next instant, Mion burst out laughing — loudly and merrily.",
53363: "Like a taut rubber band suddenly released — a slackening of tension washed over me, an almost physical sense of relief.",
53364: "Something in my chest seemed to exhale for the first time — though I didn't quite know why.",
53365: "But —",
53366: "\"I thought maybe I'd walked in on the two of you sharing some sort of inappropriate conversation.\"",
53367: "\"Inappropriate? What do you mean?\"",
53368: "\"Well… that's what I'm asking.\"",
53369: "The unease flooded back.",
53370: "\"……………\"",
53371: "Shion let out a soft ufufu — a light, airy little laugh.",
53372: "\"Oh, is that right. What sort of inappropriate conversation did you have in mind?\"",
53373: "She tilted her head in an exaggerated show of innocence.\nSomething about the deflection seemed to harden Mion's expression further.",
53374: "\"……………\"",
53375: "But the next instant Mion's face changed back to its usual open, unguarded expression.\nAnd then,",
53376: "\"So, Shion — is today your day off from work?\"",
53377: "\"Oh, what time is it?\"",
53378: "\"It's already this late.\"",
53379: "Mion held out her wrist to show the time on her watch.",
53380: "\"Oh no!\nI've stayed much later than I meant to!\"",
53381: "\"That's why I asked whether you had a reason you couldn't go — meaning your shift!\"",
53382: "…Ah… so that was the \"couldn't\" she'd meant?",
53383: "\"Thank you for telling me, Sis!\nI'm sorry, Kei-chan.\nI should get to work!\"",
53384: "With that, Shion took off at a sprint.",
53385: "Mion watched her go with a long-suffering sigh.",
53386: "Well, she really is something — I was about to respond with a wry smile when —",
53387: "\"Shion — what did she say?\"",
53388: "\"Huh…?\"",
53389: "The question came so suddenly that the words caught in my throat.",
53390: "\"She said something to you, didn't she, Kei-chan?\"",
53391: "\"Huh — no, not really?\"",
53392: "\"…Why are you hiding it?\"",
53393: "\"What…?\"",
53394: "\"There's no point hiding it — I'll figure it out anyway.\nYou can't pull the wool over this old man's eyes.\"",
53395: "I felt a strange, sharp glint deep in Mion's eyes.",
53396: "…Words failed me.\nI hesitated — should I tell her what Shion had said?",
53397: "It had been a story Mion and the others had tried to keep secret — so the words stuck in my throat and I ended up looking away.",
53398: "I could see the cotton flowing past, drifting along the surface of the river at my feet.",
53399: "…Why was that, I wondered. Was it the horrifying things I'd been told?",
53400: "The silhouettes of the cotton mounds looked, in the half-dark, like lumps of flesh riding a conveyor belt —",
53401: "Suddenly, a wave of nausea hit me.",
53402: "\"—Kei-chan?!\"",
53403: "I had bent double with one hand over my mouth.",
53404: "\"Are you alright?\"",
53405: "Mion laid a hand on my shoulder.\nIt was a soft, warm touch, full of gentleness.",
53406: "…Gradually my stomach settled.",
53407: "\"Sorry.\nThat came out a bit harsh.\"",
53408: "\"But… look, don't let it get to you.\nShe has this habit of saying disturbing things just to mess with people.\"",
53409: "\"I'm fine, I told you.\nShe didn't say anything strange.\"",
53410: "\"Really?\"",
53411: "\"Really.\"",
53412: "\"Really, really?\"",
53413: "\"I said really!\"",
53414: "Mion studied my face with skeptical eyes.",
53415: "\"You're being strange, Mion.\nWhy are you the one reading so much into this?\"",
53416: "\"What — no, I just… like, what were you two doing alone together in a dark place like this, is all!\"",
53417: "\"What? What's that supposed to mean?\"",
53418: "\"Oh come on, 'the blazing red season of summer,' right?\"",
53419: "\"That makes even less sense, and it's nighttime.\"",
53420: "\"Oh, you know.\nMaybe this old man is reading too much into things~?\nAh-hahahaha!\"",
53421: "The conversation had veered in a strange direction.\nAll the same, telling Mion what Shion had told me didn't feel right.",
53422: "So I couldn't ask whether what Shion had said was true.",
53423: "…A shadow still lingered in Mion's expression — something suspicious.",
53424: "I matched her ambiguous smile with one of my own.",
53425: "\"Kei-ichuuun!!  \nSorry~~!!\"",
53426: "I turned at my name and saw Rena bounding toward us like she was hopping.",
53427: "Behind her, Satoko and Rika-chan came running too, panting.",
53428: "\"We are terribly sorry!\nWe forgot all about you, Keiichi-san!\"",
53429: "\"How dare you!\nForgetting about me is absolutely unforgivable!\"",
53430: "\"That isn't true.\nWe were looking for you the whole time.\n…We simply got a little too caught up in conversation, that's all.\"",
53431: "That's called forgetting in the real world!",
53432: "\"It wasn't only the conversation!\nThe sweets at the stalls were partly to blame too, you know.\nWe cannot be held at fault!\"",
53433: "\"Yeah, yeah!\nThe apricot candy was really good, wasn't it? ...Right?\"",
53434: "…You all completely forgot about me!",
53435: "The three of them looked at each other and grinned.",
53436: "I sagged backward and looked up at the sky.\nYou guys are exactly that kind of people… hahah.",
53437: "\"Heyyy, everyone!\"",
53438: "And now Tomitake-san had arrived too.",
53439: "\"Oh my, isn't that Tomitake-san.\"",
53440: "\"Tomitake, perfect timing.\"",
53441: "\"Ahaha, announcement time for the shooting gallery results!\"",
53442: "\"Oh… r-right…!\nSo am I in last place, in the end?\"",
53443: "When all was said and done, today's contest had ended with my dramatic victory — but the battle for last place that followed had been just as fierce.",
53444: "In the end Rika-chan had stepped up to challenge, but there was almost nothing left to shoot at by that point.",
53445: "The few remaining targets were all tiny — no bigger than matchboxes.",
53446: "For Rika-chan to aim at anything, the counter was simply too high. Even I couldn't have taken a steady stance on tiptoe.",
53447: "And then there was the weight of the gun — her arm wobbled no matter what. There was really no way around it.",
53448: "And yet — the world of competition is a harsh one.",
53449: "However great the disadvantage, you find the strength within yourself to push past it and move forward.",
53450: "You shoot the enemy!",
53451: "That was the code and the crowning glory of our club.",
53452: "In that respect, Rika-chan truly lived up to her reputation.",
53453: "Meaning — she missed all three shots perfectly, ending in a tie for last place with Tomitake-san! …Or so it should have been.",
53454: "But the battle-hardened Rika-chan reached for her trump card — her ultimate weapon.",
53455: "Which was —",
53456: "She burst into tears right there in front of the stall, crying \"mii— mii—\" and backed the old stall-keeper into a corner.",
53457: "The passersby naturally assumed it was the old man who had made her cry.",
53458: "Cold stares rained down.",
53459: "\"I— I can't help it, can I? You're too much for me, little lady…\" — and she obtained gum!",
53460: "Even Tomitake-san, seasoned as he was, had no counter to that.",
53461: "Rika-chan — was she a fox, or a tanuki?",
53462: "\"Keiichi, you are thinking something dreadful about me.\nI am a perfectly upstanding individual, you know. Kon-kon.\"",
53463: "…The little cry at the end sounded distinctly fox-like to me.",
53464: "\"So! Tomitake-san, you are officially in last place!\"",
53465: "Everyone burst into squeals and applause, applause, grand applause!",
53466: "\"Well then… ha-hahaha.\nThank you very much.\"",
53467: "Tomitake-san scratched the back of his head and laughed, looking sheepish.",
53468: "…Pitiful — it was clear he had absolutely no idea how terrifying these people were.",
53469: "\"Hm…? What do you mean?\"",
53470: "\"Oh, Kei-chan just means 'how lucky you are, Tomitake-san.'\"",
53471: "\"Exactly.\nYou are very lucky indeed.\"",
53472: "\"Ohohohoho!\nYou are truly a man of great fortune.\nHow terribly enviable!\"",
53473: "If it's that enviable, you can trade places with him.",
53474: "\"Lucky, lucky~!\nSo enviable~! Hau~♪\"",
53475: "…These people are demons…!",
53476: "\"Alright, Tomitake-san — are you ready?\nPenalty game!!\"",
53477: "\"Hm? Oh, right… I forgot about that!!\"",
53478: "You can't just forget about it — that's not how our club works.",
53479: "Mion produced a marker from her pocket.",
53480: "…Ah, it's the face-prank thing. Permanent marker is rough. At least make it washable.",
53481: "\"That wouldn't work — permanent is the whole point.\nOtherwise it just washes off~\"",
53482: "\"Wh— hey! What's that for? You're going to write on me?!\"",
53483: "Everyone held Tomitake-san from behind while Mion approached slowly, marker in hand.",
53484: "The tension was frightening…",
53485: "\"There we go!\nAlright, squeak squeak squeak!\"",
53486: "But what Mion wrote on was not his face — it was his shirt.",
53487: "\"Hurry up and make it to the big leagues! Mion\"",
53488: "Next, Rika-chan took the marker and wrote: \"Even in last, your heart is in first. Rika\"",
53489: "A faint warmth came over me, and I couldn't help but smile.",
53490: "\"Haha, this isn't a punishment anymore — it's a farewell message.\"",
53491: "\"Ohohohohoho!\nI am not so lenient, I assure you.\nThis is absolutely still a punishment game!\"",
53492: "\"Next time you come back, I'll put you in last place again! Ohoho! Satoko\"",
53493: "\"You're up next, Keiichi-san.\"",
53494: "I wasn't sure what to write, but given the spirit of the game… this seemed about right.",
53495: "\"Please come visit again. Keiichi\"",
53496: "Then I passed the marker to Rena.",
53497: "Rena thought for a long moment, then seemed to have an idea, and wrote:",
53498: "\"Next time, please show us your photos☆ Rena\"",
53499: "Tomitake-san had looked surprised at first, but by the last message he was smiling broadly.",
53500: "\"Hahaha, I wonder if I have to go back to Tokyo wearing this.\"",
53501: "\"Of course you do!\nIt's a punishment game.\nWear it all the way home!\"",
53502: "\"Ahaha, maybe wear it again when you come back next time too!\"",
53503: "He seemed moved.",
53504: "His face was red — a complicated mixture of embarrassment and a dozen other feelings.",
53505: "\"Understood.\nI'll wear this the next time I come.\nI promise!\"",
53506: "Oh, right.",
53507: "Like Rena said — next time you come, if you show us the photos…",
53508: "\"Right.\nTomitake-san, take a picture of all of us.\"",
53509: "\"Good idea — let's get a commemorative photo!\"",
53510: "He said that, then pulled out a tripod and set the self-timer.",
53511: "\"Ready?\nHere we go~\n…Say cheese!\"",
53512: "A burst of cheers and applause from everyone.",
53513: "It was the best parting gift we could give to a friend we were saying goodbye to tonight.",
53514: "I happened to glance toward the main shrine and noticed a woman standing there — Tomitake-san's companion.\nHe seemed to have noticed too, and I sensed that the time for goodbyes had come.",
53515: "\"Oh my, your companion is waiting~?\nIs it that time already, hm~?\"",
53516: "\"Hm? Ahahaha, looks like it.\"",
53517: "Tomitake-san walked over to the woman and seemed to be apologizing for the wait.",
53518: "We each called out our farewells to him in turn.",
53519: "Each time, he turned back and waved.",
53520: "…And then his retreating figure dissolved into the darkness of the night and was gone.",
53521: "\"…There he goes.\"",
53522: "\"Well, I've got to stay to help clean up — so, until next time!\"",
53523: "Mion was staying for the post-festival cleanup, and Rika-chan was remaining for a committee meeting with the other organizers.",
53524: "Satoko was staying as Rika-chan's tagalong. Rena and I headed home, and that was how we parted ways.",
53525: "\"See you, Kei-chan.\nSee you tomorrow!\"",
53526: "Mion gave a crisp little wave.",
53527: "\"Oh, Mion —\"",
53528: "\"…?\"",
53529: "I had called out to her without thinking.",
53530: "I had wanted to ask her: why haven't you told me about the incident? That was what I'd wanted to say.",
53531: "But… when I remembered that the people involved in the incidents had all been opponents of the dam project —",
53532: "Meaning they had been people who stood against the Sonozaki family — and the words froze in my throat, and I ended up saying nothing.",
53533: "\"Well… see you tomorrow.\"",
53534: "…That was all I could manage.",
53535: "\"Yeah, see you tomorrow!\"",
53536: "I watched Mion go with a complicated, undefined expression on my face.",
53537: "Rena stood watching me with a puzzled look.",
}

# Load the file
with open(BASE_DIR / 'taraimawashi_1.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for entry in data:
    if entry.get('type') not in ('MSGSET', 'LOGSET'):
        continue
    if 'TextENGNew' in entry:
        continue
    mid = entry.get('MessageID')
    if mid in TRANSLATIONS:
        entry['TextENGNew'] = TRANSLATIONS[mid]
        count += 1

with open(BASE_DIR / 'taraimawashi_1.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"taraimawashi_1.json: wrote {count} translations")

# Verify
with open(BASE_DIR / 'taraimawashi_1.json', 'r', encoding='utf-8') as f:
    data2 = json.load(f)
missing = [e.get('MessageID') for e in data2 if e.get('type') in ('MSGSET','LOGSET') and 'TextENGNew' not in e]
print(f"Still missing: {len(missing)}")
if missing:
    print("Missing IDs:", missing[:10])
