import json, re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Strip game-engine tags from Japanese text before translating
def clean_jpn(s):
    # remove @vS.../... @k @r @w### @b...<...> @| @y `` etc.
    s = re.sub(r'@v[^\s.]+\.', '', s)
    s = re.sub(r'@[a-zA-Z][^\s@]*', '', s)
    s = re.sub(r'@[|<>]', '', s)
    s = re.sub(r'``', '', s)
    s = re.sub(r'@b([^.]+)\.@<([^>]+)@>', r'\2', s)
    s = re.sub(r'@k|@r|@y', '', s)
    return s.strip()

translations = {
    # common_day5_2.json
    21033: "That's it for today's classes.",
    21034: "Now then... what should I do next?",
    21036: "Once I was home, I got myself ready right away.",
    21037: "I'd made a promise with Rena to dig the Randy-kun figure out of that mountain of treasure.",
    21038: "\"Mom, do we have any work gloves around? And some towels.\"",
    21039: "\"Didn't you check the shed out front? The towels are in the bathroom.\"",
    21040: "All right. I was fully prepared. My mom gave me a puzzled look.",
    21041: "\"Keiichi, what's all this? Where are you going looking like that...?\"",
    21042: "If another illegal dumper came along and buried it completely beyond rescue... there was no doubt Rena would set her sights on the Randy-kun statue in front of the fried chicken shop in town.",
    21043: "\"A little excavation. So my classmate doesn't turn into a criminal.\"",
    21044: "\"...Well, don't stay out too late.\"",
    21045: "Mom went back to the kitchen with that same puzzled look on her face.",
    21046: "Cutting through the forest path that was a shortcut to the dam site, I came across a looming silhouette.",
    21047: "It was Tomitake-san.",
    21048: "I wondered if he'd managed to get any good shots of wild birds with that pride-and-joy camera of his.",
    21049: "...Surely he wasn't spending all his time photographing handsome boys at sunset...??",
    21050: "\"Hey, long time no see. You're Keiichi-kun, right?\"",
    21051: "\"Thanks for the other day.\"",
    21052: "I chased the rude image from my mind and greeted him without incident.",
    21053: "\"Come to think of it... that girl was an acquaintance of yours, wasn't she...??\"",
    21054: "He probably meant Rena. Judging by how rattled Tomitake-san looked...",
    21055: "\"Wh-What on earth was that!? She was walking around with a bare hatchet!? And with this big grin on her face!!\"",
    21056: "That was definitely Rena.",
    21057: "She was probably unable to hide her excitement at finally getting to take it home today.",
    21058: "\"I sensed danger and hid myself... shouldn't I call the police...!?\"",
    21059: "I had to admit, a girl her age wandering around with an unsheathed hatchet was pretty alarming.",
    21060: "Tomitake-san's reaction was entirely reasonable.",
    21061: "\"It's fine, it's fine. Just leave her alone. She's only out looking for her next victim.\"",
    21062: "Tomitake-san's eyes went wide at my flippant response.",
    21063: "Well, it's probably hard for an ordinary sensible person to understand Rena... I'd just blow smoke at him.",
    21064: "\"If you got killed out here, she'd probably be the one who did it. Best not go poking around where you shouldn't.\"",
    21065: "With a wicked little smirk, I headed off toward the dam site where Rena was waiting.",
    21066: "I'd barely taken a few steps when Tomitake-san called out to me.",
    21067: "\"Keiichi-kun, was that meant as a warning to an outsider like me?\"",
    21068: "...Wait, I didn't mean it seriously. I tried to say something, but—",
    21069: "\"Ha ha ha! Well, I'll be sure to watch my step.\"",
    21070: "With only those words, Tomitake-san turned on his heel and walked away.",
    21071: "Outsider... that's a bit much... I really hadn't meant anything by it.",
    21072: "It was just supposed to be a small joke, but somehow it felt like I'd said something I shouldn't have...",
    21073: "When I got back from school, Mom called out to me.",
    21074: "\"Keiichi, could you run an errand for me?\"",
    21075: "\"An errand...?\"",
    21076: "\"We've run out of instant ramen. You'd be miserable without it, wouldn't you?\"",
    21077: "\"Yeah, yeah...\"",
    21078: "It's no exaggeration to say that instant ramen is my lifeline. If Mom's away and the fridge is empty, no ramen in stock is practically a death sentence.",
    21079: "...All right, that might be overstating it a little. But that's how important it is to me.",
    21080: "\"You can pick whatever kind you like, but buy a whole box. Oh, and pick up some canned goods too. Oh, and also...\"",
    21081: "\"I'm off!\"",
    21082: "I bolted out the door. If I hadn't, she'd keep remembering things to add to the list until I was hauling home an entire warehouse. My bike's basket simply didn't have that kind of capacity.",
    21083: "\"Watch out for cars~!\"",
    21084: "\"Will do!\"",
    21085: "Her voice followed me through the door as it closed.",
    21086: "I unlocked my bike where it sat in the corner of the garage and tested the pedals, which were a little stiff. ...You know, a little cycling now and then isn't so bad. Weather's nice too.",
    21087: "All right, let's go! I set off pedaling at a brisk clip.",
    21088: "With the harsh afternoon sun fading and the air beginning to cool, my bike glided down the gentle slope toward town.",
    21089: "\"Hey, good afternoon!\"",
    21090: "Halfway down the hill, someone called out to me.",
    21091: "Huh...!? Was that directed at me? Wait, who was that?",
    21092: "Before I could remember, the bike picked up speed and carried me on down the hill.",
    21093: "From the clothes and the feel of it, they had to be a Hinamizawa resident...",
    21094: "Once I finished the downhill, I hit the upslope. I gathered speed and threw myself at the steep incline.",
    21095: "Hah... hah... This is pretty rough...",
    21096: "There I was, standing on the pedals and dripping with sweat, while the woman walking ahead of me glided along with effortless grace.",
    21097: "No way am I going to let some old lady show me up! I kept stomping the pedals with everything I had.",
    21098: "\"Keep it up, keep it up!\"",
    21099: "As we passed each other, the lady unexpectedly called out to me.",
    21100: "\"Th-Thank you!\"",
    21101: "I couldn't help shouting back with more enthusiasm than I intended.",
    21102: "My speed on the bike matched almost exactly with her walking pace, putting us side by side.",
    21103: "She was strolling along serenely with a warm smile, while I gripped the handlebars in a dead-eyed grimace and drove the pedals down with both feet.",
    21104: "It was hard to even breathe a response, but the cheering was still welcome.",
    21105: "The moment I crested the hill—",
    21106: "\"Congratulations~!\"",
    21107: "When I turned around, the lady was waving at me. ...Who was she again?",
    21108: "\"Thank you~!\"",
    21109: "Still unable to place her, I waved back. She was probably a local farmer's wife or something...",
    21110: "Was my memory just not keeping up, or were the residents of Hinamizawa just unusually quick to recognize people's faces? Either way, today I'd been greeted by strangers more times than I could count.",
    21111: "...But honestly, I didn't mind at all. If anything, I felt good about it.",
    21112: "There was a warmth and friendliness to this place that I'd never experienced in the city, and it left my heart full.",
    21113: "Hinamizawa really is a nice village... The people here, most of all, are so warm.",
    21115: "...I found myself suddenly thinking about the incident that supposedly happened in this village.",
    21116: "A brutal murder at the dam construction site...",
    21117: "Could something that terrible really have happened in a peaceful place like this?",
    21118: "...I can't believe it.",
    21119: "\"Well. The past is the past, and the present is the present...\"",
    21120: "I said it as if convincing myself, then pedaled hard toward the town of Okinomiya.",
    21121: "I took a long moment to savor that warmth, then pedaled on toward Okinomiya.",
    21122: "Seventh Mart came into view.",
    21123: "All right, where to start.",
    21125: "\"Keiichi-kun~! I've been waiting. Let's give it our all today!\"",
    21126: "I could see what Tomitake-san had been talking about.",
    21127: "Gallivanting around while brandishing a hatchet would certainly look alarming.",
    21128: "\"Put a sheath or something over that hatchet when you carry it. Going around with a bare blade is a bit much!\"",
    21129: "\"I think I lost it somewhere... so there isn't one.\"",
    21130: "Then again, reputation was probably a moot point for her.",
    21131: "Everyone in Hinamizawa likely already knew all about Rena's peculiar habits.",
    21132: "She was probably the only person who could stroll through Hinamizawa with a hatchet and not raise a single eyebrow...",
    21133: "\"Ah well! Let's finish this today! One more beam and we can pull it free. I came prepared. Leave it to me!\"",
    21134: "\"Okay!\"",
    21135: "I took the hatchet from Rena and made my way down the unstable slope.",
    21136: "\"Just wait, Randy-kun. Keiichi-kun is going to save you now...☆\"",
    21137: "\"All right, stand back. I'm going to end this in one shot!!!\"",
    21138: "A clean, ringing crack rang out through the valley, the kind you'd expect from a proper lumberjack.",
    21139: "\"...How does it look? Think it's going to work? If it seems too hard, you don't have to push yourself...\"",
    21140: "\"If I can just break through this one, we're home free! I've got plenty of energy today! I can do it!!!\"",
    21141: "...But the enemy was tougher than I expected.",
    21142: "For one thing, I had never actually used a hatchet before.",
    21143: "At a school camping trip once, I'd volunteered to split wood and lost at rock-paper-scissors before I even got to try.",
    21144: "The unstable footing wore me down quickly, and I decided to take a break.",
    21145: "Rena had already spread a sheet and laid out a thermos of tea and some sweet snacks.",
    21146: "\"I'm fine! Just a little more. By the time Rena goes to sleep tonight, she'll be able to give Randy-kun a good-night kiss.\"",
    21147: "\"...Yeah. ...Thank you. ...Randy-kun... a good-night kiss... hau...\"",
    21148: "\"Come to think of it... you transferred in too, didn't you, Rena? Where did you live before?\"",
    21149: "I asked casually while sipping the tea.",
    21150: "I'd always just assumed she'd lived here her whole life.",
    21151: "\"Hmm? Kanto area. It wasn't quite as rural as here, but still out in the countryside, I suppose.\"",
    21152: "\"Why did you move here? To Hinamizawa, I mean. It's pretty out of the way.\"",
    21153: "\"Why did you move here, Keiichi-kun? Was it something to do with your dad's work?\"",
    21154: "\"My dad decided he wanted to move his studio. He'd always said somewhere deep in the mountains would be perfect.\"",
    21155: "\"A studio? ...Is your father an artist?\"",
    21156: "\"He paints landscapes. Apparently he opens a solo exhibition somewhere about twice a year.\"",
    21157: "He'd started out exhibiting at some gallery in a Tokyo ward, but now he was showing at a proper venue.",
    21158: "He'd been excited about eventually getting into the new exhibition hall planned for the reclaimed waterfront.",
    21159: "\"That's amazing! You'll have to show me sometime!\"",
    21160: "...I was too embarrassed to admit that I didn't actually know much about what my dad painted.",
    21161: "Well, someday. I gave a vague answer and got back to my feet.",
    21162: "\"But... you transferred in the middle of the semester, didn't you? Wasn't that rough?\"",
    21163: "\"Not really. ...I was getting bored of the city anyway.\"",
    21164: "I'd been the one asking questions, yet somehow I'd ended up being the one doing all the answering.",
    21165: "With a wry smile, I took hold of the hatchet and headed back to work.",
    21166: "The sun began to tilt, and the air grew slowly cooler.",
    21167: "The higurashi began their chorus, as if telling me to pack it in and go home.",
    21168: "Just a bit more. Today... I'd settle it.",
    21169: "At first I'd been joking around with Rena as I worked, but that luxury was long gone.",
    21170: "\"Hyah! ...You little—! ...Damn it!\"",
    21171: "I swung the hatchet just as I had done countless times that day. Contact. Splinters flew.",
    21172: "\"The perpetrators beat their victim to death with hatchets and pickaxes, leaving the body mutilated beyond recognition,\"",
    21173: "A passage from that tabloid article came back to me without warning.",
    21174: "One blow with something like this and a person's skull would cave in...",
    21175: "A hatchet or a pickaxe was never something to be swung at a person, not under any circumstances.",
    21176: "Seventh Mart was a discount bulk retailer for food and liquor in town. A bit of a distance, but if you're buying in bulk, it was cheaper than the shopping district stores and had a wider selection.",
    21177: "The shop floor was packed with merchandise, and it was busy with people rummaging through the shelves. The ramen section, fortunately, wasn't that crowded.",
    21178: "With no one getting in my way, I examined the shelves carefully. They were lined with a dizzying variety of cup noodles that made me want to dance.",
    21179: "Hokkaido butter-style rich miso, Sanuki udon style, Kitakata soy sauce... I would have loved to load my cart with a colorful assortment, but I'd been told to buy in bulk.",
    21180: "Since I'd come by bike, I could only choose one type to take home in a box. That made picking the right cup noodle feel like a life-or-death decision. After scrutinizing every last label on the shelves, I settled on one.",
    21181: "\"Nothing else for it. This is the one...\"",
    21182: "And what I pulled off the shelf was... Extra Large Cup Tonkotsu Ginger Flavor!",
    21183: "Tonkotsu is delicious! And it's a big serving, but it doesn't taste bloated! From the moment I realized I could only pick one, the truth was that no other flavor was ever really in the running!",
    21184: "I hoisted the cardboard box and turned toward the register — and stopped dead.",
    21185: "...!?",
    21186: "A sudden creeping feeling in my chest. Someone was behind me.",
    21187: "An inexplicable unease welled up, and I spun around to find—",
    21188: "\"Keiichi-kun~♪\"",
    21189: "\"You finally noticed~. You're so oblivious, Kei-chan!\"",
    21190: "\"...Oh, it's just Mion and Rena.\"",
    21191: "I quietly breathed a sigh of relief. I must have been more anxious than I'd realized... What in the world had I been so jumpy about!?",
    21192: "\"Were you surprised? I was wondering how long it would take you to catch on!\"",
    21193: "\"Instead of lurking around, just say hello like a normal person.\"",
    21194: "Rena and Mion looked at each other and grinned.",
    21195: "Apparently these two had been tailing me for a while. Unbelievable... If you're going to pull something, at least go all out and startle me properly!",
    21196: "\"...Keiichi-kun, cup ramen isn't very good for you, you know.\"",
    21197: "\"Mind your own business.\"",
    21198: "\"Is that okay though? It says Tonkotsu Ginger flavor on the box.\"",
    21199: "My cup noodle selection is beyond reproach! Say it, Mion! Tell it to Rena!",
    21200: "I drew a long breath and unleashed every burning conviction in my chest!",
    21201: "\"Don't you dare look down on Extra Large Cup Tonkotsu Ginger Flavor!\"",
    21202: "\"This volume, this bold cup design! The rich depth of the tonkotsu broth transcends the very concept of instant noodles — it possesses a gravity that could satisfy even the most discerning of ramen artisans!\"",
    21203: "\"It's a generous serving, yet never feels heavy, and it's priced like someone who's made peace with existence itself! An absurdly low price! Tell me — what other cup ramen could possibly take its place?!\"",
    21204: "\"...?\"",
    21205: "The two of them stared at me blankly. That look of utter bewilderment made me want to shrink into the floor.",
    21206: "\"A-Anyway, it tastes good.\"",
    21207: "I left them behind and hurried toward the register.",
    21208: "\"Oh... hau... Keiichi-kun, don't you need anything else? Anything else at all?\"",
    21209: "\"Mind your own business...!\"",
    21210: "I was about to say exactly that, when I remembered Mom had also asked for canned goods. Nice going, Rena!",
    21211: "\"Are you two here on an errand?\"",
    21212: "\"I'm just along for the ride. I also wanted to see if there were any interesting new snacks.\"",
    21213: "Of course. The reigning queen of junk food.",
    21214: "\"Hmm? Don't go slapping weird titles on me~!\"",
    21215: "\"What's wrong with it? Anyway...?\"",
    21216: "Just then I caught the eye of a girl who'd stopped and was looking at us in mild confusion. Mion noticed her too and turned to look.",
    21217: "\"Oh, it really is you, Mion-chan. Hello~!\"",
    21218: "\"...Huh~? Isn't that Natsumi-chan? It's been forever!\"",
    21219: "\"What are you doing here? Did you come back?\"",
    21220: "\"No. Today's the founding anniversary, and Grandma wanted to come back home for it after so long. I'm planning to head back tonight.\"",
    21221: "\"Is that so~? Well, the highway here gets pretty backed up on weekends! Ah—\"",
    21222: "At that, Mion noticed that Rena and I were looking back and forth between the two of them in complete confusion.",
    21223: "\"Oh, sorry — I forgot to introduce you! This is Kimiyoshi Natsumi-chan. She's a relative of the village chief's, and she lived in Okinomiya until last year.\"",
    21224: "\"...Really? So we just missed each other, huh.\"",
    21225: "\"Nice to meet you. I went to school in Okinomiya though, so Mion-chan is the only one I know.\"",
    21226: "\"Hey. Nice to meet you too.\"",
    21227: "We chatted easily and introduced ourselves. She looked about the same age as Rena and me.",
    21228: "\"Well, see you around. I've got to get going.\"",
    21229: "\"Sure, take care! Will you be back for the festival?\"",
    21230: "\"Probably. Grandma's really looking forward to it.\"",
    21231: "With that, Natsumi-chan left the shop with a cheerful wave and a smile.",
    21232: "\"Oh, I'm going to check out the new snacks~\"",
    21233: "Mion drifted off toward the candy section.",
    21234: "\"What did you come to buy, Rena?\"",
    21235: "\"Dish soap, floor cleaner, bath soap, laundry detergent, and a bottle of water. Plus mirin and soy sauce...\"",
    21236: "Come on, isn't that a lot?... Are you planning to carry all that home by yourself?!",
    21237: "In the meantime, Mion had made her way to the register with yet another basket overflowing with snacks. ...As expected of Seventh Mart, that terrifying bulk retailer with its iron grip on the desires of every Hinamizawa resident!",
    21238: "We made it through the register without incident and finished our shopping.",
    21239: "\"Uh~. Did I buy too much? Too much?\"",
    21240: "Sure enough, Rena's haul was far more than a bicycle basket could hold.",
    21241: "\"...Honestly. I'll carry half — you can put it in my basket. I'll see you home.\"",
    21242: "\"Hau~. Thank you so much, Keiichi-kun~!\"",
    21243: "Rena's face went rosy and warm.",
    21244: "\"Kei-chan, put some of mine in too~~!\"",
    21245: "\"There's no more room! If it's candy, I'll eat it right here, right now!\"",
    21246: "\"Buuu~! I'd rather haul it home myself than let Kei-chan eat it!\"",
    21247: "Rena and I looked at each other and laughed as Mion crammed snacks into her basket with ruthless determination.",
    21248: "\"See! It fits!\"",
    21249: "We cheered at the wobbling but somehow successful mountain of snacks piled high in the basket.",
    21250: "And so I wound up hauling a full basket of groceries all the way to Rena's house.",
    21251: "Seventh Mart was a discount bulk retailer for food and liquor in town. A little far, but buying in bulk there was cheaper than the shopping district shops, and they had a far better selection.",
    21252: "The shop floor was crammed with merchandise, and it was bustling with people looking through the shelves. The canned goods section, fortunately, wasn't too crowded.",
    21253: "With no one getting in my way, I examined the shelves methodically.",
    21254: "There was more variety in canned goods than you'd think...",
    21255: "What Mom told me to buy was probably cooking staples.",
    21256: "Miso-simmered mackerel, shellfish tsukudani, sardine balls, braised liver... I had to make up my mind before my hunger got completely out of control.",
    21257: "Since I'd come by bike, I could only take one type home in a box.",
    21258: "After scrutinizing every label on the shelf with hawk-like intensity, my final selection was... Charcoal-Grilled Yakitori, Sweet Soy Glaze!",
    21259: "This really is the best. Something I'd quietly loved since I was a kid.",
    21260: "That smoky charcoal fragrance sealed inside the tin! The satisfying density of chicken packed in with all its texture intact! If I were told I could only bring one can to a desert island, there was really no other choice.",
    21261: "I hoisted the cardboard box and turned toward the register — and stopped dead.",
    21262: "...!?",
    21263: "A sudden creeping feeling in my chest. Someone was behind me.",
    21264: "An inexplicable unease welled up, and I spun around to find—",
    21265: "\"Keiichi-kun~♪\"",
    21266: "\"You finally noticed~. You're so oblivious, Kei-chan!\"",
    21267: "\"...Oh, it's just Mion and Rena.\"",
    21268: "I quietly breathed a sigh of relief. I must have been more anxious than I'd realized... What in the world had I been so jumpy about!?",
    21269: "\"Were you surprised? I was wondering how long it would take you to catch on!\"",
    21270: "\"Instead of lurking around, just say something already.\"",
    21271: "Rena and Mion exchanged glances and smirked. Apparently these two had been tailing me for a while.",
    21272: "What a pair... If you're going to pull something, at least go all out and surprise me properly!",
    21273: "\"It's unusual to see you doing the shopping, Mion.\"",
    21274: "\"Hehe... I was wondering if there were any interesting new snacks. ...Oh, Kei-chan, buying canned goods in bulk?\"",
    21275: "Mion glanced over at my cardboard box, her own basket already overflowing with snacks.",
    21276: "\"Charcoal-Grilled Yakitori, Sweet Soy Glaze...? Bold choice. Very old-man-ish.\"",
    21277: "\"I don't need that from you. ...What's wrong with it?\"",
    21278: "\"Heh heh heh... Kei-chan, do you know the terrifying story that goes with canned goods...?\"",
    21279: "Mion edged closer with a grin like she found it all tremendously funny. ...I was genuinely curious, but asking right before dinner felt like a mistake, so I politely declined.",
    21280: "\"But really! If you don't check what's inside before you buy it, you'll get a nasty shock when you open it~\"",
    21281: "A nasty shock...!?",
    21282: "Has Rena actually opened some unidentifiable can before...!?",
    21283: "\"Hmm...?\"",
    21284: "Just then I caught the eye of a girl who'd stopped and was looking at us in mild confusion. Mion noticed her too and turned to look.",
    21285: "\"Oh, it really is you, Mion-chan. Hello~!\"",
    21286: "\"...Huh~? Isn't that Natsumi-chan? It's been forever!\"",
    21287: "\"What are you doing here? Did you come back?\"",
    21288: "\"No. Today's the founding anniversary, and Grandma wanted to come back home for it after so long. I'm planning to head back tonight.\"",
    21289: "\"Is that so~? Well, the highway here gets pretty backed up on weekends! Ah—\"",
    21290: "At that, Mion noticed that Rena and I were looking back and forth between the two of them in complete confusion.",
    21291: "\"Oh, sorry — I forgot to introduce you! This is Kimiyoshi Natsumi-chan. She's a relative of the village chief's, and she lived in Okinomiya until last year.\"",
    21292: "\"...Really? So we just missed each other, huh.\"",
    21293: "\"Nice to meet you. I went to school in Okinomiya though, so Mion-chan is the only one I know.\"",
    21294: "\"Hey. Nice to meet you too.\"",
    21295: "We chatted easily and introduced ourselves. She looked about the same age as Rena and me.",
    21296: "\"Well, see you around. I've got to get going.\"",
    21297: "\"Sure, take care! Will you be back for the festival?\"",
    21298: "\"Probably. Grandma's really looking forward to it.\"",
    21299: "With that, Natsumi-chan left the shop with a cheerful wave and a smile.",
    21300: "\"Oh, I'm also going to check the new release section~. The melon cream cookies should be out by now.\"",
    21301: "Mion wandered off toward the candy section. With her basket already stuffed with sweets, was she seriously going to buy even more?!",
    21302: "\"Is that all you're getting, Keiichi-kun? Is that all?\"",
    21303: "\"Of course. As long as I have my yakitori...\"",
    21304: "I was about to say exactly that, when I remembered Mom had also asked for cup ramen.",
    21305: "Nice going, Rena!",
    21306: "\"What did you come here for, Rena?\"",
    21307: "\"Dish soap, floor cleaner, bath soap, laundry detergent, and a bottle of water. Plus mirin and soy sauce...\"",
    21308: "Come on, isn't that a lot?... Are you planning to carry all that home by yourself?!",
    21309: "In the meantime, Mion headed toward the register, her basket overflowing with yet more snacks.",
    21310: "The terrifying bulk retailer Seventh Mart, with its iron grip on the desires of every Hinamizawa resident!",
    21311: "We made it through the register without incident and finished our shopping.",
    21312: "\"Uh~. Did I buy too much? Too much?\"",
    21313: "Sure enough, Rena's haul was far more than a bicycle basket could hold. Why don't you realize these things before you buy!",
    21314: "\"...Honestly. I'll carry half — put it in my basket. I'll see you home.\"",
    21315: "\"Hau~. Thank you so much, Keiichi-kun~!\"",
    21316: "Rena's face went rosy and warm.",
    21317: "\"Kei-chan, put some of mine in too~~!\"",
    21318: "\"There's no more room! If it's candy, I'll eat it right here, right now!\"",
    21319: "\"I'd rather haul it home myself than let Kei-chan eat it!\"",
    21320: "Rena and I looked at each other and laughed as Mion crammed snacks into her basket.",
    21321: "\"See! It fits!\"",
    21322: "We cheered at the wobbling but somehow successful mountain of snacks piled high in the basket.",
    21323: "And so I wound up hauling a full basket of groceries all the way to Rena's house.",
    21324: "The final blow snapped the beam clean in two.",
    21325: "The force of the hatchet split not only the beam but also crashed into the shoulder of the figure beneath it.",
    21326: "There was an ugly sound, and the arm came off.",
    21327: "It rolled and clattered to a stop at my feet.",
    21328: "\"...Ah,\"",
    21329: "\"Wh-What happened, are you okay!? Are you hurt!?\"",
    21330: "\"S-Sorry... I broke the figure's arm...\"",
    21331: "\"...Oh, is that all? I thought Keiichi-kun had hurt himself.\"",
    21332: "I must have looked deeply guilty. Rena said it with a smile, without a cloud on her face.",
    21333: "\"We can stick it back on with duct tape and put a jacket over it. Nobody will ever know.\"",
    21334: "\"...I see. Let's pull it out then. Can you grab that side?\"",
    21335: "\"Okay!\"",
    21336: "(...It was a terrible incident, wasn't it. ...They still haven't found them, right?)",
    21337: "In the dim light, the figure lying there seemed unnervingly real, and a vague sense of dread crept over me... but I caught myself and laughed quietly at my own foolishness.",
    21338: "Both Rena and Mion knew full well what a disgusting incident it had been.",
    21339: "That was why they'd pretended not to know anything about it.",
    21340: "I was the one who had gone out of my way to look it up.",
    21341: "...And now, pathetically enough, I was afraid.",
    21342: "\"...Get it together, Keiichi Maebara! All right, Rena! We're doing this in one go! Ready... go!!!\"",
    21343: "\"...Whoa! We did it! We did it, Keiichi-kun!! Yaaaaay!!\"",
    21344: "Three cheers all around! The culmination of two hard days' work.",
    21345: "He had been filthy and bound for an end buried in Hinamizawa. Instead, he had been welcomed back to the world.",
    21346: "You got lucky, Randy-kun. Your new master is a good person.",
    21347: "\"...Waaaah... It's Randy-kun... He really is so kyute!!\"",
    21348: "Filth and all, Rena happily pressed her cheek against him.",
    21349: "I was completely exhausted, but watching Rena's face light up with joy made it feel worth every moment.",
    21350: "\"Come on, I'll help you carry it. We should head out before it gets dark.\"",
    21351: "\"...Yeah. You're right! Thank you so much, Keiichi-kun! I'll never forget this!\"",
    21352: "\"I'll take my time thinking about how you can repay me.\"",
    21353: "\"Wh-Whoa... I wonder what kind of repayment... It will be repayment, right?\"",
    21354: "For now I'd just hold onto my best wicked smile and leave it there.",
    21355: "We were finally ready to haul it to her house, but we couldn't exactly go looking like this.",
    21356: "We wrapped the figure up in the sheet and carried it out together.",
    21357: "Down a dimming mountain path — two young people carrying a human-sized bundle and a bare hatchet!",
    21358: "All I could do was pray we didn't run into Tomitake-san.",
    21359: "If he spotted us here and took a photo... we'd have to make him disappear. (lol)",
    21360: "\"...Was that meant as a warning?\"",
    21361: "Tomitake-san's words, so at odds with my casual tone, kept nagging at me.",
}

data = json.load(open(BASE_DIR / 'common_day5_2.json'))

count = 0
for entry in data:
    if entry.get('type') in ('MSGSET', 'LOGSET'):
        mid = entry.get('MessageID')
        if mid in translations and 'TextENGNew' not in entry:
            entry['TextENGNew'] = translations[mid]
            count += 1

with open(BASE_DIR / 'common_day5_2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added TextENGNew to {count} entries in common_day5_2.json")
