#!/usr/bin/env python3
"""Add TextENGNew translations to kamikashimashi_3.json"""
import json, re, copy

def strip_tags(s):
    if s is None:
        return s
    # Remove @vS.../..../....... voice tags
    s = re.sub(r'@vS[\w/]+\.', '', s)
    # Remove @w### wait tags
    s = re.sub(r'@w\d+\.', '', s)
    # Remove @b...@<...@> ruby tags - keep only displayed text between @< and @>
    s = re.sub(r'@b[^@]+@<([^@]+)@>', r'\1', s)
    # Remove @k (click wait), @r (newline), @| (center), @e (end)
    s = re.sub(r'@[kre|]', '', s)
    # Remove @y, @z###., @s##. style tags
    s = re.sub(r'@[yzs]\d*\.?', '', s)
    # Remove backtick pairs (`` text ``)
    s = re.sub(r'`', '', s)
    return s.strip()

# Translations: {MessageID: "TextENGNew"}
translations = {
154300: "\"Found it. This should open it.\"",
154301: "\"Au, au. What if there's a terrifying ghost locked in there?\"",
154302: "\"Then you two can hold a staring contest and see which of you is the scarier monster.\"",
154303: "\"Rika!\"",
154304: "The strange, repetitive sound was coming from the other side of a heavy door marked EMERGENCY STORAGE.",
154305: "Someone was hurling themselves against the thick metal door — or so it seemed.",
154306: "\"But why the emergency storage room?\"",
154307: "\"Perhaps someone used it as a makeshift cell...\"",
154308: "\"Who? When? For whom?\"",
154309: "\"Even Oyashiro-sama doesn't know that!\"",
154310: "\"I suppose that's fair.\"",
154311: "The emergency storage room door was the type that locked from outside.",
154312: "Since something kept hammering at it from within, there was clearly no way to unlock it from inside.",
154313: "When Rika returned with the master key, the sound had gone quiet for a moment.",
154314: "Perhaps whatever was inside had worn itself out. Or perhaps it was holding its breath, waiting for them to walk in.",
154315: "\"...I'm opening it.\"",
154316: "\"G-Go ahead whenever you're ready...\"",
154317: "She slid the key in and slowly turned it......",
154318: "Surely they hadn't quarantined an L5 patient in here — had they?",
154319: "If they had, the moment she opened the door, that person could come flying out and launch at her.",
154320: "\"Not a chance. ......There's no reason Irie and the others would do something so senseless as locking someone up here.\"",
154321: "For the hundred-years witch Rika, it was hard to resist the curiosity of what might lie beyond that door.",
154322: "She had no interest in this ruined world. Yet dying was something she could do at any time.",
154323: "So she wanted to see what became of it right up until the very end.",
154324: "It wasn't some noble desire to bear witness — more like a faintly wicked, morbid curiosity.",
154325: "She slowly opened the heavy door......",
154326: "Through the narrow gap came a gust of hot, foul air — a mix of sweat and something rotting.",
154327: "It wasn't terror she felt so much as revulsion.",
154328: "There was a light on inside...... And a sweaty man collapsed on the floor slowly raised his face......",
154329: "\"......Tomitake......\"",
154330: "\"Hey...... Rika-chan...... ......You saved me.........\"",
154331: "\"What were you doing in a place like this?\"",
154332: "\"Good question. One thing's for certain — it wasn't by my own choice.\"",
154333: "\"Rika...... Look at the pipes in the back.\"",
154334: "\"......Handcuffs......\"",
154335: "Fastened around the pipes at the back of the storage room were a pair of broken handcuffs.",
154336: "He had almost certainly been bound by them.",
154337: "Just how long had he been imprisoned in here?",
154338: "From the look of things, it had to have been more than a day or two.",
154339: "......Surely he hadn't been locked up here throughout this entire ordeal?",
154340: "He was gaunt and utterly exhausted, but he seemed to have held onto his sanity by the thinnest of threads.",
154341: "\"By the way. ......Has anything happened outside over these past few days?\"",
154342: "\"Not much. ......If anything, it's finally grown quiet.\"",
154343: "\"......Rika.\"",
154344: "\"The villagers have been falling into terminal stage one after another. And now it seems to be spreading beyond the village, into Okinomiya as well.\"",
154345: "\"Good God...... W-What about Takano-san?!\"",
154346: "\"......Come to think of it, I haven't seen her since this all started.\"",
154347: "\"Could you get Director Irie here immediately...... Something terrible is going to happen.\"",
154348: "\"Something terrible has already happened, and it's over now.\"",
154349: "\"No, something even worse is coming. Takano-san intends to spread Hinamizawa Syndrome across all of Japan — no, across the entire world......!!\"",
154350: "It had all begun several days ago.",
154351: "Tomitake had already been locked up in here back when things were still peaceful, before any of it started......",
154352: "\"......Nnh......nnh..........\"",
154353: "\"You're awake...? Jirou-san.\"",
154354: "He had been roused with smelling salts.",
154355: "Tomitake's body was heavy as lead as he slowly looked up at Takano......",
154356: "He tried to move his legs and felt a cold, heavy weight against them.",
154357: "Looking down, he found handcuffs clamped around his ankles, fastened to the pipes.",
154358: "\"Ah, Takano-san...... What kind of joke is this......?\"",
154359: "\"A joke? ......Hehe, hardly. This is a true divine revelation.\"",
154360: "\"......What are you talking about.........?\"",
154361: "\"I have been chosen by God. ......Yes. All of this is a divine revelation......\"",
154362: "Takano's eyes looked as though she were burning with fever.",
154363: "She herself must have felt perfectly calm.",
154364: "Yet to Tomitake's eyes, she looked drunk on some terrible liquor, lost in a waking dream......",
154365: "\"Please, calm down...... Could you explain this in terms I can follow?\"",
154366: "\"......You're right. Come to think of it, putting it in terms you'd understand would be no great challenge. But I had to tell you. Even if it means nothing to you.\"",
154367: "\"......And yet you still wanted to tell me. ......I'm a little flattered.\"",
154368: "\"Hehe. Thank you for saying that. ......You really are someone special to me, Jirou-san.\"",
154369: "\"And yet you'd chain this special person to a pipe in a storage room?\"",
154370: "\"I want you to stay here quietly until the world is reborn into something new.\"",
154371: "\"What are you scheming......?\"",
154372: "\"Not scheming — a divine revelation. I have been chosen by God......!\"",
154373: "Tomitake was no fool.",
154374: "From that exchange he could already dimly grasp what Takano was planning.",
154375: "\"Don't tell me you're planning to cause something terrible......?\"",
154376: "\"Something terrible may occur. But it is God's revelation. I have a feeling this is the beginning of something wonderful.\"",
154377: "\"......You're not planning to take the virus we've been studying out of here, are you?\"",
154378: "\"Hehe, hehe. I'm sure all of our research was in preparation for this day. God chose me. He understood my noble mission......!!\"",
154379: "\"Stop this...! I don't know who put you up to it, but this is no divine revelation! This is a devil's whisper!\"",
154380: "\"A devil? How harsh. ......Perhaps you can't see their divine glory? Well — of course not. You're only an ordinary person. Hehe, hehe, hehe......\"",
154381: "Takano pulled something from her jacket and tossed it to Tomitake.",
154382: "It was a small case containing a syringe and a medicine vial.",
154383: "He recognized it. It was the new experimental prophylactic for Hinamizawa Syndrome.",
154384: "Though it should still have been in development......",
154385: "\"If...... you wish to see the new world, Jirou-san — inject this. ......If you're fortunate, you may avoid acute onset.\"",
154386: "\"Stop this! It's not too late to turn back! Talk to me! And undo these handcuffs first!\"",
154387: "Takano slowly picked up the attache case sitting at her feet.",
154388: "No ordinary attache case — it was a specialized case for transporting η173.",
154389: "If she released its contents, a vast number of people would contract Hinamizawa Syndrome, eventually reach L5, and bring about catastrophe.",
154390: "To Takano, researching the Syndrome was a sacred act — a way to prove her grandfather's work to the world, to be counted among the divine. He knew that.",
154391: "But unleashing an outbreak of Hinamizawa Syndrome and bringing about some terrible apocalypse was never supposed to be her goal......",
154392: "He couldn't begin to imagine what delusions had overtaken her.",
154393: "But she was fully prepared to do it. ......Without the slightest hesitation.",
154394: "\"Goodbye for now, Jirou-san. If you're lucky, we'll meet again. ......Since this is an emergency storage room, there should be food and water within your reach.\"",
154395: "\"I'm sure you'll manage those handcuffs somehow, Jirou-san. Even if I lock this door from outside, yes?\"",
154396: "Given enough time, Tomitake would certainly be able to free himself from the handcuffs.",
154397: "But that would give Takano all the time she needed to execute her terrible plan......",
154398: "\"Wait — wait, Takano-san!! Wait, wait, waittttttttt!! Are you trying to destroy the world?!\"",
154399: "\"Heavens, no. ......I am going to save humanity, as God has commanded me. By setting these dear little ones free all at once!\"",
154400: "\"That is the devil's whisper! You mustn't listen to it!!\"",
154401: "\"The devil is apparently somewhere else.\"",
154402: "\"Huh?\"",
154403: "\"A devil trying to destroy humanity has already appeared. ......God told me. He said I am the only one who can stop it.\"",
154404: "\"What you are about to do is the very work of the devil! You must not be deceived!!\"",
154405: "\"Don't worry. God is always with me. ......Farewell. I'm going to Okinomiya. That's where it is, isn't it?\"",
154406: "\"Yes, I know. Hehe, hehe, ufufufufufu...... Hahahahahahahahahahaha......!!\"",
154407: "\"Wha...... How could this be...... Au, au, au......\"",
154408: "\"Exactly as expected — the woman never learns. ......So it's her fault again after all.\"",
154409: "\"We're too late......? Good lord.........\"",
154410: "Tomitake had been captured by Takano right before the incident began and had been locked up here ever since.",
154411: "It was all too late now. Takano had already spread the infection far beyond the village.",
154412: "Perhaps it had already reached the entire city, or even the whole prefecture......",
154413: "Tomitake shook his head again and again as Rika described the current situation.",
154414: "The reality was hard to swallow, yet the grim sight of the researchers' bodies left no room for doubt......",
154415: "Tomitake went to the security room and tried the radio, but contact with the outside proved impossible.",
154416: "Per the emergency manual, in the event of a Hinamizawa Syndrome outbreak, jamming signals were to be deployed across the entire city to prevent the spread of panic.",
154417: "The phone lines were dead as well, of course.",
154418: "There was no way to relay the crucial information — that Takano was the culprit — to the outside world......",
154419: "\"......It seems the hazard level has advanced to X2.\"",
154420: "\"What does that mean?\"",
154421: "\"It means Hinamizawa Syndrome has spread to Shishibone City. The city is now quarantined from the outside, and all the bridges should be blocked off. ......Here's hoping Tokyo can do something in the meantime.\"",
154422: "\"Is there nothing we can do but wait?\"",
154423: "\"Unfortunately, waiting isn't an option. ......We can't leave Takano-san at large.\"",
154424: "She had said:",
154425: "A devil trying to destroy humanity has appeared.",
154426: "I'm going to Okinomiya. That's where it is, isn't it......?",
154427: "\"I don't know what she means by a devil, but...\"",
154428: "\"......We can't afford to let her run rampant any longer.\"",
154429: "\"Precisely. ......Takano-san is most likely still within the city.\"",
154430: "\"Since all the bridges are blocked off, Takano can't get out either.\"",
154431: "\"If she means to spread η173 beyond the city, she must be stopped at any cost. She should be in Okinomiya.\"",
154432: "\"Tomitake. I'll help too.\"",
154433: "\"It's dangerous. You should stay hidden here.\"",
154434: "\"Even for you, Okinomiya is dangerous right now, Tomitake.\"",
154435: "\"There are many young people in Okinomiya...... Those who have surrendered their hearts to the demon will be far more dangerous.\"",
154436: "\"I'm the queen carrier. I should have the power to calm nearby infected, if I recall.\"",
154437: "\"......Now that you mention it, that's right. ...............\"",
154438: "\"Playing the gentleman toward me is less important than capturing Takano and stopping further harm.\"",
154439: "\"But if anything were to happen to you......\"",
154440: "\"The worst has already happened. Even if I were to die now, things couldn't get any worse.\"",
154441: "Protecting Rika from harm had been their entire purpose — to prevent exactly this kind of situation.",
154442: "But the mass L5 outbreak, the worst-case scenario, had already occurred without her dying.",
154443: "......He had to admit she had a point. Logically, things truly couldn't get worse.",
154444: "And yet, if Takano were left unchecked, there was the very real possibility of something even worse.",
154445: "She could spread Hinamizawa Syndrome across all of Japan...",
154446: "Or she could be stopped by whatever she called a \"devil.\"",
154447: "\"If she's calling something a devil...... then the enemy of our enemy is our ally.\"",
154448: "\"......You have a point there. Alright then. We don't have time for debate.\"",
154449: "\"Don't stop me, Hanyuu. This is for the sake of the world too, you know?\"",
154450: "\"Au, au...... It really looks like you're enjoying this......\"",
154451: "\"Let's move. We're going to find Takano-san!\"",
154452: "Tomitake borrowed a car from the clinic.",
154453: "In a world resembling a zombie apocalypse, a car was as good as a mobile shelter — as long as no zombies spontaneously materialized in the back seat.",
154454: "The car was headed toward Okinomiya.",
154455: "Rika and Hanyuu relaxed in the back seat......",
154456: "\"I was planning to wait things out quietly in Hinamizawa, but I've changed my mind. ......I can't stand back and let Takano have her way.\"",
154457: "\"But what could this 'devil' she speaks of be......?\"",
154458: "\"Hard to say. Maybe someone like us.\"",
154459: "\"..............................\"",
154460: "\"Hanyuu?\"",
154461: "\".........Yes. ......It appears to be someone like us.\"",
154462: "\"Huh?\"",
154463: "They should have been inside the car, yet...... there was a sudden sensation, as though their very souls were floating free of their bodies.",
154464: "Before they knew it, Rika and Hanyuu found themselves in a strange, dreamlike world.",
154465: "What was happening? Yet this feeling......",
154466: "Hanyuu's expression had grown solemn — the way it did when she spoke of things a thousand years past......",
154467: "At that moment, something like drifting mist gathered and took on a human shape......",
154468: "\"W-What? Who......\"",
154469: "\"......Someone I had hoped never to meet again.\"",
154470: "Even Rika, the hundred-years witch, found herself at a loss.",
154471: "It was not the sort of words she had ever heard from Hanyuu before.",
154472: "Someone Hanyuu never wanted to see again......",
154473: "The misty human shape...... was human in form, yet entirely inhuman in nature.",
154474: "\"......To think we should meet once more. Tamurahime-no-Mikoto......\"",
154475: "\"Hanyuu, leader of the horned people...... I too had no wish to meet with you again.\"",
154476: "\"I could say the same to you. ......Why must I encounter you like this again......?\"",
154477: "\"......You're showing open hostility — that's not like you.\"",
154478: "\"She is an enemy who refuses to acknowledge our existence. Do not let down your guard.\"",
154479: "\"So monsters can despise their own kind too.\"",
154480: "\"I will not tolerate being lumped in with that demon who cannot even hide her horns. Know your place, priestess of the horned people.\"",
154481: "A single sharp glance from her sent a jolt of pain through Rika's head.",
154482: "Her frozen eyes carried not only supernatural force, but a rejection and contempt so intense it was physically painful......",
154483: "......Thinking back, Rika had always been the object of reverence.",
154484: "No matter how many hundreds of deaths she had endured, or however long she had lived...... not once had she been subjected to such a gaze.",
154485: "Rika swallowed hard in the face of this unfamiliar feeling......",
154486: "\"Hanyuu. ......Do you know why I have shown myself?\"",
154487: "\"...........................\"",
154488: "\"What do you make of this disaster below?\"",
154489: "Slowly, the mist at their feet cleared.",
154490: "Rika finally understood. They weren't standing in mist — they were inside a cloud.",
154491: "Below spread a view as if glimpsed from an airplane.",
154492: "Without even straining her eyes, she could tell the city below was Okinomiya......",
154493: "Black smoke rose from all over the city, and a dark haze hung low over it.",
154494: "If she looked harder she could see the people in the streets — those who had surrendered their hearts to the demon — cutting each other down......",
154495: "\"What a wretched sight...... Tremble before the weight of your own sin. All of this is the work of your people. Know shame, leader of the horned people.\"",
154496: "\"............!.........\"",
154497: "From the perspective of humans like Rika, Takano was the one at fault.",
154498: "But from the perspective of inhuman beings like Hanyuu...... the disaster below was entirely Hanyuu's doing.",
154499: "Because η173 was Hanyuu. η173 was the horned people.",
154500: "Hanyuu bit her lower lip, unable to argue back.",
154501: "Takano had conducted research to turn the horned people ferocious.",
154502: "That was not Hanyuu's fault. And yet — beings such as these would never permit the sin to be transferred to a human.",
154503: "\"......That responsibility...... we shall take with our own hands.\"",
154504: "\"You shall not. That is unnecessary. Know that your tainted horned people will not be permitted to despoil our lands any further.\"",
154505: "\"That's quite the thing to say, coming from someone who's as much of a monster.\"",
154506: "\"Silence. Know your place, child of man. You are nothing more than the priestess of the tainted horned people.\"",
154507: "\"Kh......\"",
154508: "Tamurahime-no-Mikoto cast a single glance at Rika, and pain shot through her head again.",
154509: "There was no doubt she was the same kind of being as Hanyuu — yet it was equally clear that the two were utterly incompatible.",
154510: "\"I never wish to speak with you again. ......The tragedy wrought by the horned people — I, their leader, and my priestess shall bring it to an end with our own hands.\"",
154511: "\"You shall not. Return home, tainted ones. The disaster visited upon my people's lands is for me to resolve, and I alone. You should slink back to Hinamizawa and bow your head in shame for your immature charges! Begone, Hanyuu and priestess!\"",
154512: "A violent shock shook her body — and the very next moment she was back in the swaying rear seat of the car.",
154513: "Like a waking dream. Yet undeniably real for both of them.",
154514: "A cold reunion between inhuman beings, across centuries — or perhaps longer.",
154515: "\"......Who in the world was that?\"",
154516: "\"Tamurahime-no-Mikoto. ......The leader of the original inhabitants, who ruled these lands long before we ever arrived.\"",
154517: "\"I see. No wonder you never got along.\"",
154518: "\"For those who had wandered, finding land at last was an irreplaceable blessing — a miracle. ......Yet Tamura gave us only cold rejection.\"",
154519: "That was a truth recorded nowhere — not even in the most ancient texts kept within the ritual storehouse. ......The oldest of all myths, known only to Hanyuu.",
154520: "\"We wandered space for a long time, searching for a place to call home. ......After a journey so long it nearly drove us mad, we finally found this beautiful blue planet.\"",
154521: "\"......Just what exactly are you all? ......I've always wondered. You're certainly not some abstract being called a god. You're something that Irie and the others could study under a microscope — something that genuinely exists, aren't you?\"",
154522: "The Hinamizawa Syndrome was caused by a virus. And there was no way a virus could have a will......",
154523: "And yet that was apparently the true identity of Hanyuu's so-called horned people.",
154524: "And Rika's guess was correct.",
154525: "There is a line of science fiction reasoning that humans are merely parasites upon the Earth.",
154526: "In that sense, the horned people are no different from humans.",
154527: "Humans are parasites upon the Earth. And they are parasites upon the human brain.",
154528: "To the horned people, the human brain is their ground.",
154529: "And if humans destroy the environment, they will eventually kill the Earth, taking everything that lives upon it with them.",
154530: "That is why humanity must be kind to the Earth and strive to coexist with it.",
154531: "The same is true for the horned people.",
154532: "If they cannot coexist with humanity, they cannot survive either.",
154533: "......In that analogy, Hinamizawa Syndrome is their destruction of the environment.",
154534: "When a human falls into paranoid madness and hurts themselves, turns violent, or takes their own life — the horned people perish alongside them.",
154535: "Once her thoughts reached that point, the parting insult Tamura had left behind — calling them immature — began to make a little more sense.",
154536: "......Tamurahime-no-Mikoto, too, was likely the leader of a supernatural entity that parasitized humans.",
154537: "Yet aside from the Hinamizawa Syndrome, no such strange symptoms had been reported anywhere in Japan.",
154538: "Which meant Tamura's people had found a way to coexist peacefully with humanity.",
154539: "Hanyuu's horned people, however, had yet to find that way. ......That was why they were called immature.",
154540: "Still, there was a counterargument to be made from this side.",
154541: "Certainly, there had been an incident in ancient Onigafuchi Village long ago.",
154542: "Yet they had overcome it over the centuries, developing unique customs to keep themselves in check so that symptoms would not emerge.",
154543: "And then a villain like Takano came along and deliberately began research to make them more ferocious.",
154544: "This incident in Hinamizawa was not caused by Hanyuu and the horned people.",
154545: "It had to have been triggered by the new strain of η173 that Takano and the others had developed — a ferocious variant — leaking out.",
154546: "\"That stiff-necked monster doesn't look capable of understanding any of that.\"",
154547: "\"She never listens to anyone. She's utterly cold and completely inflexible.\"",
154548: "\"True. But the one thing we can be certain of is that if we let her have her way, this disaster will spread across all of Japan — across the whole world.\"",
154549: "\"If that happens, I wonder — will self-proclaimed god-monsters from all over the world come to lay into you?\"",
154550: "\"......Au, au, au.\"",
154551: "\"Takano raving about wanting to become a god. And then you with your Tamurahime-no-Mikoto. ......I see now. This is no longer a problem the human world can handle on its own.\"",
154552: "Most likely...... if Hanyuu is to be called a god, then a disturbance was taking place in the realm of gods.",
154553: "Humans were merely caught up in it.",
154554: "......The more she thought about it, the more certain she became: we are the only ones who can stop this.",
}

with open('kamikashimashi_3.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for entry in data:
    if entry.get('type') not in ('MSGSET', 'LOGSET'):
        continue
    mid = entry.get('MessageID')
    if 'TextENGNew' in entry:
        continue
    if mid in translations:
        entry['TextENGNew'] = translations[mid]
        count += 1
    else:
        print(f"WARNING: No translation for MessageID {mid}")

with open('kamikashimashi_3.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {count} TextENGNew entries to kamikashimashi_3.json")
