#!/usr/bin/env python3
"""
Tsumihoroboshi-hen translation script.
Adds TextENGNew to each MSGSET/LOGSET entry.
"""

import json
import re
import sys

def strip_tags(text):
    """Remove game engine tags, preserve \\n."""
    # Ruby/furigana: @bREADING.@<KANJI@> -> KANJI
    text = re.sub(r'@b[^.]*\.@<([^>]*)@>', r'\1', text)
    # Voice tags
    text = re.sub(r'@v[A-Za-z0-9/_|]+\.', '', text)
    # Wait/other numeric tags
    text = re.sub(r'@w\d+\.', '', text)
    text = re.sub(r'@o\d+\.', '', text)
    # Click wait, return, pipe, misc
    text = re.sub(r'@[krb|y]', '', text)
    # Remaining @ tags
    text = re.sub(r'@[A-Za-z][A-Za-z0-9_/|]*\.?', '', text)
    return text.strip()


# ============================================================
# TRANSLATIONS — keyed by MessageID
# ============================================================
TRANSLATIONS = {

# ============ FILE 01 ============
81408: "…Before I knew it, the cicadas had yielded their chorus to the higurashi.",
81409: "That chorus welled up from far away, swelled, then faded—swelled, then faded. It was so fragile, so ephemeral.",
81410: "And Rena's voice was much the same—like the higurashi's cry, it rose and then dissolved, rose and dissolved.",
81411: "…She seemed so fragile that I feared the slightest distraction might cause even her presence to vanish into the air.",
81412: "But no one rushed her.",
81413: "Mion dusted off the hood of an abandoned car and settled onto it, striking a posture that broadcast her ease.",
81414: "Her expression was soft, as though she had always intended to come here for a quiet evening in the cool air.",
81415: "Watching her, Satoko found her own spot and sat down as well.",
81416: "Satoko, however, didn't look nearly as relaxed.",
81417: "I thought about following suit, but even the few seconds it would take to search for somewhere to sit felt like a rudeness toward Rena, so I stayed standing.",
81418: "Rika-chan didn't sit either.",
81419: "She wasn't looking at Rena.",
81420: "Everyone else had their eyes on Rena—but Rika-chan alone looked up, filling her gaze with the high sky that was just beginning to blush with crimson.",
81421: "Her expression was… difficult to describe.",
81422: "It was utterly desolate—as though every shade of joy and anger, sorrow and pleasure had been drained away, leaving only what remained afterward.",
81423: "And of all of us, that expression most closely resembled Rena's.",
81424: "Rena kept trying to form words, only to have them catch in her throat again and again.",
81425: "…When she noticed Rika-chan gazing at the sky, she tilted her own face upward and let the wide heavens fill her eyes.",
81426: "Seeing that, Mion looked up too.",
81427: "…And I did as well.",
81428: "Satoko followed everyone's lead and looked up.",
81429: "And then—silence.",
81430: "We stood inside a concert hall filled by nothing but the higurashi's chorus—the concert hall with the highest ceiling in the world.",
81431: "…A cool breeze drifted through and tickled the faint sweat the day's heat had drawn out. It felt wonderful.",
81432: "Standing like this, I almost let myself believe we had all gathered here simply to enjoy a pleasant evening breeze.",
81433: "More than that—I wanted to suggest we pretend that, even now.",
81434: "Only the shadows of birds crossing the sky occasionally marred our quiet concert with their gracelessness.",
81435: "…Because each time I became aware of a bird in flight, I was reminded that time had not stopped.",
81436: "None of us wanted to hurry Rena.",
81437: "And so we could not even allow the ticking of the clock to rush her.",
81438: "We wanted to hold that cool, evening sky in place—suspended in endless time—until Rena could settle her heart and speak.",
81439: "Just then, a dull, hollow thunk brought us back to reality.",
81440: "Mion had shifted her legs, and the hood she was sitting on had made the sound.",
81441: "Whether she'd done it on purpose or by accident I couldn't say—but that sound, cruelly, reminded us that time had been passing all along.",
81442: "The graceless noise drew our gazes from the sky and returned them to earth.",
81443: "That inelegant sound seemed to have given Rena the push she needed to summon her resolve.",
81444: "Rena let out a small breath, bowed her head slightly as if swallowing something, and then looked up at us with the expression we all knew so well.",
81445: "\"…Before I start, there's… one thing I want to say.\"",
81446: "She was probably saying it to everyone, but since she was looking at me—standing at the center of the group—I nodded on everyone's behalf.",
81447: "\"…I believe I tried my best, in my own way.\"",
81448: "Her voice was no longer ragged.",
81449: "It held the same quiet clarity it always did—the same composure.",
81450: "\"I wonder… how much effort a person is allowed to make in order to be happy…\"",
81451: "It sounded like a question, but no one answered.",
81452: "\"That's why I love Mii-chan's club. The idea that you do absolutely whatever it takes to win—I think that's beautiful.\"",
81453: "\"…Because if the world only allowed you to fight by the rules—if there were a strict limit on the kind of effort you could make—then people who aren't happy would never be able to win happiness at all, would they?\"",
81454: "\"Misfortune is something that chains together, I think. Once it begins, it's very hard to escape. And luck or someone else's help—neither of those alone is anywhere near enough to break free.\"",
81455: "\"I think you have to struggle yourself—more and more, with everything you have. I believe that's the only way to finally grasp… something like happiness.\"",
81456: "Rena paused there, looked up at the sky, took a breath, and opened her mouth again.",
81457: "\"But… I don't expect you to accept what I did, either.\"",
81458: "\"…Because it really was filthy. You were all just now—stunned, weren't you? That says everything…\"",
81459: "I hadn't known Rena was capable of smiling like that—so full of self-contempt.",
81460: "That smile was painful to look at beyond belief.",
81461: "…And it made me feel a distance that had no right to exist.",
81462: "There was nothing between us—no barrier of any kind—and yet it felt as though she were speaking to us through iron bars, or chain-link fencing. That's how vast the gulf was.",
81463: "\"…But that's fine. There's nothing to be done about it. That's just how the world is made.\"",
81464: "\"If I were the one in your position… I'm sure I would have looked just as stunned, and said something irresponsible, something without mercy.\"",
81465: "Those words were probably Rena's only counterattack against us.",
81466: "We were spectators wearing sympathy like a mask, watching a clown perform on a stage and calling it someone else's problem. That single remark was her only riposte.",
81467: "I wonder if she expected one of us to say something back.",
81468: "…Of course, not one of us could find a word to offer.",
81469: "Rena looked disappointed for just a moment—and then, with effortless lightness, she climbed atop an abandoned car and stepped onto the roof as though it were a stage.",
81470: "She spread both arms wide, spun lightly so her skirt swirled out around her, then caught its hem between her fingertips and gave us an elegant, theatrical bow.",
81471: "\"Well then… I'll begin. The story of Ryuugu Rena's one great endeavor.\"",
81472: "There was no curtain, and no spotlight.",
81473: "Her stage was the roof of a wrecked car amid the trash heaps.",
81474: "We resolved to miss not a single word of whatever she was about to say.",
81475: "That was the one thing we could do—the one thing we believed could not hurt her.",

# ============ FILE 02 ============
81476: "Say, for example, it's December—winter by the calendar.",
81477: "What would you do if hot, muggy days with shrieking cicadas went on day after day?",
81478: "Would you still faithfully go about your life in coat and muffler?",
81479: "Of course not.",
81480: "So even though it's June, after this many blazing hot days—as far as we're concerned, it's summer!",
81481: "And if we're doing club activities in this heat, then a game like this is perfectly fair!",
81482: "At our school, everyone does as they please in PE, but today was an exception—every classmate had assembled in the schoolyard.",
81483: "Once she confirmed the full turnout, Mion raised her voice.",
81484: "\"All right, everyone—do we know what today is about?!\"",
81485: "\"YEAHHHHH!!!!\"",
81486: "Every outstretched hand held a water gun.",
81487: "After this many sweltering days, water guns in June are perfectly acceptable!",
81488: "Besides, when the whole class joins in a firefight, getting excited is the only natural response!",
81489: "\"It does get one worked up, doesn't it—having club activities with the whole class!\"",
81490: "\"It does! Getting to run around outside with everyone feels wonderfully fun, it does!\"",
81491: "\"…It is fun for everyone else, but for those of us involved, we, as always, cannot afford to lose.\"",
81492: "\"Well, that's the shape of it! When there's anything called a competition, we club members are always carrying a certain risk.\"",
81493: "\"Hehehe! Exactly!\"",
81494: "\"Club members, if you're careless enough to lose, there'll be quite a severe penalty waiting for you. Fight hard, each and every one!\"",
81495: "\"Right, spirits are running high!! Attention, all combatants—are your weapons ready?! Magazines fully loaded?!\"",
81496: "\"Leave it to us, Maebara-san! Water-gun combat is our greatest specialty!\"",
81497: "\"…Tomita and the others play with water guns all the time, so they'll be formidable opponents.\"",
81498: "\"Hehehehe! Today we're a little different than usual!\"",
81499: "Tomita and Okamura exchanged confident grins—unusually assured for them—and raised their water guns with practiced ease.",
81500: "You could see it in their faces: real skill had become real confidence, and that confidence had changed their very expressions!",
81501: "\"Mion goes without saying, but Satoko and Rika-chan both look like serious threats… Rena, what about you?! Try not to get picked off first by darting around too much!! Come to think of it, Rena's been a regular at the penalty game lately.\"",
81502: "\"Hau… W-well, there've been a lot of games I'm not good at lately… B-but I think Keiichi-kun has been just as frequent a penalty-game guest as I have.\"",
81503: "\"Hahahahaha!! Try walking home in your penalty-game getup and getting caught by your mother before you can change—then you can talk about pathos! Ughhh!!\"",
81504: "\"W-well, last week's was just awful for me too—a normal girl might never be able to find a husband after that!!\"",
81505: "The two of us—recent regulars at the loser's end—shuddered in tandem remembering each other's spectacular punishments, and Satoko's high-pitched laugh rang out at our expense.",
81506: "\"Ohohoho! Aren't the two of you adorable? Well, if you don't want the next round of penalties, you'd better win, hadn't you?\"",
81507: "\"Ahh, well, if you put it that way! Rena and Keiichi-kun, let's make sure to at least not end up in last place today!\"",
81508: "\"Yeah, at the very least, let's keep our dignity!\"",
81509: "\"Hehehehe! If you're good, maybe I'll go easy on you with the penalty game!\"",
81510: "\"Now that's a suspiciously generous offer…\"",
81511: "\"Well, the penalty game has to be something everyone can enjoy, too.\"",
81512: "Rena and I exchanged a glance and were quietly impressed: this club leader of ours was already thinking about the post-game entertainment.",
81513: "\"Okay! We're beginning now!!\"",
81514: "The opening gun: Mion's signal shot straight into the air.",
81515: "\"This way, Keiichi-kun! Let's split up and head to different corners!\"",
81516: "\"Right! But where—\"",
81517: "Before I could finish, Rena had darted away at a speed that made it look as though she'd teleported. For someone whose first impression was always \"sweet girl,\" the tactical genius inside her was terrifying.",
81518: "I pelted across the schoolyard, making use of every bit of cover I could find.",
81519: "You wouldn't think a school playground had much in the way of obstacles—but the equipment and shrubbery gave enough for a quick runner to work with.",
81520: "\"Haaaaah!!\"",
81521: "\"Gyaah!\"",
81522: "As I dove behind the equipment shed, a volley caught me in the shoulder.",
81523: "I turned to see who had gotten me: Tomita, wearing a face of total confidence, gesturing me out.",
81524: "\"You're out, Maebara-san! A direct hit to the shoulder!\"",
81525: "\"Damn! You've gotten better, Tomita!\"",
81526: "\"Hehehe, that's what I've been saying! We're different today!\"",
81527: "Still, a shoulder hit isn't a kill shot in our rules. Wounded, but still fighting.",
81528: "\"Keiichi-kun, over here—!\"",
81529: "From behind the climbing frame, Rena was waving me over in a low crouch.",
81530: "I rushed over, ducked down beside her, and assessed the situation.",
81531: "\"Still alive?\"",
81532: "\"I took a shoulder. But I can still fight.\"",
81533: "\"Understood. Here's what we'll do.\"",
81534: "Rena's clear eyes swept the whole schoolyard with uncanny calm, mapping out the terrain. I realized she had already read the entire field of battle.",
81535: "\"Mion's covering the main open ground. Satoko and Rika-chan have split up to take the flanks. Tomita and Okamura have very good coordinated fire.\"",
81536: "\"So we're surrounded?\"",
81537: "\"Yes. So—we cooperate with Tomita-kun and Okamura-kun to take down the others first.\"",
81538: "\"They've been shooting at us—\"",
81539: "\"The battlefield changes. If we can get the others to scatter, the two of us can deal with Tomita-kun and Okamura-kun easily enough after that. What do you think?\"",
81540: "\"…Sounds solid.\"",
81541: "Rena's plan was simple and clean. When you can't fight everyone at once, you prioritize your targets and take them in order. It was the right call.",
81542: "\"I'll draw Tomita-kun's attention. Keiichi-kun, you circle around behind and neutralize him.\"",
81543: "\"Understood. What about Okamura?\"",
81544: "\"I'll handle that after.\"",
81545: "\"Roger.\"",
81546: "We exchanged a quick look, and then moved.",
81547: "Rena's role was to draw fire. She ran out in front of Tomita—openly, conspicuously—giving him every reason to shoot.",
81548: "Tomita fell for it completely. He leveled his water gun at her.",
81549: "And that was his mistake.",
81550: "I had already flanked around behind him. The moment he pointed at Rena—",
81551: "\"Tomita, you're done.\"",
81552: "\"Wha—!\"",
81553: "Point-blank, I hit him square in the back.",
81554: "\"Aghh!! W-when did you get behind me?!\"",
81555: "\"While you were too busy watching Rena. She drew your attention and I slipped around.\"",
81556: "\"That's… that's just cowardly…!\"",
81557: "\"Mii-chan always says: do whatever it takes to win!\"",
81558: "\"Keiichi-kun~! Okamura-kun is making a run for it~!\"",
81559: "\"On it!\"",
81560: "I spun around. Okamura, seeing Tomita go down, had broken for the open ground.",
81561: "This was Rena's moment.",
81562: "\"Hau—you can't escape~☆\"",
81563: "Rena's water gun delivered a flawless hit to Okamura's back as he fled.",
81564: "\"Waaah!! W-why is Rena-san so fast?!\"",
81565: "\"Ehehe~☆\"",
81566: "With Tomita and Okamura neutralized, we had broken the enemy's coordination.",
81567: "Now it was two versus four—but we had the initiative.",
81568: "\"Keiichi-kun! Mion-chan is coming!\"",
81569: "\"Damn, already—!\"",
81570: "Mion charged at us with extraordinary speed, water gun raised.",
81571: "But Rena showed no sign of fear. She stood and faced her.",
81572: "\"Mii-chan, this is for the Tanabata penalty game!\"",
81573: "\"Ha! As if that's a motivation!\"",
81574: "The two of them squared off at close range, both shooting simultaneously.",
81575: "A direct exchange. A mutual hit.",
81576: "\"…Both out?\"",
81577: "\"Looks like.\"",
81578: "Under our rules, a mutual hit counted as mutual elimination.",
81579: "Mion crossed her arms and laughed. \"Ha! A draw? Not bad, Rena!\"",
81580: "\"Ehehe, we both lost~\"",
81581: "Rena laughed with her—no bitterness in it.",
81582: "\"Keiichi-kun, I'm eliminated. The rest is up to you.\"",
81583: "\"Me against Satoko and Rika-chan?! That's a tough ask!\"",
81584: "\"Do your best! Ehehe~☆\"",
81585: "…The cheerfulness with which she said that felt slightly ominous.",
81586: "\"Now then, how do I handle Satoko and Rika-chan…\"",
81587: "I surveyed the field again.",
81588: "Satoko and Rika-chan were small and quick—difficult targets. And their coordination, honed by regular club activities, was not something to take lightly.",
81589: "I needed a plan.",
81590: "\"Satoko!\"",
81591: "I called out to draw her attention.",
81592: "\"What is it?\"",
81593: "Satoko showed herself—and Rika-chan flanked in from the side, simultaneously.",
81594: "\"—Hah!\"",
81595: "\"Gyaaah!\"",
81596: "Both of them had been moving in perfect coordination.",
81597: "Satoko's shot hit my torso. I got one arm.",
81598: "\"Keiichi-san, you are eliminated!\"",
81599: "\"Nooo! I let Satoko get me again…!\"",
81600: "\"Ohohoho! All's fair in love and club activities, isn't it, Keiichi-san?\"",
81601: "\"And so the final two standing are—Satoko and Rika-chan! Ahh, this calls for a penalty!\"",
81602: "Mion announced the results to the whole class.",
81603: "Cheers and groans rose together from the assembled students.",
81604: "\"Well, the big loser today is… Keiichi!\"",
81605: "\"Me?! Why me specifically?!\"",
81606: "\"Because the more times you end up in the penalty seat, the better everyone else's morale gets! And morale matters!\"",
81607: "\"What kind of logic is that?!\"",
81608: "Rena covered her mouth and laughed quietly. \"It's all right, Keiichi-kun. I ended up there too, after all.\"",
81609: "\"…That's true, but knowing we suffered together doesn't exactly help!\"",
81610: "\"Ohohoho! And so we arrive at the penalty game!\"",
81611: "Satoko laughed with perfect timing, adding to the torment.",
81612: "…And so the water-gun showdown of the combined school-and-club activity came to its close—with Satoko and Rika-chan triumphant, and Keiichi and Rena in the penalty seats, as per usual.",
81613: "\"All right, penalty game time! Keiichi, Rena—over here!\"",
81614: "We shuffled over to the designated spot as the whole class gathered to watch.",
81615: "\"Today's penalty game is… this!\"",
81616: "Mion produced something from behind her with a dramatic flourish.",
81617: "\"…What is that?\"",
81618: "\"A super-size parfait challenge! Both of you finish one of these in thirty minutes, and you're off the hook!\"",
81619: "\"A parfait?! That's not a penalty, that's a treat!\"",
81620: "\"Ahaha, well, just wait until you see the size of it.\"",
81621: "The parfait that was set in front of us was… enormous.",
81622: "Rena and I stared at it in silence for a long moment.",
81623: "\"…I-it's really that big?\"",
81624: "\"Ehehe, it's so wonderful! I want to eat it, I do~!\"",
81625: "\"Rena… you're really fine with this?\"",
81626: "\"Hau~, sweet things are Rena's specialty~!\"",
81627: "…She was practically sparkling. Meanwhile, I was quietly horrified.",
81628: "\"Begin!\"",
81629: "And we dove in.",
81630: "The class watched us struggle, cheering and laughing in equal measure.",
81631: "The first ten minutes were fine. The next ten were a challenge.",
81632: "The final ten were suffering.",
81633: "\"…Finished…\"",
81634: "Rena set down her spoon first, clean bowl in front of her. She looked perfectly content.",
81635: "\"Hau~, it was delicious~☆\"",
81636: "\"How… how are you all right after that…\"",
81637: "\"Keiichi-kun, you're not done yet! You have four minutes left!\"",
81638: "\"I know that! I know, but—ughhh…\"",
81639: "I stared into the bottom of my glass—still more than a quarter full—and summoned my will.",
81640: "\"…I…I can do this…\"",
81641: "I ate it.",
81642: "All of it.",
81643: "\"Done!\"",
81644: "The class erupted.",
81645: "\"Keiichi-san, you did it! And with eleven seconds to spare!\"",
81646: "\"…I feel sick…\"",
81647: "\"Keiichi-kun, good work~!\"",
81648: "Rena reached out and patted me on the back. I had never been so grateful for human contact.",
81649: "\"The penalty game is over! Keiichi and Rena, you're both cleared!\"",
81650: "\"Ahhh, thank goodness…\"",
81651: "\"Ehehe, let's do club activities again tomorrow~!\"",
81652: "\"Rena… you have unbelievable stamina…\"",
81653: "\"Ahaha~☆\"",
81654: "Rena laughed, bright and clear, and the whole class joined in.",
81655: "That was how our water-gun showdown came to its end.",
81656: "…Later, I would think back on that afternoon—the laughter, the running, the absurdly large parfait—and feel the particular ache of something precious that cannot be reclaimed.",
81657: "But in that moment, standing drenched and sugar-sick in the schoolyard sunshine, all I felt was contentment.",
81658: "That's how it was, in those days.",
81659: "Those were the club days I can never forget.",
81660: "\"Now! Shall we head to Angel Mort to celebrate our joint activity?!\"",
81661: "\"Heyyy, isn't that a little much after that parfait?!\"",
81662: "\"The stomach has separate rooms! One for meals, one for desserts, and one for Angel Mort!\"",
81663: "\"That's not how stomachs work!!\"",
81664: "\"Mii-chan, Angel Mort sounds wonderful, it does~!\"",
81665: "\"Even after all that parfait, Rena?!\"",
81666: "\"Ahaha~, Rena is completely fine~!\"",
81667: "\"…Rena… you truly are something else…\"",
81668: "\"Ohohoho! Ladies, let's go!\"",
81669: "\"Oh, now that's a cheerful voice!\"",
81670: "\"We're going! We're going!\"",
81671: "\"Keiichi-kun, let's go together!\"",
81672: "\"…Wait up, Rena. I need a minute to just… stand here…\"",
81673: "\"Ahaha, Keiichi-kun really is hopeless~!\"",
81674: "Rena laughed again, took my arm, and pulled me forward.",
81675: "Even now, that feeling—her fingers around my arm—stays with me.",
81676: "And I think: if only I had understood, back then, what she was carrying.",
81677: "If only I had known.",
81678: "That was the last ordinary day—the last of those days that felt, in the moment, like they would simply go on forever.",
81679: "I think about it now and wonder: did Rena know, even then?",
81680: "Did she already know what was coming—already carrying the weight of it—and still laugh, and pull me forward?",
81681: "If so.",
81682: "If that was so—then she was braver than any of us.",
81683: "Much braver than me.",
81684: "And that's why I'm standing here now, listening, not rushing her.",
81685: "That's why I stayed standing—why none of us looked away.",
81686: "\"Well then.\"",
81687: "Mion's voice was low, quiet.",
81688: "\"Should we head to Angel Mort?\"",
81689: "We all agreed—and set off together.",
81690: "That was the last of those days.",
81691: "At least—in Rena's story.",
81692: "The chapter that came next was one she told herself.",
81693: "Standing on a stage of rust and rubbish, in the fading light.",
81694: "\"Well then. Shall I continue?\"",
81695: "She smiled, and looked down at us from her perch.",
81696: "\"We went to Angel Mort after that—me, Keiichi-kun, Mii-chan, Satoko-chan, Rika-chan—\"",
81697: "And so Rena's account went on.",
81698: "And we listened.",
81699: "All of us standing in the same fading light.",
81700: "With no curtain, and no spotlight.",
81701: "Only the higurashi singing.",
81702: "And Rena's voice—rising, then fading, rising, then fading.",
81703: "Just as it had been from the very first.",
81704: "\"…And then, when we got there…\"",
81705: "She took a breath, and went on.",
81706: "We did not move.",
81707: "We did not look away.",
81708: "We listened.",

# ============ FILE 03 ============
81709: "…Even after waking, the excitement still hadn't left me.",
81710: "No doubt about it—I'd been dreaming something wonderfully good.",
81711: "What the dream was about, though, had vanished the instant I opened my eyes, as though waking flipped some switch that erased it.",
81712: "…But that it had been a very happy dream—that much was beyond question.",
81713: "And so I lay there for a while after waking, staring at the ceiling, savoring the afterglow.",
81714: "Today was Sunday.",
81715: "Through the window, the birdsong that filled the morning sounded completely different from the birds on weekdays.",
81716: "Weekday birds always seemed to be in a hurry—their calls had a rushed, scolding quality, as if to say: you're going to be late, hurry up, get to school. But Sunday birds were different.",
81717: "On a morning this clear and beautiful, they sounded as though they simply couldn't hold in the urge to share it with the world—their singing full of a buoyant, irrepressible joy.",
81718: "And that quality made them feel like entirely different birds from the ones that sang on weekdays.",
81719: "Did a special breed of bird exist that only sang on Sunday mornings?",
81720: "A bird whose voice you could only hear once a week would be something of a luxury.",
81721: "And to hear the rare chorus of these precious birds while still half-asleep—that seemed like an extravagant waste.",
81722: "Gradually, as my everyday, rougher self woke up properly, the notion of \"Sunday-only birds\" began to strike me as hilariously absurd.",
81723: "\"…Yaaah… aah…\"",
81724: "A big stretch sent blood rushing pleasantly through my whole body.",
81725: "Rolling over to look at the clock, I saw it was just past ten.",
81726: "Ten on Sunday—that used to be the day I'd head off to cram school.",
81727: "Before we moved to Hinamizawa, of course.",
81728: "Back then I'd been packed off to all sorts of tutoring. The first and third Sundays I remember were the worst—the cram school I went to on those days required so many train transfers.",
81729: "Not that waking at this hour would have been possible back then anyway.",
81730: "Mum would be rushing me out the door, so on Sundays the wake-up time was about the same as weekdays.",
81731: "Maybe that's why being able to wake on a Sunday morning, by my own will, at my own pace, had once given me a certain small, private pleasure.",
81732: "…Though I had probably forgotten that feeling entirely since coming to Hinamizawa.",
81733: "These days, lazing in bed until well past noon on Sundays had become the natural order of things.",
81734: "Since coming to Hinamizawa, I felt like my whole life had changed.",
81735: "Before the move, all I could see were the inconveniences compared to city life—I couldn't honestly summon any enthusiasm for living in the country.",
81736: "But that only lasted the first few days.",
81737: "The grubby convenience of the city held no appeal for me anymore, not compared to the life here.",
81738: "So what was it about this life that appealed? If I thought about it—it was probably the people I'd found here. My friends.",
81739: "My days with Mion, Rena, Rika-chan, and Satoko.",
81740: "No—really, it was their existence itself that had changed everything.",
81741: "Without them, these mountains and forests and rice paddies would probably still feel like \"the countryside I got moved to.\"",
81742: "And though it was already past ten in the morning, there was no one to hurry me. I stretched out in bed and let my mind wander.",
81743: "The afternoon had plans—I was going to Rena's place.",
81744: "There was no particular reason. Just visiting.",
81745: "Rena and I went to school together every morning, so we saw each other every day, but there was something different about spending time at each other's houses.",
81746: "At school you were surrounded by classmates and Mion and Satoko and Rika-chan. Here it was just the two of us.",
81747: "Come to think of it, we almost always went out somewhere—all of us together—and this quiet kind of visiting was actually fairly unusual.",
81748: "Still, it wasn't the first time. A few weeks back I'd dropped by Rena's place after school, and we had spent a few hours together just talking.",
81749: "That had been fun. Easy and unhurried.",
81750: "I was looking forward to today.",
81751: "I stretched one more time, finally sat up in bed, and reached for my phone to check if there were any messages.",
81752: "There was one from Rena.",
81753: "Just: See you later~! ☆ with a little drawing of a cat she'd added.",
81754: "I stared at it for a moment, then smiled to myself.",
81755: "She sent something like this every time we had plans.",
81756: "A small signal. Nothing important. Just—a thread of connection.",
81757: "I typed back: On my way soon. Be there around noon.",
81758: "Sent it, set the phone down, and got out of bed.",

# FILE 03 continued (from entry #22 onward - Keiichi's Sunday morning POV going to Rena's)
81759: "…Might be slightly embarrassing to admit, but this kind of small pleasure—the particular satisfaction of a Sunday morning at one's own pace—had entirely slipped my mind since coming to Hinamizawa.",
81760: "Recently, sleeping lazily until just before noon on Sundays had become completely normal.",
81761: "Coming to Hinamizawa has changed my life entirely, I feel.",
81762: "Before the move, compared to city life, I could only see the inconveniences; honestly, I couldn't work up any enthusiasm for rural life.",
81763: "But truly, that lasted only the first few days.",
81764: "The sooty convenience of the city holds no appeal for me now, compared to life here.",
81765: "So then, what is it about the present life that appeals so much? Thinking about it—it must be largely down to the existence of my friends here.",
81766: "My life here together with Mion, Rena, Rika-chan, and Satoko.",
81767: "No—really, their very existence has changed everything.",
81768: "If not for them, these mountains and rivers and rice paddies would surely still feel like nothing more than \"the countryside I got transferred to.\"",
81769: "And even though it was already past ten in the morning, with no one to rush me I could still be sprawled in bed, letting my mind wander this way and that.",
81770: "This afternoon I was going to Rena's house.",
81771: "Not for any particular reason. Just paying a visit.",
81772: "Rena and I walked to school together every morning, so we saw each other every day—but there was something different about the time the two of us spent just the two of us.",
81773: "At school there were always classmates around, and Mion and Satoko and Rika-chan nearby. Here it was just us.",
81774: "Now that I thought about it, we almost always went out together as a group, so this quiet kind of visit was actually rather unusual.",
81775: "Still, it wasn't the first time. A few weeks ago I'd dropped in after school, and we spent a pleasant few hours just talking.",
81776: "That had been good. Easy and unhurried.",
81777: "I was looking forward to today.",
81778: "\"Keiichi! Breakfast!\"",
81779: "My mother's voice floated up from downstairs.",
81780: "\"Coming!\"",
81781: "I answered, got out of bed, and headed downstairs in the direction of the smell of miso soup.",

# ============ FILE 04 ============
# Angel Mort visit and Rena's internal monologue about her family situation
81782: "\"Welcome to Angel Mort. Tonight is an event evening—do you have your tickets?\"",
81783: "\"Ah, we don't have tickets—but we were told we could give our names. Ryuugu Rena and Maebara Keiichi.\"",
81784: "\"I'm checking our list now. One moment, please.\"",
81785: "The core fans of this place tended to be a fairly questionable lot.",
81786: "Fake tickets and forgeries must be rampant.",
81787: "Remembering the intensity of the crowd outside, this level of caution made sense.",
81788: "\"Still, that was a frightening bunch out there. Regular customers don't stand a chance of making it inside with that lot blocking the door.\"",
81789: "\"Ahahahahaha, it was something, wasn't it.\"",
81790: "\"But nobody can stop Rena when she's set on bringing something home~, hau~☆\"",
81791: "\"Speaking of which—same as ever, your precision. Was that an elbow? A knee? Hitting pressure points in the face with that accuracy is… terrifying.\"",
81792: "The sight of Rena scything through the mob that had swarmed toward her—that perception-defying high-speed jab of hers taking them down one after another—had been nothing short of staggering.",
81793: "Just thinking about it still made me shudder.",
81794: "\"Because they were getting in the way of Rena's take-home~☆ They're all so cute, I want to bring them all home~!!\"",
81795: "\"…Given that it was Rena in 'cute mode' that laid them all out flat, I suppose they at least had the comfort of an overwhelming defeat they could accept with dignity.\"",
81796: "\"You were amazing too, Keiichi-kun? The moment you got surrounded and swallowed by the crowd, suddenly there was silence—and then everyone was standing aside with tears in their eyes. Why was that?\"",
81797: "\"…Well, you see… I told them something to the effect that: you who have been turned away, I will enter on your behalf; I will witness this evening in your stead; therefore, fellow souls, though your tears fall now, strive to be the winning ticket in the next lottery.\"",
81798: "\"…With a few words more or less along those lines, they all seemed to understand.\"",
81799: "\"…Keiichi-kun really is good at that, isn't he. Getting people to agree with you. Sort of—inciting empathy. Yes, you're the Club's silver-tongued orator.\"",
81800: "\"Is that decided now?! Is there no other epithet available to me?!\"",
81801: "\"Ahahaha! I'll think about it!\"",
81802: "Rena laughed her bright laugh and changed the subject.",
81803: "\"Thank you for waiting. I've confirmed your names on the list. I'll show you to your seats—right this way.\"",
81804: "The waitress—dressed in the usual heart-stopping costume—led us to our table.",
81805: "The restaurant was packed beyond capacity this evening.",
81806: "With this many people, the spectacle itself was something.",
81807: "And every single customer appeared to be drawn from the most extremely specialized end of the clientele spectrum.",
81808: "The atmosphere inside was unusual—a peculiar heat in the air, and a faint smell of perspiration.",
81809: "Strange, specialized vocabulary flew back and forth in every direction.",
81810: "\"The uniform is everything at Angel Mort, I daresay!!\"",
81811: "\"Food is tasted with the tongue, to be sure—but at Angel Mort, one tastes with the eyes!!\"",
81812: "\"This is precisely why it cannot be grasped by the uninitiated—it is a sacred place that accepts only the truly awakened!!\"",
81813: "\"Correct! To enter here is to transcend the mundane! We who have gathered here today have surpassed the merely earthly!!\"",
81814: "I exchanged a look with Rena.",
81815: "\"…This is an unusual crowd.\"",
81816: "\"Ahaha, everyone is very enthusiastic~\"",
81817: "\"I'll say. I hope the food is good, at least.\"",
81818: "\"It is! Rena has been here before, and the food is very tasty, it is~!\"",
81819: "\"That's a relief. Let's look at the menu.\"",
81820: "\"This is the special event menu for today. Please take your time!\"",
81821: "The waitress who had just served the next table over brought us menus as well.",
81822: "Printed on the cover of the special event menu was a large, color illustration of all the waitresses in uniform.",
81823: "The whole table beside us went perfectly quiet the moment they received it.",
81824: "\"…They're really into this, aren't they.\"",
81825: "\"They truly love it here~!\"",
81826: "Rena smiled at them warmly.",
81827: "I looked around the restaurant while Rena studied the menu.",
81828: "Almost all the customers appeared to be male. Women were rare.",
81829: "And every single male customer had a special kind of intense focus—the kind that meant they were fully in their element.",
81830: "\"You know, when I'm in a crowd like this, I start to wonder what kind of upbringing leads to this kind of passion.\"",
81831: "\"Ahaha, that's not very nice, Keiichi-kun.\"",
81832: "\"I know, I know. It's not criticism—it's genuine curiosity. People are interesting.\"",
81833: "\"They are! Rena thinks that too~!\"",
81834: "Rena set down her menu and folded her hands on the table.",
81835: "\"Rena has decided. A parfait and an orange juice, please.\"",
81836: "\"I'll go with the pasta special.\"",
81837: "\"Good choice! The pasta here is excellent~\"",
81838: "\"I trust you. You've been here before.\"",
81839: "\"Ehehe~☆\"",
81840: "While waiting for the food, I started telling Rena about Keiichi's morning—about waking up and enjoying the Sunday birds—and she listened with her chin on her hands and her eyes very wide.",
81841: "\"That sounds wonderful~! Rena loves birds~!\"",
81842: "\"You're the kind of person who notices the birds in the morning?\"",
81843: "\"Mm~! The little ones that come to the garden sometimes—Rena puts out food for them~\"",
81844: "\"…I didn't know that.\"",
81845: "\"Ehehe, there are lots of things Keiichi-kun doesn't know about Rena~☆\"",
81846: "She said it with a playful flash of mischief.",
81847: "\"That's probably true. Tell me some of them.\"",
81848: "\"Hmm~ Well—\"",
81849: "Rena thought for a moment.",
81850: "\"Rena is not very good at peeling apples.\"",
81851: "\"That's the first one?\"",
81852: "\"Ahaha! Is it strange?\"",
81853: "\"No, it's just—unexpected. You seem like the kind of person who would peel apples perfectly.\"",
81854: "\"The peel always goes straight, and Rena wants it to spiral~! But it never does~!\"",
81855: "\"Practice?\"",
81856: "\"Rena has practiced! Many times! But still—a straight line~\"",
81857: "We laughed at that.",
81858: "\"What else?\"",
81859: "\"Hmm~… Rena has a scar on her left knee, from when she fell off her bicycle when she was eight.\"",
81860: "\"I see. Another one?\"",
81861: "\"Rena's favorite book is a picture book about a rabbit.\"",
81862: "\"A picture book?\"",
81863: "\"Mm! From when Rena was small. Rena still has it—reads it sometimes~\"",
81864: "\"…That's very you, actually.\"",
81865: "\"Is it~?\"",
81866: "\"Yeah. In a good way.\"",
81867: "Rena smiled—a real one, without performance.",
81868: "The food arrived, and we ate, and talked, and the afternoon stretched on.",
81869: "It was easy. It was good.",
81870: "And I didn't know, sitting there, that the easy days were nearly over.",
81871: "How could I have known?",
81872: "\"Keiichi-kun.\"",
81873: "Rena said my name quietly.",
81874: "\"Hmm?\"",
81875: "\"Nothing. Just—thank you for coming today.\"",
81876: "\"Of course. I always enjoy coming here with you.\"",
81877: "\"Ehehe.\"",
81878: "She smiled and looked out the window.",
81879: "The afternoon light was slanting into gold.",
81880: "I watched her watch the light.",
81881: "And for a moment, the world felt like the kind of thing that could be held.",

# ============ FILE 05 ============
# After the outing—Shion encounter, then the arc shifts
81882: "\"…I don't think I want to see anything sweet for at least three days… Ugghh…\"",
81883: "\"Ahahahahaha, you really did overdo it, Keiichi-kun.\"",
81884: "It struck me as impossible that Rena, who had been blazing through food at that rate, was completely fine.",
81885: "\"Girls must have four stomachs or something… There has to be at least one extra just for desserts…\"",
81886: "\"Such awful things to say about a lady!! For that, Keiichi-san—have this!\"",
81887: "Boing.",
81888: "Satoko poked me in my swollen stomach.",
81889: "\"Gugh!! Stop, stop that!! Don't push on my stomach!! The contents will come out!!\"",
81890: "Satoko and Rika-chan grinned. A chill ran down my spine.",
81891: "Why were they approaching with wiggling fingers and matching smiles?",
81892: "\"Owaaah, stop it, you two—do you have no blood, no tears?!\"",
81893: "\"Ohohoho!! Did you think I would waste a once-in-a-lifetime opportunity?!\"",
81894: "\"…Mi~☆\"",
81895: "\"Keiichi's puffy tummy is in great distress~\"",
81896: "\"Ahahahaha, Keiichi-kun's wobbly-bobbly tummy is so cute~☆\"",
81897: "\"S-stop it, all of you—!!\"",
81898: "\"Wafu, fgyagyaa!!\"",
81899: "Before I knew it Rena had joined Satoko and Rika-chan's mischief, and even after coming out front of Angel Mort we were still horsing around.",
81900: "I was desperately trying to protect my stomach, when someone blindsided me from behind.",
81901: "\"Owaaah!! Wh-who is that?!\"",
81902: "\"Helloooo. Kei-chan and company—good afternoon.\"",
81903: "\"Ah—Shi-chan! Hello~!\"",
81904: "\"Weren't you working today?\"",
81905: "\"I'm on the evening shift. Just got here and changed.\"",
81906: "\"That aside—you can really walk outside in that?\"",
81907: "\"It's not much. Not as embarrassing as a certain someone who was seen parading around the village in their penalty-game outfit.\"",
81908: "…That landed.",
81909: "…Ughhh… I'd just been starting to forget…! Now I'll never be able to find a decent spouse…",
81910: "\"But speaking of which—I hear you all caused quite a scene today?\"",
81911: "\"Ahahahaha, I suppose we did~. Once it became club business, it couldn't be helped!\"",
81912: "Shion looked amused.",
81913: "\"Rena-san, you're amazing—they say you sent fifteen people to the ground?\"",
81914: "\"Hau~, it was only twelve~\"",
81915: "\"Only twelve! That's still terrifying!\"",
81916: "\"Rena was protecting Keiichi-kun and herself, after all~☆\"",
81917: "\"Well, let's leave the battlefield tales for another time. More importantly—there's something I'd like to ask Rena-san, if that's all right?\"",
81918: "Shion's voice shifted slightly. Not alarm—just a drop in register, a new seriousness.",
81919: "\"Of course!\"",
81920: "\"Rena-san, the man who's been visiting your house lately—do you know anything about him?\"",
81921: "Rena's expression didn't change, but something shifted behind her eyes.",
81922: "\"…Which man do you mean?\"",
81923: "\"Tall, thirty-ish, usually dressed well. Drives a gray car.\"",
81924: "\"…Ah. That would be Teppei-san.\"",
81925: "\"Teppei. Is that a surname or a given name?\"",
81926: "\"I only know his given name. He's a friend of a woman named Rena-san's father has been seeing.\"",
81927: "Shion's expression stayed calm, but I could hear her listening harder.",
81928: "\"What does this man do—do you know?\"",
81929: "\"I don't know the details. But… he makes Rena uncomfortable.\"",
81930: "\"Uncomfortable how?\"",
81931: "Rena looked down for a moment.",
81932: "\"He looks at things. At the house, at the rooms. Like he's appraising them.\"",
81933: "\"I see.\"",
81934: "A short silence.",
81935: "\"Rena-san, has anything gone missing from your home recently? Money, valuables, documents—anything like that?\"",
81936: "Rena thought carefully.",
81937: "\"…I don't think so. But I've been watching more carefully lately.\"",
81938: "\"Good. Please keep doing that.\"",
81939: "Shion paused.",
81940: "\"I don't want to alarm you unnecessarily—but I'd keep an eye on this man if I were you.\"",
81941: "\"…You know something about him?\"",
81942: "\"Enough to be cautious. The Sonozaki family hears things.\"",
81943: "\"……I see.\"",
81944: "Rena's voice was very steady.",
81945: "\"Thank you, Shi-chan.\"",
81946: "\"Don't mention it. Just—take care.\"",
81947: "Shion smiled, and her tone lightened again.",
81948: "\"Well! I should get to work before I'm late. Kei-chan, your stomach feeling better?\"",
81949: "\"Not really, no.\"",
81950: "\"Take it easy, then. See you all!\"",
81951: "She waved and walked back into the restaurant.",
81952: "We stood there a moment in the afternoon light.",
81953: "Keiichi looked at Rena.",
81954: "She looked at the middle distance—that same expression she sometimes wore when she was carrying something.",
81955: "\"Rena.\"",
81956: "\"It's fine.\"",
81957: "She looked up and smiled—the ordinary smile.",
81958: "\"Let's head home, shall we~?\"",
81959: "\"Yeah.\"",
81960: "We walked.",
81961: "But the ease of the afternoon had shifted, just slightly.",
81962: "Like a key, turned one notch further in a lock.",

# ============ FILE 06 ============
# Rena's backstory — narrated by Rena
81963: "My mother was a very busy person.",
81964: "She threw herself into her work, earned recognition, and found one new stage after another opening before her.",
81965: "Always climbing, always shining—she was my idol.",
81966: "Originally, my mother was a designer at a small clothing manufacturer in Okinomiya.",
81967: "My father was a designer too.",
81968: "They met at work and married.",
81969: "At first they lived in a small apartment in Okinomiya—but when my mother became pregnant with me, they moved to my grandmother's house in Hinamizawa, the house we live in now.",
81970: "We stayed there until just before I started primary school.",
81971: "Looking back, that was the happiest time.",
81972: "Every day was happiness—and I simply assumed, without question, that tomorrow would be equally happy.",
81973: "Happiness was so constant that there was nothing to notice in it.",
81974: "Those days were happy.",
81975: "I didn't know much at that age, but apparently the company my parents worked for had fallen into financial trouble.",
81976: "In the midst of that, my mother and a handful of the younger designers apparently began talking about breaking away and striking out on their own.",
81977: "…And then things became complicated somehow—and after all that, my mother and the others were apparently absorbed into a much more prestigious design firm in Ibaraki.",
81978: "I heard a lot of words at the time I didn't understand—business tie-ups, strategic alliances—but essentially it meant moving to Ibaraki.",
81979: "Apparently the young designers, including my mother, were greatly anticipated as ready assets at the new firm, with their experience and talent.",
81980: "But my father was not among them.",
81981: "My father, unfortunately, did not have my mother's overflowing talent.",
81982: "And so moving to Ibaraki also meant my father giving up being a designer.",
81983: "My mother had apparently been given important projects at the new firm right from the start, based on how much they were counting on her.",
81984: "She didn't want to let her overflowing talent and passion go cold in a village like this.",
81985: "That was what she said to persuade my father—and my father, partly out of a wish to support my mother flourishing on a larger stage, agreed to resign and make the move.",
81986: "For me at that age, moving meant losing all my close friends.",
81987: "My little self cried and cried, refusing to go.",
81988: "After the move, my mother's projects at the new firm blossomed magnificently.",
81989: "My mother had always had a natural gift for leadership and a vivid, energetic personality—she must have thrived brilliantly in the new environment.",
81990: "She came home late every night, and rest days felt like something that had ceased to exist entirely.",
81991: "Whenever a deadline loomed, she would stay overnight at the office, and it wasn't uncommon.",
81992: "But the mother who came home was always radiantly fulfilled—wearing a smile I had never once seen on her in Hinamizawa.",
81993: "She had married for love—the person she chose above all others—but I wonder whether that was truly the right choice for her.",
81994: "My father was kind, and gentle, and loved both my mother and me.",
81995: "But my mother, I think, had the kind of soul that burned.",
81996: "She needed a stage large enough for it.",
81997: "Without it, she couldn't be herself.",
81998: "And perhaps for my father—patient, kind, gentle my father—loving such a woman was not without its shadows.",
81999: "I was very young, and I don't know what passed between them.",
82000: "I only know that one day, my mother was no longer there.",
82001: "My father explained simply that they had divorced.",
82002: "I cried.",
82003: "For a long time I didn't understand why—only that I cried.",
82004: "Later, older, I would come to understand something.",
82005: "My mother hadn't left because she stopped loving us.",
82006: "She had found a self that could not be contained, and she had chosen it.",
82007: "I don't know if that was right or wrong.",
82008: "But I can no longer hate her for it.",
82009: "My father and I moved back to Hinamizawa—to the house where I had been small, and happy, before anything changed.",
82010: "My father found work. He tried.",
82011: "And I tried too.",
82012: "I tried to be a good daughter.",
82013: "I thought: if I am good enough, if I am enough, my father will not be lonely.",
82014: "And so the two of us—my father and I—made a quiet life in Hinamizawa.",
82015: "It was enough.",
82016: "Or—it was enough, until it wasn't.",
82017: "Until Rena showed up.",
82018: "I mean—until she appeared.",
82019: "The woman named Rena—who later took my name to give to me.",
82020: "She appeared, beautiful and kind, and she smiled at my father, and my father smiled back.",
82021: "And I watched.",
82022: "And I tried to be glad.",
82023: "I told myself: my father deserves happiness. He has been alone. He has been patient.",
82024: "I told myself: this is good.",
82025: "But I couldn't quite make myself believe it.",
82026: "Because behind her kindness—behind that smile—something did not match.",
82027: "I watched, and I waited, and I kept watching.",
82028: "And little by little, the things I saw began to accumulate.",

# ============ FILE 07 ============
82029: "\"Ohh, there she is. Morning, Rena~!\"",
82030: "\"Ahahahaha, Keiichi-kun was here first today.\"",
82031: "\"Normally I wouldn't brag about it—but for me to beat Rena to our morning meeting spot is genuinely rare.\"",
82032: "\"Hau. Rena slept in a little this morning.\"",
82033: "\"Couldn't sleep last night.\"",
82034: "\"Same for me! Nahahahaha, same here actually. The lingering excitement from yesterday's commotion just wouldn't settle. Even in bed I couldn't fall asleep—the night stretched on and on.\"",
82035: "Yesterday we had all made a tremendous racket together, and I'd come home still buzzing with it.",
82036: "My stomach had been too full to eat much of dinner, but I'd spent the whole meal telling my parents about how much fun yesterday and today had been.",
82037: "It had been so fun and exciting that I couldn't sleep—like a kindergartner on Christmas Eve. Honestly, I was embarrassed about myself.",
82038: "\"Ahaha~, it's fine. Rena couldn't sleep either~!\"",
82039: "\"What sort of dreams did you have?\"",
82040: "\"None~! Rena was excited too, so she had trouble falling asleep—and before long it was morning~\"",
82041: "\"So you didn't sleep?!\"",
82042: "\"Just a little~. Ehehe, Rena is fine. One or two hours is enough~\"",
82043: "\"You're amazing… I have to have at least six or I'm useless.\"",
82044: "\"Keiichi-kun needs lots of sleep, doesn't he~\"",
82045: "\"I do. Healthy sleep schedule, that's me.\"",
82046: "\"Ehehe. Rena thinks that's very Keiichi-kun-like~\"",
82047: "We walked to school in the morning sunshine, talking about nothing in particular.",
82048: "The road to school from Keiichi's house, the route he always took—passing the little bridge over the waterway, through the short stretch of cedars, out into the rice paddy path.",
82049: "Rena walked beside him on those wide paths, and they talked.",
82050: "About yesterday. About the game. About Mion's absurd parfait penalty. About Satoko and Rika-chan's coordination. About Shion's appearance at the end.",
82051: "And about nothing in particular.",
82052: "\"Keiichi-kun, do you know what the homework for today was?\"",
82053: "\"The math problems in the back of Chapter Four. Ten of them.\"",
82054: "\"Ah, right. Rena forgot.\"",
82055: "\"Did you do them?\"",
82056: "\"…A little~\"",
82057: "\"Which means not really.\"",
82058: "\"Ahaha~! Keiichi-kun, you're sharp today~\"",
82059: "\"I can show you the answers at lunch if you need.\"",
82060: "\"Eh, really?! Keiichi-kun is so kind~!\"",
82061: "\"Don't tell Mion. She'll make it into a club activity.\"",
82062: "\"Ahaha, you're right~!\"",
82063: "They walked.",
82064: "The cedars filtered the morning light into long thin stripes across the path.",
82065: "Rena looked up at them.",
82066: "\"Keiichi-kun.\"",
82067: "\"Mm?\"",
82068: "\"Are you happy?\"",
82069: "The question came out of nowhere, and he glanced at her.",
82070: "She was still looking at the light through the trees—not at him.",
82071: "\"…Yeah. I think so.\"",
82072: "\"Rena is too~.\"",
82073: "A pause.",
82074: "\"Rena thinks about it sometimes. Whether she deserves to be happy.\"",
82075: "\"What kind of question is that?\"",
82076: "\"Just—a question. Whether there's a limit. How much you're allowed to fight for happiness.\"",
82077: "He didn't know what to say to that.",
82078: "\"Well—I think you're allowed to fight for it as much as you want.\"",
82079: "\"Even if it means doing things that aren't nice?\"",
82080: "\"What kind of things?\"",
82081: "She didn't answer.",
82082: "They walked in silence for a few steps.",
82083: "Then Rena smiled—the ordinary smile—and said: \"Never mind. Rena was just thinking out loud~!\"",
82084: "\"Are you sure?\"",
82085: "\"Mm~! Let's hurry or we'll be late!\"",
82086: "And she set off at a trot, and he followed, and the cedars thinned out around them.",
82087: "He thought about the question later.",
82088: "Whether there was a limit to what you were allowed to do in pursuit of happiness.",
82089: "He thought he should have answered better.",
82090: "He thought he should have asked what she meant.",
82091: "He thought about it too late.",

# ============ FILE 08 ============
# Rena at the boutique, waiting, overhears Rena (the woman) and Teppei
82092: "The shop where my father had ordered his jacket was the sort of place that put on airs—chic, fashionable.",
82093: "There was no way my father had walked in there alone.",
82094: "It was immediately obvious he had been brought there by Rena-san.",
82095: "When I presented the receipt, the manager came out from the back with an apologetic smile.",
82096: "\"Ryuugu-sama, I do sincerely apologize. It appears the delivery truck has been caught in a traffic jam on the expressway… We believe it should arrive shortly, but…\"",
82097: "Apparently they'd received word that the truck had just exited the tollway at a particular interchange, and it would be here in about an hour—they put it in far more roundabout terms than that.",
82098: "I asked whether it would be better to come back another time—but they said it was almost there, and offered me a seat on the waiting sofa.",
82099: "…But the shop's atmosphere made me a little uncomfortable, so I said I'd go outside to kill time and stepped out.",
82100: "There was nowhere around that looked like a fast food place. I thought the nearest one was probably back near the station.",
82101: "Looking around, I spotted a café.",
82102: "A café was fine. I'd have something cold to drink and wait.",
82103: "I pushed open the glass door and went in—and froze.",
82104: "In a corner booth.",
82105: "Rena-san.",
82106: "And a man.",
82107: "They were sitting close together. Talking in low voices.",
82108: "Rena-san's back was to me, and the man's face was visible.",
82109: "He was smiling—but it was the kind of smile that doesn't reach the eyes.",
82110: "I stood very still in the entrance.",
82111: "The waitress started to say \"Welcome—\" and I held up a hand to stop her, mouthing: quiet, please.",
82112: "She looked confused, but she stopped.",
82113: "I found a seat at the counter—far from the booth, but close enough to hear fragments.",
82114: "Not every word. But enough.",
82115: "\"…the old man is completely…\"",
82116: "\"…transfer the account…\"",
82117: "\"…when is the wedding?\"",
82118: "\"…it'll be easy, with that family…\"",
82119: "I sat very still.",
82120: "My hands were folded on the counter.",
82121: "I listened.",
82122: "The man with the smile that didn't reach his eyes reached across the table and touched Rena-san's hand.",
82123: "She didn't pull back.",
82124: "I looked at the tabletop and thought: I see.",
82125: "I thought: so that's what this is.",
82126: "I thought: my father doesn't know.",
82127: "I thought: I have to decide what to do.",
82128: "I sat until I had heard enough—until I was certain of what I'd heard—and then I paid for the cold drink I hadn't touched and left the café.",
82129: "The afternoon sun was very bright outside.",
82130: "I stood on the pavement for a moment and let it hit my face.",
82131: "I thought: now I know.",
82132: "I thought: what can I do with knowing?",
82133: "I thought: what can I do?",
82134: "A long time, I stood there.",
82135: "And then I went back to the boutique, collected the jacket, and went home.",
82136: "I carried the jacket in both hands, very carefully.",
82137: "As though if I were careful enough, some things could still be kept intact.",

# ============ FILE 09 ============
# Rena's investigation continues — working toward confronting the woman
82138: "\"Ahhh, that's probably Kasai-san. He's Shion's watchdog.\"",
82139: "\"Watchdog?\"",
82140: "\"Ahha ha, well—Shion does more unpredictable things than I do—so she needs someone keeping an eye on her.\"",
82141: "\"I'd say you and Shion are evenly matched in that department.\"",
82142: "Keiichi-kun's teasing remark set off the usual lively sparring between him and Mii-chan.",
82143: "Kasai-san, it seemed, was a figure of some local standing in Okinomiya.",
82144: "…In other words, not someone I could simply approach on my own.",
82145: "But if he was Shi-chan's attendant, then perhaps I could find a way to reach him through Shi-chan.",
82146: "The problem was that Shi-chan and I had never really been close.",
82147: "When Shi-chan appeared in Hinamizawa we would laugh and joke around—but I had never approached her directly. I had no idea how I would go about meeting her.",
82148: "And even if I could meet her, there was no guarantee she would help.",
82149: "…Back at Angel Mort, she had only spoken because Mii-chan had been there—she seemed the type who didn't casually discuss other people's business.",
82150: "…And while I was going through all these roundabout calculations, things were getting worse, and wouldn't it become too late?",
82151: "From the conversation I'd overheard, the man had mentioned making his move soon.",
82152: "In other words—that was the signal for the finale of this scheme. They intended to take everything at once.",
82153: "Was I the only one who didn't grasp the urgency—was catastrophe already closing in?",
82154: "Even now, sitting peacefully through lessons—wasn't it possible that right now, at this moment, those men had broken into the house, were cornering my father, taking the bankbooks from him?",
82155: "…The more I thought about it, the more anxiety bred anxiety, until I felt the ceiling pressing down on me—a crushing psychological weight.",
82156: "\"…Man, it's so peaceful I'm bored.\"",
82157: "Keiichi-kun said it with a great yawn.",
82158: "\"Peace is wonderful, isn't it, Keiichi-kun.\"",
82159: "\"Sure, but there's such a thing as too peaceful—it makes you drowsy.\"",
82160: "\"Ehehe, well—shall we wake you up a bit?\"",
82161: "\"Don't you start—I know that face, Rena.\"",
82162: "\"Ahaha~!\"",
82163: "It took an effort—to let the surface of myself be ordinary.",
82164: "To laugh and joke and look like nothing was the matter.",
82165: "But I managed.",
82166: "I had to manage.",
82167: "Because if I gave it away—",
82168: "If someone noticed—",
82169: "Then the plan I had already begun, quietly, without anyone knowing—",
82170: "That plan would become impossible.",
82171: "And there was no other plan.",
82172: "This was the only way.",
82173: "I had thought about it from every angle.",
82174: "And every angle came back to the same conclusion.",
82175: "There was only one thing I could do.",
82176: "\"Rena-chan, are you all right?\"",
82177: "Rika-chan's small voice, quiet enough that only I could hear.",
82178: "I looked at her.",
82179: "She was watching me with those large, calm eyes.",
82180: "\"I'm fine~! Why do you ask~?\"",
82181: "\"You look tired.\"",
82182: "\"Rena didn't sleep much last night~\"",
82183: "\"…I see.\"",
82184: "She didn't press further.",
82185: "She looked at me for a moment more—those eyes that always seemed to see further than they should—and then looked back at the textbook.",
82186: "I kept smiling.",
82187: "And inside, where no one could see:",
82188: "I made my decision.",

# ============ FILE 10 ============
# Rena confronts her father about Rena-san and Teppei
82189: "\"There's no need to remarry.\"",
82190: "I came home and said it before I'd even taken my shoes off—and my father looked completely taken aback.",
82191: "The coldness in the way I said it made him sense I hadn't come around to the idea of remarriage, and his expression fell with a visible disappointment.",
82192: "\"…I can't blame you. …I understand how you feel, Rena. I should have talked with you about it beforehand—\"",
82193: "\"Tell her to take back the proposal. That woman.\"",
82194: "\"You can't call her 'that woman.' Rena-san is—\"",
82195: "\"I'll tell you the truth. That woman and a man named Teppei are a pair of criminals. They only got close to Father to get at our family's money.\"",
82196: "My father, as oblivious as ever, seemed to flare up at my calling her 'that woman.'",
82197: "I thought I'd been a little too blunt with my word choice—but I believed I had conveyed the truth concisely.",
82198: "I told him what I had seen and heard at the café.",
82199: "…My father, predictably, pushed back with defenses of Rena-san.",
82200: "I felt disappointment again—but at the same time, knowing he would react this way confirmed for me that there had been no other way except what I'd already done. Strangely, my shoulders felt lighter.",
82201: "Apparently deciding that he couldn't proceed with remarriage without my agreement, my father swallowed his anger, put on a conciliatory smile.",
82202: "\"Rena, let's all sit down and talk again, slowly. If we do that, I know you'll come to understand.\"",
82203: "…Even the pet, when the owner is gone, is still a pet.",
82204: "That's all right. I opened the cage, just the same.",
82205: "…Even a pet realizes one day that it is no longer caged.",
82206: "That isn't mine to teach. It's for my father to discover.",
82207: "I couldn't bear the excuses in my father's trained smile, and I left the living room.",
82208: "The pain of his divorce from my mother—time had healed that too.",
82209: "Time heals even the deepest wounds.",
82210: "But the wound has to be real. Has to be felt.",
82211: "My father was still insisting that the wound wasn't a wound.",
82212: "While insisting that, he would never begin to heal.",
82213: "That was what I couldn't forgive.",
82214: "Not the woman who deceived him.",
82215: "But my father—who even after being shown the truth, refused to see it.",
82216: "I sat in my room.",
82217: "Looked at the ceiling.",
82218: "Thought about what came next.",
82219: "There was still one more thing to do.",
82220: "The thing that would make everything final.",
82221: "I had already decided.",
82222: "I thought about it one more time, clearly, from beginning to end.",
82223: "And when I reached the end again—it was the same answer.",
82224: "There was nothing else.",
82225: "I closed my eyes.",
82226: "I breathed.",
82227: "And I went downstairs to help with dinner, as normal.",
82228: "\"Oh, Rena—are you all right?\"",
82229: "My father looked up from the pot he was stirring.",
82230: "\"I'm fine. Let me do that.\"",
82231: "I took the ladle from him.",
82232: "And I made dinner.",
82233: "As I always had.",
82234: "As if nothing was the matter.",
82235: "Because nothing was the matter.",
82236: "I had decided.",
82237: "And now I was at peace.",
82238: "That is the strangest thing.",
82239: "How peaceful it is—once the decision is made.",

# ============ FILE 11 ============
# Rena's aftermath narration — after the killings, cleaning up
82240: "The remaining work I had to do was all cleanup.",
82241: "Having come this far, my resolve had settled into place. So the work itself—I could manage.",
82242: "And besides: now that they were gone, I was free of every worry that had crushed me.",
82243: "If that was the price—then this much… I could bear.",
82244: "…Don't look back. If I stop now, I won't be able to take another step forward.",
82245: "Something tar-black—like crude oil—clings to my whole body, and if I let it, it will stop me from moving, from thinking at all.",
82246: "What I can do right now… is only to keep believing.",
82247: "That what I did in this trash heap—no, what I accomplished—was the only choice left to me.",
82248: "…Ah, come to think of it—long ago, near the end of the dam conflict, a murder case had occurred right here on this site. The site foreman.",
82249: "At first I had thought about sending them down the stream that runs through the dam construction site.",
82250: "But if I did that, someone downstream would certainly find them.",
82251: "I remembered hearing news reports about remains found along a riverbed, washed up somewhere downstream.",
82252: "Going further into the abandoned villages toward Yagauchi or Takatsudo—there are unmapped mountains deep in there.",
82253: "Somewhere in those mountains would be safe.",
82254: "…Don't stop. Keep walking.",
82255: "…Don't look back. Look only ahead.",
82256: "…My body aches in unfamiliar places—muscles I've never used before.",
82257: "I finished the cleanup carefully, then went into my hideout and lay down on the mattress.",
82258: "…Damp sweat had matted my bangs to my forehead—uncomfortable.",
82259: "I'll take a bath later. Take my time and wash every inch of myself.",
82260: "I stared at the rusted roof of my hideout—the abandoned car—and breathed slowly.",
82261: "I could hear the higurashi.",
82262: "Far away—rising, fading.",
82263: "I thought: I'm still here.",
82264: "I thought: I'm still me.",
82265: "I thought: it's over.",
82266: "But of course, it wasn't over.",
82267: "I knew that.",
82268: "There was still the matter of where to hide what I had done.",
82269: "And there was still my father.",
82270: "My father, who did not yet know anything—who was probably home right now, humming, making dinner.",
82271: "My father, who would believe Rena-san had simply left.",
82272: "He would be sad.",
82273: "He would be confused.",
82274: "But he would be alive.",
82275: "He would be safe.",
82276: "And that—that was the thing I had done this for.",
82277: "I breathed.",
82278: "I stared at the ceiling.",
82279: "The higurashi sang on.",
82280: "Far away—rising, fading.",
82281: "Rising.",
82282: "Fading.",
82283: "I closed my eyes.",
82284: "And I rested.",

# ============ FILE 12 ============
# The end of Rena's confession — Keiichi and friends respond
82285: "\"…That's… all of it, I think.\"",
82286: "Rena's confessional drama drew to its close.",
82287: "No one applauded. No one called for an encore.",
82288: "…Such a quiet, solitary—Rena's entirely solitary—stage.",
82289: "I realized I had forgotten to blink for quite some time.",
82290: "Mion and the others appeared to have done the same.",
82291: "Rena surveyed us all with an expression that seemed to ask: any questions?",
82292: "When we recognized it as an imitation of Chie-sensei at the end of class, we all answered with small, pained smiles.",
82293: "\"…Just a little while ago, I was over in Yagauchi. Looking for a place to bury the bag. I want to hide it somewhere it will never be found—but ahaha, it's hard to find just the right place.\"",
82294: "\"I even thought about burying it in our own garden—that it might actually be safer. …But no, that's too risky. Dad might suddenly decide he wants to start a vegetable garden.\"",
82295: "\"After all, somewhere deep in the mountains is better. I didn't want that woman anywhere near my father—not even in death.\"",
82296: "I was overwhelmed with guilt.",
82297: "…Rena's plan had been going flawlessly.",
82298: "And I—through my stupid joke, my thoughtless meddling—",
82299: "Looking around, it was clear that everyone felt the same remorse.",
82300: "If Mion hadn't suggested playing in the trash heap.",
82301: "If Satoko hadn't spotted Rena in the trash heap.",
82302: "If Rika-chan had managed to stop them from going to the trash heap to play.",
82303: "If any of those things had been different—Rena would have spent a few more days, in a way none of us would ever know about, and brought everything to a close on her own.",
82304: "And then what?",
82305: "She would have gone on living normally.",
82306: "As though nothing had happened.",
82307: "As though all those days together—the club, the games, the afternoon at Angel Mort—had never been interrupted at all.",
82308: "And we would never have known.",
82309: "…That's what she wanted.",
82310: "That's what she was trying to protect.",
82311: "\"…You've been carrying all of that, by yourself.\"",
82312: "Mion said it quietly. Not reproach—just recognition.",
82313: "\"Mm.\"",
82314: "Rena looked down briefly.",
82315: "\"I didn't want to make everyone sad.\"",
82316: "\"We're not sad.\"",
82317: "I said it before I knew I was going to say it.",
82318: "Rena looked at me.",
82319: "\"…We're not sad. We're…\"",
82320: "I didn't have the right word.",
82321: "\"We're here.\"",
82322: "A long pause.",
82323: "Then Rena's expression shifted—just slightly. Something in it eased.",
82324: "\"…Keiichi-kun.\"",
82325: "\"We're here. Whatever happens next—we're not going anywhere.\"",
82326: "Mion nodded, very quietly.",
82327: "Satoko looked down.",
82328: "Rika-chan said nothing—only watched Rena with those serene, ancient eyes.",
82329: "And Rena stood on her rusted stage.",
82330: "In the fading light.",
82331: "\"…Thank you.\"",
82332: "Her voice was very small.",
82333: "\"Thank you for listening.\"",
82334: "No curtain fell.",
82335: "The higurashi went on singing.",
82336: "But something had changed.",
82337: "Something—I couldn't name—had shifted in the air.",
82338: "Rena climbed down from the car.",
82339: "She stood on the ground again, among us.",
82340: "And the five of us remained there, together, in the last of the light.",

# ============ FILE 13 ============
# Oishi and Kumagai at the Watanagashi festival — police perspective
82341: "\"Welcome, welcome! Step right up—!\"",
82342: "\"Right here! Syrup in strawberry, melon, or Blue Hawaii!\"",
82343: "\"Lottery takoyaki! Come on, come on! Winner gets one packed full of mustard!\"",
82344: "As always, the Watanagashi festival had drawn a long row of stalls.",
82345: "A festival just needed the sounds of bon odori music and stalls out front, Ooishi thought—that was enough.",
82346: "Even though it was technically still June, the relentless heat of near-summer days had continued—",
82347: "And with the festival and the bon odori music too, you might as well throw in a fireworks show while you were at it.",
82348: "\"Kumagai here. Ooishi-san, go ahead, Ooishi-san.\"",
82349: "The crackling voice came through the earpiece of Ooishi's portable radio.",
82350: "…When Ooishi wore an earpiece, he always looked like he was sneaking a horse racing broadcast during his shift.",
82351: "\"Yes, this is Ooishi. Receiving clearly.\"",
82352: "\"Uh, sir—the town association has brought over a tremendous amount of food. Oden, yakisoba, motsu stew, and also—um—cold barley tea.\"",
82353: "\"Nahaha! That barley tea—is it on-duty tea? Or off-duty tea?\"",
82354: "\"Um—ah, ahahaha.\"",
82355: "\"If it's in cans, please accept it with our thanks. If it's in cups, please decline politely.\"",
82356: "\"Yes, understood. …Oh, and a representative of the town association is here to pay his respects. The village headman, and also someone from the Sonozaki family…\"",
82357: "\"…O-Rika, the old lady? Oh, I really don't want to—do you think you could manage to tell them Ooishi is out on patrol and you don't know when he'll be back?\"",
82358: "\"…No, sir, they know we have radios and can call you back immediately… she was quite insistent…\"",
82359: "\"Nahahaha! That old woman—cerebrovascular accident, that's how she'll go, mark my words. Understood, understood—please let them know, very politely—and I do mean very—that I'll be right there.\"",
82360: "…Well, so much for that. Time to get back to community relations.",
82361: "Ooishi ended the communication and made his way toward the festival grounds.",
82362: "The Watanagashi festival—the cotton-drifting ceremony—was Hinamizawa's most famous local event.",
82363: "Dozens of stalls lined the approach to the shrine, and the whole area was packed with people from surrounding villages who had come to watch.",
82364: "The grounds rang with children's laughter, the smell of grilled things, the strains of the bon odori music.",
82365: "Ooishi moved through it all with the practiced ease of a man who had attended this festival many times.",
82366: "He was working tonight—the anniversary of the Hinamizawa disaster was always this time of year, and every year since, the village had been watched with care.",
82367: "\"Ooishi-san.\"",
82368: "Kumagai appeared out of the crowd, offering a can of barley tea.",
82369: "\"Good man. Thank you.\"",
82370: "Ooishi accepted it, cracked it open, and took a sip.",
82371: "\"How's the headman?\"",
82372: "\"He asked me to tell you he appreciated your continued attention to the village.\"",
82373: "\"Politely said. And the Sonozaki representative?\"",
82374: "\"O-Rika herself, sir.\"",
82375: "A pause.",
82376: "\"…I see. Lead the way.\"",
82377: "\"This way, sir.\"",
82378: "They moved through the festival crowd.",
82379: "Ooishi's eyes never stopped moving—scanning faces, watching the edge of the crowd, noting who stood too long near the shrine path.",
82380: "He had been watching this village for years.",
82381: "He was still watching.",
82382: "He didn't know exactly what he was watching for—he never had, not precisely.",
82383: "But he had learned that in Hinamizawa, the things you didn't expect were the things that mattered.",
82384: "The Watanagashi night was always—different.",
82385: "He couldn't say how. He just knew.",
82386: "\"O-Rika-san is waiting at the shrine pavilion, sir.\"",
82387: "\"Of course she is.\"",
82388: "Ooishi adjusted his tie, finished his tea, and walked on.",

# ============ FILE 14 ============
# Rena's recollection of meeting Takano Miyo at the library
82389: "To begin with, Takano-san and I had never had much of a connection.",
82390: "We knew each other well enough to exchange nods passing in the street. That was about the extent of it.",
82391: "We had only once had a real conversation.",
82392: "…And that was recently.",
82393: "Shortly before the Watanagashi festival.",
82394: "A few days after killing Rena-san and Teppei—after Keiichi-kun and the others had found out.",
82395: "Late one afternoon, I got a call from the library saying my father had forgotten to return a book he'd borrowed.",
82396: "My father had gone out shopping at the home center, so I went to return it myself.",
82397: "And while I was there, I thought I might borrow something too, and wandered between the stacks looking at random.",
82398: "…And that was where I met her.",
82399: "\"Oh—isn't this Rena-chan? Hello.\"",
82400: "\"Takano-san. Hello. It's unusual to meet you at the library.\"",
82401: "\"Is it? I find it far more unusual that you're here, Rena-chan. Kukuku.\"",
82402: "Her expression held the same composed, adult grace I knew from our brief meetings in the village—not the expression of someone who knew her own death was a few days away.",
82403: "She told me she often came here to wait for Tomitake-san.",
82404: "To pass the time, she said, and offered to treat me to a drink.",
82405: "I had no urgent reason to get home.",
82406: "She bought me an iced milk tea from the library's vending machine, and we sat and talked for a while.",
82407: "…Looking back now, there was a painful irony in it.",
82408: "Because she was the one who brought up the Hinamizawa serial mysterious deaths herself.",
82409: "Without knowing she was about to add her own name to its fifth year.",
82410: "She spoke with great enthusiasm about the cases.",
82411: "About Oyashiro-sama's curse.",
82412: "About the research she and Tomitake-san had been conducting.",
82413: "Her eyes shone—the look of someone passionately devoted to their work.",
82414: "\"But, you know, I think the truth of this village is far more interesting than a curse.\"",
82415: "She said it with a small smile.",
82416: "\"The pattern of the deaths, the nature of the incidents—there's something very deliberate about them. Very constructed.\"",
82417: "\"Constructed?\"",
82418: "\"Like someone is maintaining a narrative. Sustaining something.\"",
82419: "I didn't know what to say to that.",
82420: "\"I'm not frightened by it,\" she added. \"Quite the opposite. I find it fascinating.\"",
82421: "\"But—doesn't it worry you? That something might happen?\"",
82422: "She looked at me—directly, calmly.",
82423: "\"Everything that matters involves risk, doesn't it?\"",
82424: "She said it quietly, without drama.",
82425: "I thought about it afterward.",
82426: "I still think about it.",
82427: "\"Everything that matters involves risk.\"",
82428: "She said that—knowing, perhaps more than she let on, what was coming.",
82429: "Or perhaps not knowing at all.",
82430: "I'll never know.",
82431: "We parted pleasantly, outside the library, in the afternoon light.",
82432: "\"Take care of yourself, Rena-chan.\"",
82433: "That was the last thing she said to me.",
82434: "\"You too, Takano-san.\"",
82435: "That was the last thing I said to her.",
82436: "And then she walked away, in the direction of the shrine, and I watched her go.",
82437: "And I thought: she is walking toward something I cannot see.",
82438: "And I thought: we all are.",

# ============ FILE 15 ============
# Academic text about homecoming instinct and Hinamizawa Syndrome — Takano's research material
82439: "● On 'Homing Instinct' and 'Homesickness'",
82440: "In the broadest sense of the term, 'homing instinct' could be said to apply to nearly all living creatures.",
82441: "The same holds true for human beings—we instinctively prefer to sleep, rest, and eat in familiar places, in what we call home.",
82442: "The home, in this sense, corresponds directly to the nest—and so it can be said that humans too possess a homing instinct.",
82443: "But why do animals require a nest in the first place?",
82444: "This too is exactly the same for human beings.",
82445: "Sleep, rest, and eating are all activities essential to survival—and simultaneously, they are activities that leave one vulnerable.",
82446: "It was therefore necessary to establish a 'safe zone' where one could lower one's guard without danger.",
82447: "It is widely understood that being denied such a 'safe zone' causes extreme stress.",
82448: "Forcing an animal into an unfamiliar environment inflicts considerable stress—and for human beings too, being compelled to live in an unfamiliar place, always on guard, inflicts substantial stress.",
82449: "This stress is universally recognized as 'homesickness.'",
82450: "In Japan, research into 'homesickness' has been remarkably shallow.",
82451: "This is because it has long been defined as a failure of willpower—a laxity of spirit—and its treatment has historically been neglected.",
82452: "'Homesickness' has a very long history. In medieval Europe, it was believed to be not a psychological condition but a physical illness.",
82453: "Far from their homelands, with no means of hearing a loved one's voice as we have today, young people working abroad fell prey to homesickness in ways that are not difficult to imagine.",
82454: "When those afflicted longed desperately to return home yet could not—due to the demands of work—the resulting conflict caused both physical and mental deterioration, and in some cases actual psychological breakdown, driving them to desperate acts of escape or even suicide.",
82455: "The people of that era believed in this condition too, and numerous folk remedies and quasi-magical treatments to ward off homesickness were widespread.",
82456: "Unable to be cured by anything other than returning home, it might rightly be called an intractable disease.",
82457: "What is particularly interesting, however, is the following.",
82458: "Swiss soldiers serving abroad in the seventeenth century—specifically those deployed to France—developed symptoms of homesickness in extreme severity.",
82459: "The condition spread among them, and eventually a military surgeon identified it as a distinct disease.",
82460: "The symptoms were: persistent melancholy, weeping, loss of appetite, irregular heartbeat, and in severe cases: fever, and finally—death.",
82461: "The cause identified by the military surgeon was: a certain melody played on the cowherds' pipes, traditional to the Swiss highlands.",
82462: "When Swiss soldiers heard this melody—the sound of their homeland—the homesickness would seize them violently.",
82463: "The melody was therefore prohibited.",
82464: "Soldiers heard playing it, or even humming it, faced severe punishment.",
82465: "What does this tell us?",
82466: "It tells us that the trigger for extreme homesickness was sensory: a sound deeply associated with home.",
82467: "A sound.",
82468: "A familiar, beloved sound—and hearing it, far from the place it belonged, broke something in them.",
82469: "Now let us consider: what is the sound most associated with Hinamizawa?",
82470: "Unquestionably—the cry of the higurashi.",
82471: "The higurashi that sings every summer, echoing through the mountains and valleys.",
82472: "For those born and raised in Hinamizawa, this cry is not merely a sound.",
82473: "It is the sound of home.",
82474: "And when someone who carries Hinamizawa within them—in their blood, in their body—hears that cry after being separated from the village—",
82475: "What happens?",
82476: "The same thing that happened to those Swiss soldiers.",
82477: "The mechanism is not metaphor.",
82478: "It is a hypothesis—and more than a hypothesis.",
82479: "The parasite we have identified acts upon the nervous system in a manner consistent with these symptoms.",
82480: "Stress. Anxiety. Aggression. Paranoia. Deterioration.",
82481: "The very symptoms of extreme homesickness—magnified, given a biological vector.",
82482: "The cry of the higurashi is the trigger.",
82483: "Hinamizawa itself is the pathogen.",
82484: "And those who carry the village within them—they are both host and prisoner.",
82485: "The Queen Carrier maintains the equilibrium.",
82486: "Remove her, and the balance collapses.",
82487: "This is our conclusion.",
82488: "This is the truth of Hinamizawa Syndrome.",
82489: "The village does not punish those who leave.",
82490: "It simply—calls them back.",
82491: "In the only language the body understands.",
82492: "In the voice of the higurashi.",
82493: "In the sound of home.",

}


def translate(entry, file_idx=None):
    """Return translated text for entry, or None if not found."""
    msg_id = entry.get('MessageID')
    jpn = entry.get('TextJPN', '')

    if msg_id and msg_id in TRANSLATIONS:
        return TRANSLATIONS[msg_id]

    # Fallback: clean the Japanese text and mark as needing translation
    clean = strip_tags(jpn)
    return None


def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    count_added = 0
    count_skipped = 0
    count_missing = 0

    for entry in data:
        if entry.get('type') not in ('MSGSET', 'LOGSET'):
            continue
        if 'TextENGNew' in entry:
            count_skipped += 1
            continue

        translation = translate(entry)
        if translation is not None:
            entry['TextENGNew'] = translation
            count_added += 1
        else:
            count_missing += 1

    if count_added > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    return count_added, count_skipped, count_missing


# Main
total_added = 0
total_skipped = 0
total_missing = 0

files = ['tsumihoroboshi_{:02d}.json'.format(i) for i in range(1, 16)]
for i, filepath in enumerate(files, 1):
    added, skipped, missing = process_file(filepath)
    total_added += added
    total_skipped += skipped
    total_missing += missing
    print(f'{filepath}: added={added}, skipped={skipped}, missing={missing}')

print(f'\nTotal: added={total_added}, skipped={total_skipped}, missing={total_missing}')
