#!/usr/bin/env python3
"""Translations for taraimawashi_3.json"""
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

TRANSLATIONS = {
53870: "\"See you~, Kei-kun!\"",
53871: "She gave a snappy little wave, then spun on her heel and started walking in the direction of her house.",
53872: "Copying Mion's gesture, of all things.",
53873: "A moment later she broke into a skipping gait, humming to herself.",
53874: "\"Don't trip on something and fall over, Rena!\"",
53875: "\"Ahahaha!\nI'm totally fine~!\"",
53876: "That's not an answer.",
53877: "Club activities ended, and as usual, I walked partway home with Rena.",
53878: "Rena was in high spirits today.",
53879: "She said it was because she'd topped the scoreboard for the first time ever in the mystery game — but even so, she was practically holding her own private festival.",
53880: "That broad smile when she handed Mion the shopping list…",
53881: "Years of grudges… at last, I get my revenge… I'll be in your care… won't I~ Doro-doro-doro-doro…",
53882: "…That kind of energy.",
53883: "I arrived home somewhere in the middle of that nonsense.",
53884: "I reached for the front door handle — hm, it won't open?",
53885: "…Ah, nobody's home.\nToday, because of Dad's work, Mom had gone out with him.",
53886: "I reached into my pocket for the key on its walrus keychain, intending to unlock the front door.",
53887: "I slid it into the lock, turned it, and the door swung open.",
53888: "The empty house was dead quiet and somehow melancholy.",
53889: "I think I understand why an uninhabited house, left alone, starts to rot quickly.",
53890: "I kicked off my shoes and headed upstairs.",
53891: "I dropped my bag in my room and flopped down on the bed wondering what to do next — and then my stomach gave a loud rumble.",
53892: "…I needed to get something in me before dinner.",
53893: "I went back downstairs to the kitchen and rummaged through the fridge, the cupboards, every corner in reach.",
53894: "\"Nothing…\nNothing……\nNothing~~!\"",
53895: "Not a trace of food anywhere I looked.",
53896: "My shoulders sagged and I let out a long, deep sigh.",
53897: "I mean… normally, when parents go out, they leave something prepared, don't they.",
53898: "I had complained about this once before, but Mom waved it off with \"you can buy whatever you want anywhere\" and that was her standing excuse for never cooking.",
53899: "…She had a point, technically…\nBut… somehow having nothing there still made me quietly annoyed.",
53900: "People really are terribly selfish creatures.",
53901: "\"Hurry up and get here already… Mion.\"",
53902: "I was talking to myself.",
53903: "Why?\nBecause she had gone and said it on her own.",
53904: "In today's club activities, Mion was the undisputed last place.",
53905: "Which, in a sense, was only natural — but Rena and I had tied for first.",
53906: "So Mion had taken Rena's shopping list — and then turned on me like she was picking a fight.",
53907: "\"Well, if it comes to this, one more or less doesn't matter!\nCome on, out with it — what do you want me to buy?!\"",
53908: "…Being coerced into making a request — that was a first in my life.",
53909: "There was nothing for it, so I went ahead and asked Mion for my own particular errand.",
53910: "But Mion's expression at that moment — head tilted slightly —",
53911: "\"…This?\nThis is all you want?\nAnd… this?\"",
53912: "She kept double-checking.",
53913: "Yes, that's what I want! I'm starving — just get it and come back!",
53914: "I was on the verge of shouting exactly that — when the doorbell rang.",
53915: "I walked to the door and opened it — and there standing in front of me was Mion.",
53916: "\"Here — got it!\"",
53917: "\"…Perfect timing.\"",
53918: "\"Hm? …Kei-chan.\nJust now, I heard you calling up at the sky: 'Mion, hurry up and get here!'\n\"",
53919: "\"Wh-why would I do that?!\"",
53920: "\"So you did~ ahahaha!\"",
53921: "\"How did you know, Mion?\"",
53922: "\"Because I could hear you.\"",
53923: "\"Y-you could?!\"",
53924: "Watching me panic, Mion burst out with \"I was lying~~!\" and cackled.\n…She'd got me.",
53925: "\"Even so… why this for an errand?\nAnd just one…\"",
53926: "Her eyes were fixed on what she had gone to buy.",
53927: "Cup ramen.\nAnd with a specific brand — the extra-large cup, pork bone with ginger flavour…",
53928: "\"It's fine, isn't it.\nIt's my favourite — and it's my dinner tonight.\"",
53929: "\"What?!\nThis was your dinner?!\"",
53930: "\"Mom's out today, so.\"",
53931: "\"Oh, is that all…\nIf that's the case, maybe I should have made something and brought it over?\"",
53932: "\"…You, Mion?\nCan you cook?\"",
53933: "\"How rude!\nDon't underestimate me.\nCooking is one of my greatest strengths!\"",
53934: "She planted her hands on her hips and stood in defiant outrage.",
53935: "But… I had a hard time believing that. With that face, that manner?… Not buying it.",
53936: "\"…What's with that look?\"",
53937: "\"Well, I've never actually seen it…\"",
53938: "\"Hmph — I'll show you someday.\nAnd then I'll make you say 'gyaffuuun'!\"",
53939: "\"Sure, I'm looking forward to it.\"",
53940: "I answered cheerfully, and then Mion picked up her bags from the ground.",
53941: "Both hands were full of enormous shopping bags.",
53942: "…No, seriously, that was an incredible amount of stuff.\nI found myself looking into the bags without even asking.",
53943: "Five hundred grams of pork scraps, two packs of eggs, five cakes of tofu, four cartons of milk, 1.8 litres of soy sauce… and then carrots, long onions, pumpkin, onions, potatoes, green beans, Chinese cabbage, shiitake, king oyster mushrooms, komatsuna, bean sprouts…",
53944: "…With a start, I looked more closely and — a row of little spice jars lined up neatly.",
53945: "Mion pulled Rena's shopping list out of her pocket and read off the spice names.",
53946: "\"Let's see… colouring bittering agents: saffron, paprika, turmeric, gardenia seed…\nThen spicy heat agents: pepper, chilli, wasabi, mustard…\"",
53947: "\"And finally flavouring aromatics: clove, mint, thyme, rosemary.\nSage, basil, fennel, caraway, fennel seed.\nAnise, oregano, watercress, caper, bay leaf, coriander…\"",
53948: "I checked each name against the label on the little spice jars.",
53949: "\"That lines up… that's right… correct…\"",
53950: "\"Because Rena said she wants to try her hand at real cooking next time!\"",
53951: "…Even so — there have to be limits. What is she planning to make? A proper curry? Italian food?",
53952: "This seemed almost like bullying.",
53953: "And what was more — there was another bag, with a similar shopping list inside — also Mion's, making the total formidable.",
53954: "\"Mion.\nDid you carry all of this yourself?\"",
53955: "\"I did.\nIt's a penalty game.\"",
53956: "I looked at Mion's face.\nThen I looked at her arms struggling under the weight.",
53957: "Her expression was perfectly composed, but her arms — the tendons stood out sharply in them, and they were faintly trembling.",
53958: "\"Alright then, Kei-chan.\nSee you tomorrow~ …yup.\"",
53959: "Mion turned and began making her heavy way back the way she had come.",
53960: "It felt almost as if the earth was bending under the weight.",
53961: "\"…Wait, Mion.\"",
53962: "I had sprinted out after her before I knew it.",
53963: "\"Hold on.\"",
53964: "\"…What is it?\"",
53965: "\"I've got nothing to do anyway.\nI'll help carry.\"",
53966: "I said that, grabbed one of the shopping bags from her, and set off walking.",
53967: "\"It's okay.\nHey — I said it's fine — wait, hold on…\"",
53968: "I had expected her to protest, so I ignored every word and walked on briskly.",
53969: "\"…………\"",
53970: "After a while, Mion's footsteps came up behind me.",
53971: "She caught up and fell into step beside me, then gave an embarrassed little laugh.",
53972: "\"Thanks.\"",
53973: "…Hm?",
53974: "\"They were… just a little heavy, you know.\"",
53975: "A straightforward admission from Mion.",
53976: "Normally she would have refused even so.\nBut today's Mion felt somehow different from usual — that much was certain.",
53977: "Something of her usual tomboy manner had gone quiet.",
53978: "Two shadows walked side by side along the road where the sun had set.\nThe cry of the higurashi rang pleasantly across the landscape in all directions.",
53979: "\"What's going on, Mion?\"",
53980: "Not that it was directly connected to that — but I decided to just ask.",
53981: "\"Hm, what?\"",
53982: "\"You seem like something's on your mind.\"",
53983: "\"…Not really.\"",
53984: "Mion said that and nothing more, and we walked on in silence again.\n…And then.",
53985: "\"…Hey.\"",
53986: "\"What?\"",
53987: "I wanted to ask at least the thing that had been on my mind since the afternoon, so I opened my mouth again.",
53988: "\"You were called away during club activities, right?\nWho was it that came?\"",
53989: "\"Oh, right… just, you know…\"",
53990: "\"…Just, what?\"",
53991: "When she had come back, she had seemed less energetic than usual.\nRena had noticed too and asked about it.",
53992: "I had been wondering about it the whole time.",
53993: "\"…Could it be… about last night?\"",
53994: "The moment I said that, Mion drew a sharp breath and stopped dead.",
53995: "She spun toward me and fixed her eyes on me.",
53996: "…There it was again. Those eyes.",
53997: "The ones I had seen on the night of the Watanagashi — when she was pressing me about what Shion and I had talked about. That strangely fierce, gleaming light.",
53998: "\"…Last night…?\"",
53999: "\"What…?\"",
54000: "\"What do you mean by… last night…\"",
54001: "Caught in that gleaming gaze, something clenched in me involuntarily.",
54002: "A tension like something gripping me by the base of the skull bore down on me.",
54003: "When a person finds themselves in the gaze of a force that is absolutely, overwhelmingly greater than their own — sometimes, out of sheer fear, the body acts against the will.",
54004: "And so, from me — my mouth spoke on its own.",
54005: "\"I-I just thought… maybe something happened after the festival.\nBecause I heard — you know, that the curse means people die strangely, or suddenly disappear…\"",
54006: "Perhaps I had, somewhere in the depths of my heart, long felt a quiet grievance at Mion never telling me anything.",
54007: "That said, there was no doubt that what came out was a naive, thoughtless question.",
54008: "But Mion's expression was very sharp.",
54009: "\"Who told you?\"",
54010: "\"…What?\"",
54011: "\"…Who told you?!\"",
54012: "\"……………\"",
54013: "I couldn't answer right away.",
54014: "\"Who?\nWho?\"",
54015: "Mion's eyes went wide — and at the same moment —",
54016: "Crash!!",
54017: "The shopping bag in Mion's hand slammed down onto the road.",
54018: "The contents spilled out and scattered across the ground.",
54019: "For an instant it felt as though everything had stopped moving.",
54020: "And then —",
54021: "A damp, raw-smelling wind swept through as if in mockery — moist and thick.",
54022: "\"Oh — sorry.\"",
54023: "Mion seemed to snap back, surprise crossing her face.\nShe crouched down on the road and started picking up the scattered contents.",
54024: "\"Oh… right…\"",
54025: "I crouched down and helped Mion gather them up.",
54026: "In the middle of it, Mion murmured — almost to herself, as if confirming it —",
54027: "\"…It was Shion.\"",
54028: "\"……………\"",
54029: "I couldn't deny it.",
54030: "\"…So I was right.\nShe — going around saying unnecessary things —\"",
54031: "She spat the words out.",
54032: "\"H-hey, Mion… it wasn't like Shion was doing anything —\"",
54033: "The words stuck before I could get any further.",
54034: "\"…don't.\"",
54035: "\"…What?\"",
54036: "Suddenly I heard Mion's voice, but it was quiet — I couldn't quite make it out.",
54037: "I turned and looked at Mion's lips — still bent over the ground, still picking things up.",
54038: "\"——\"",
54039: "…What? Mion, what are you —?",
54040: "\"Don't go near Shion anymore.\"",
54041: "The words, weighted as if something were crushing them from above.",
54042: "In an instant she closed the distance between our faces and I could see my own reflection clearly in Mion's sharp eyes.",
54043: "I felt, somehow, as if I had been shut inside that dark and uncanny darkness — and my body went still.",
54044: "\"……………\"",
54045: "\"You can't go near Shion anymore.\"",
54046: "I nodded, carefully.",
54047: "Words… wouldn't come.",
54048: "Then, suddenly, it looked as if Mion's eyes flipped right over.",
54049: "And in the next moment, Mion was laughing her bright, rattling laugh.",
54050: "\"…Ahahaha, Kei-chan!\"",
54051: "\"…What??\"",
54052: "\"The way you look!\"",
54053: "I finally noticed — I had sat down flat on the road.",
54054: "…Undignified.",
54055: "\"Like a frog. Ahahahahahaha.\"",
54056: "…A frog?",
54057: "\"A frog flipped on its back, belly in the air!\"",
54058: "Mion laughed and laughed, rolling with it.",
54059: "The usual Mion………… right?",
54060: "Mion and I collected everything that had rolled away, and set off again toward Rena's house.",
54061: "After we had walked a while, Mion said quietly:",
54062: "\"Kei-chan.\nYou're… my friend, right?\"",
54063: "She said that, then turned to me with a warm smile and continued.",
54064: "\"When things calm down, I'll tell you everything.\nI promise.\nSo… please don't go near Shion anymore.\"",
54065: "\"Ah, alright…\"",
54066: "There was nothing more I could add.",
54067: "At that, Mion looked down, hiding her expression, and murmured:",
54068: "\"…Shion is overstepping herself.\nIf she keeps sniffing around… there won't be much choice…\"",
54069: "—— 'There won't be much choice'…?",
54070: "Those words alone came creeping out from Mion's barely-visible shadow, sending a chill down my spine.",
54071: "The cry of the higurashi had begun to ring out across the landscape again.",
}

# Entry 53949 is missing from the list above:
TRANSLATIONS[53949] = "\"Let's see… that one lines up… yep… right…\""

with open(BASE_DIR / 'taraimawashi_3.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for entry in data:
    if entry.get('type') not in ('MSGSET', 'LOGSET'):
        continue
    if 'TextENGNew' in entry:
        continue
    mid = entry.get('MessageID')
    if mid in TRANSLATIONS:
        entry['TextENGNew'] = TRANSLATIONS[mid]
        count += 1

with open(BASE_DIR / 'taraimawashi_3.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"taraimawashi_3.json: wrote {count} translations")

with open(BASE_DIR / 'taraimawashi_3.json', 'r', encoding='utf-8') as f:
    data2 = json.load(f)
missing = [(e.get('MessageID'), e['TextJPN']) for e in data2 if e.get('type') in ('MSGSET','LOGSET') and 'TextENGNew' not in e]
print(f"Still missing: {len(missing)}")
if missing:
    for mid, txt in missing:
        print(f"  {mid}: {txt[:80]}")
