#!/usr/bin/env python3
"""Add TextENGNew translations to kamikashimashi_5.json"""
import json

translations = {
154652: "......I must have drifted off at some point despite everything.",
154653: "I woke up to Mion poking me......",
154654: "\"Time to get up.\"",
154655: "\"Mmn...... Oh, yeah...... You actually woke up on time without any alarm. Impressive......\"",
154656: "\"Mii-chan didn't sleep at all.\"",
154657: "\"You're the one who snored the loudest of us all. Quite a set of nerves on you, Keiichi-san.\"",
154658: "\"......It doesn't feel, pitch dark......\"",
154659: "\"True. Moonlight is surprisingly bright.\"",
154660: "If it really had been only moonlight, it might have been a little romantic.",
154661: "Traffic lights and other illumination that had been left on kept lighting the city without rest.",
154662: "Unlike Hinamizawa, Okinomiya never fell into absolute darkness at night.",
154663: "I couldn't tell whether that was fortunate or a disadvantage for our stealth.",
154664: "From time to time, flashlight beams flickered over the main road — a river of unattended cars.",
154665: "They had set a watch, just as we expected.",
154666: "Still, their alertness was far thinner than it was during the day.",
154667: "\"......Okay. We can do this......\"",
154668: "\"......We're going to, be okay, aren't we......?\"",
154669: "\"Leave it to us. There's nothing to be afraid of. We'll cross it easily.\"",
154670: "\"We've got our secret weapon too.\"",
154671: "\"I'd really like to do this quietly. If we come barreling in making noise, we'll cause problems for the people in the office too.\"",
154672: "\"Fair enough.\"",
154673: "From the reconnaissance, the Sonozaki office appeared to have cut off all contact with the outside.",
154674: "They had fortified themselves with barricades and had no apparent interaction with the rioters.",
154675: "If they had surrendered their hearts to the demon like the rioters, they wouldn't have been fortifying themselves — they'd have been out joining the hunt for the infected.",
154676: "But if we came crashing in with rioters in pursuit, the Sonozaki Group would be accused of sheltering the infected, sparking another conflict.",
154677: "Complete stealth was the only way.",
154678: "Une slowly unlocked the door that led outside.",
154679: "In Okinomiya, where the streets were as good as an ocean teeming with sharks, opening the front door felt like stepping into a lion's cage......",
154680: "\"It's not like, I'm not scared......\"",
154681: "\"I'll take point. ......If I fail, fall back quickly as planned. Don't even think about coming back for me. Understood!\"",
154682: "\".........That goes both ways. If I twist my ankle this time, leave me behind.\"",
154683: "\"We really will this time, so tread carefully, Keiichi-kun.\"",
154684: "\"Got it!\"",
154685: "\"Systems confirmed. Leave it to me when the time comes.\"",
154686: "Satoko was carrying a remote-controlled car borrowed from a second floor somewhere.",
154687: "She had tested it driving in a straight line with the remote, with an empty can tied behind it to drag along.",
154688: "It could serve as a decoy in a crisis. The only downside was that the noise would draw unwanted attention.",
154689: "It wasn't a trump card to reach the office — it was a trump card to buy time for a retreat if the operation failed.",
154690: "Mion estimated the operation's success rate at 95%. But that still left a chance of failure above zero.",
154691: "Following her policy of anticipating every possible scenario, Mion gave Satoko's remote-control decoy plan the green light just in case.",
154692: "\"Moving out. ......Keep a fair distance between yourselves and me.\"",
154693: "She eased the door open, took a long moment to feel out the silence around her...... and slipped outside.",
154694: "......Unlike Hinamizawa, Okinomiya was covered in concrete, and even the smallest sounds echoed unexpectedly.",
154695: "Step on a small pebble on the asphalt, and the sound carried remarkably far.",
154696: "\"......Actually...... going barefoot might be better......\"",
154697: "Mion took off her shoes.",
154698: "No matter how carefully you walked, the hard rubber soles couldn't silence the sound of grit grinding against asphalt.",
154699: "Even with socks, a city kid would find walking barefoot on pavement painful.",
154700: "But for us Hinamizawa kids who ran around and climbed trees barefoot like it was nothing, walking on asphalt without shoes was trivial.",
154701: "\"I wonder if our former city boy Keiichi-san can handle the barefoot treatment. Worth watching.\"",
154702: "\"I've been toughened up plenty since then. Don't sell me short.\"",
154703: "\"Are you okay going barefoot, Une-chan......?\"",
154704: "\"......It hurts......\"",
154705: "\"Sorry. Just bear with it for a little while, okay......\"",
154706: "Mion poked just her head out of the alley and checked on the main road — the river of unattended cars.",
154707: "The wide sidewalk gave too clear a sightline. The only option was to dash across in one go and take cover among the cars.",
154708: "The self-styled watch, too, clearly understood that clear view made it the perfect lookout point.",
154709: "Every so often, a flashlight beam swept straight down the sidewalk.",
154710: "......They were excessively frightened, looking for an enemy.",
154711: "Even the faintest presence would send them shouting and summoning the others.",
154712: "\".........Now this is good. This is the kind of thrill I've been after.\"",
154713: "Mion licked the sweat running down her nose with a bold grin.",
154714: "She signaled her friends with hand signs to hold, then watched for her moment.",
154715: "......The watch's lights were restless.",
154716: "They wandered back and forth, looking in every direction nervously.",
154717: "Their fear drove them to light up every shadow.",
154718: "That very restlessness created plenty of openings......",
154719: "Now.........",
154720: "Swift and nimble as a cat. Mion sprinted across the sidewalk and dove into the row of cars.",
154721: "It was over so quickly and cleanly that all the tension beforehand seemed absurd.",
154722: "Keiichi and the others watching from the shadows let out a deep breath of relief.",
154723: "Keiichi, as second in line, was about to follow, but Mion sent the sign to hold.",
154724: "She seemed to want to carefully work her way through the line of cars and check the sidewalk on the far side.",
154725: "\"......Oh no...... This is bad......\"",
154726: "When she'd scouted it from the rooftop right before the operation, there had been no one over there.",
154727: "But at some point, three figures from the watch had appeared on the sidewalk on the far side.",
154728: "......And they were heading right toward her.",
154729: "It was all right — she hadn't been spotted. They were just strolling around shining lights randomly at the cars.",
154730: "Mion calmly spotted a truck with enough clearance and slid underneath it......",
154731: "It was fine, it was fine...... She hadn't been spotted.",
154732: "If they'd seen her, would they really be walking around so carelessly......?",
154733: "Even knowing she was 99% safe...... just thinking about the remaining 1% made her feel a cold sweat coming on.",
154734: "......Pathetic, Mion Sonozaki. To think I'd be sweating over something as basic as hide-and-seek......",
154735: "\"Make sure you don't let any infected slip through......\"",
154736: "\"They've got damaged brains. And they'll try to bite us to spread the virus.\"",
154737: "If anyone's brain is damaged, it's yours. Mion smirked bitterly.",
154738: "But her smile froze when their feet stopped right in front of the truck she was hiding under.",
154739: "\"D-Did they find her...?!\"",
154740: "\"......We're, we're done for.........\"",
154741: "\"Calm down. ......Something's off about how they're acting.\"",
154742: "\"Are they climbing into the truck bed?\"",
154743: "The men from the watch climbed up into the truck bed that Mion was hiding beneath.",
154744: "Apparently there were folding chairs or something stored in the truck bed. The men sat down.",
154745: "In other words, the men had positioned themselves directly above Mion. She was like an insect pinned to a board......",
154746: "\"Wh...... Seriously......?\"",
154747: "Cold sweat dripped from Mion's forehead.",
154748: "Keiichi and the others understood the situation. Mion couldn't move an inch.",
154749: "There was no guarantee they wouldn't hear her crawl out from under the truck. On top of that, Mion had no way to see what was happening above her.",
154750: "Even if she somehow slipped out without a sound, there was no guarantee they wouldn't happen to glance over and spot her.",
154751: "......Mion couldn't move until those men had left......",
154752: "\"I-It's not like, I know what to do......\"",
154753: "\"Is it finally time for the secret weapon?!\"",
154754: "\"Only as a last resort. It could get Mion out, but it'll make a terrible ruckus...!\"",
154755: "\"Still, get it ready.\"",
154756: "Satoko nodded, set the remote-controlled car on the sidewalk, and tied the empty can to it.",
154757: "Once it was set loose, the racket it made would definitely draw their attention.",
154758: "\"Either way, the operation's blown. We need to create an opening for Mion to escape. Better to try again from scratch.\"",
154759: "\"......Agreed. We just had bad timing. Let's start over.\"",
154760: "Having been through so many dangerous club activities, the members knew precisely when to pull back.",
154761: "Mion was thinking the same thing, naturally. Keiichi and the others would create a chance for her to escape. She had to slip out in that gap.",
154762: "......But not yet.",
154763: "There was still a chance the men in the truck bed would stand up and move off somewhere.",
154764: "Even a successful retreat, if it created an uproar, would make a second crossing far more difficult.",
154765: "Even with her heart essentially pinned in place, Mion kept calmly watching for her chance at victory......",
154766: "\"Get Une-chan back to safety first.\"",
154767: "She wasn't used to going barefoot. If it came down to a sprint, she might not be able to give it her all.",
154768: "\"Keiichi-kun, take Une-chan and secure our retreat. Satoko-chan, guard my back.\"",
154769: "\"Leave it to me. You've got a big responsibility, Keiichi-san!\"",
154770: "\"Understood. We're counting on you. Let's go, Une-chan...!\"",
154771: "\"Y-Yes......\"",
154772: "Keiichi took Une and withdrew for the time being.",
154773: "......I thought I'd faced death in Hinamizawa. But it was mostly old people there. And we'd had the home field advantage.",
154774: "Here was a completely different game — pure away territory.",
154775: "\"If I'd known it was going to come to this, I'd have spent more time exploring Okinomiya......\"",
154776: "\"Hahh, hahh, hahh......\"",
154777: "Une was gasping for breath.",
154778: "No surprise there. Being wound this tight took it out of you. Fear alone was enough to make you breathless.",
154779: "\"Let's stop for a moment and catch our breath.\"",
154780: "\"Th...... thank...... you...... Hahh...... hahh......\"",
154781: "Once Une's breathing had steadied, Keiichi sharpened all his senses and swept the area for any presence.",
154782: "......He found one almost immediately.",
154783: "\"This is bad...... Someone's coming.\"",
154784: "\"Huh......?!\"",
154785: "\"Multiple sets of footsteps. The watch. .....................\"",
154786: "There was almost nowhere to hide. Getting spotted now would cut off Mion's escape route too. Any risk was out of the question.",
154787: "There were no other streets. They had to turn back and pray the men went elsewhere.",
154788: "But the main road seemed to be the artery of their patrol circuit. There was a high chance they were heading straight toward Rena and the others.",
154789: "\"Head back. We can't run into them here.\"",
154790: "\"W-We're going back, again......? A-A pincer move......\"",
154791: "\"Might be. Anyway, back we go...!\"",
154792: "Keiichi's instinct was right. The men didn't turn down any other alley — they were heading straight for the main road.",
154793: "Three young men around college age, carrying bent metal bats.",
154794: "At this rate they'd hit Rena and the others from behind.",
154795: "\"A pincer? That's bad......\"",
154796: "\"Now this is interesting. I didn't think we'd get suspense on par with club activities.\"",
154797: "\"No way back. So what do we do?\"",
154798: "\"Y-You don't mean...... do you......?\"",
154799: "\"If we can't go back, then we go forward!\"",
154800: "\"......We'll have to use the remote-control trap to draw the enemy's eyes...... and push forward in that gap.\"",
154801: "A dangerous gambit. It would probably get us through this particular pinch.",
154802: "But the noise would wake the rioters resting nearby, all at once.",
154803: "If they had the bad luck to run headlong into those rioters, we'd be trapped like rats in a bag.",
154804: "Two or three opponents — with all the club members together, we might manage.",
154805: "But if a huge mob came running in response to the noise, we'd just be kids with no way to fight back.",
154806: "Still, even stacked with misfortunes, this was not a game with zero chance of winning.",
154807: "\"Satoko-chan, trap ready......\"",
154808: "\"Whenever you say.\"",
154809: "\"Sidewalk is clear. We can cross now...!\"",
154810: "\"Go! Satoko-chan, now!\"",
154811: "\"Leave it to me!\"",
154812: "\"Move, Une-chan...! Run!\"",
154813: "\"It's not like, I can't run!\"",
154814: "We all crossed at once and dove into the line of cars.",
154815: "But there was no preventing the men in the truck above from noticing our dash.",
154816: "The moment they looked to see what it was, Satoko's remote-control trap activated.",
154817: "It dragged the empty can behind it, making a harsh metallic clatter as it raced down the sidewalk.",
154818: "\"W-What?! What's that sound?!\"",
154819: "\"They're running! After them!! Has to be the infected!!\"",
154820: "Their paranoia and fear transformed into violent aggression.",
154821: "The men leapt from the truck bed onto car roofs and hoods, charging after the sound of the remote-controlled car.",
154822: "The midnight silence shattered, shouts and whistle blasts erupting from all directions. The city's madness came fully awake.",
154823: "But Mion, pinned under the truck, was finally free.",
154824: "\"What are you doing?! It was still too early!\"",
154825: "\"We were pincered! We had no choice!\"",
154826: "\"Une-san, now is the time to show what you're made of!\"",
154827: "\"Hahh, hahh, hahh...!!\"",
154828: "\"There's no going back! More are coming that way!\"",
154829: "Rioters with bloodshot eyes came pouring one after another from the very alley everyone had just been hiding in.",
154830: "There must have been a building or something housing them nearby.",
154831: "The option of retreating to safety was cut off. Forward was the only way.",
154832: "\"If we have to go forward, then forward it is! We're almost there!\"",
154833: "\"Let's pray the Sonozaki Group hasn't forgotten your face.\"",
154834: "\"Hahaha, Kei-chan, you do say the funniest things!\"",
154835: "\"Don't let your guard down! We can't relax until we're inside the Sonozaki Group office!\"",
154836: "\"Agreed. There's still a nonzero chance Shion-san greets us with a 'Who's your sister? Blehhh!'\"",
154837: "\"Right. More importantly, Mion — you haven't forgotten your promise about the belly dance, have you? You made it when Une-chan threw that ladder down for us!\"",
154838: "\"Ihihi, did this old man say something like that?\"",
154839: "\"Hahh, hahh, hahh...!!\"",
154840: "\"Une-chan, hang in there! Just a bit further!\"",
154841: "\"Just around that corner! ...... Huh?!\"",
154842: "I think Mion had completely let her guard down.",
154843: "All that was left was the final sprint to the finish and cutting the tape.",
154844: "But the finish line was not something that could simply be cut through.",
154845: "\"What—?! W-What is this?!\"",
154846: "\"W-What the—?!\"",
154847: "The alley was sealed off with barbed wire mesh.",
154848: "Whether it was the Sonozaki Group securing safety in front of their office, or the rioters keeping the infected from getting through, there was no way to know.",
154849: "But the fact was that the alley was blocked off, with the office right in front of us.",
154850: "Had we known about this barricade in advance, our plan would have been entirely different.",
154851: "It was nothing but bad luck. That one spot alone was in the perfect blind spot from the angle Mion had been surveying through the opera glasses.",
154852: "And a barricade had been built in that very blind spot — a double misfortune!",
154853: "It wasn't impossible to climb over it if you were willing to tear yourself up on the barbed wire.",
154854: "But we couldn't demand that of Une, who didn't share the resolve of us club members.",
154855: "\"Alternate routes?!\"",
154856: "\"Th-there is one! If we swing around from the alley on the other side...!!\"",
154857: "That was when blazing flashlight beams caught us all at once.",
154858: "\"Who are you?!!\"",
154859: "\"Hyahahahaha! There! It's the infected!!\"",
154860: "Our blood ran cold. It was over.",
154861: "Unable to endure the terror any longer, Une let out a piercing scream......",
154862: "There was nothing we could do. Our opponents had us beaten in size, ferocity, and numbers.",
154863: "The rioters swarmed in from all sides...... surrounding us in the dead end formed by the barricade......",
154864: "That was when several dry gunshots rang out in rapid succession.",
154865: "Mion immediately shouted \"Down!\" and pushed everyone's heads to the ground.",
154866: "The rioters, unused to the sound of gunfire, stood there blinking.",
154867: "\"Gentlemen, that's enough! Mob punishment without legal basis is unacceptable under any circumstances!!\"",
154868: "It was the sound of Tomitake firing into the air with a submachine gun he'd taken from the Irie Institution's security room.",
154869: "Perhaps the rioters thought it was a model gun or something — they showed no fear, only glaring at Tomitake for interrupting their hunt.",
154870: "With Okinomiya's medical facilities completely paralyzed, even a shot to the leg could prove fatal.",
154871: "Tomitake had no wish to shoot, and he swallowed hard as the rioters showed no sign of backing down......",
154872: "\"I don't want to shoot, everyone...!\"",
154873: "\"Leave this to me. ......Hanyuu!\"",
154874: "\"Brethren of mine...... Calm your spirits...... I am Oyashiro-sama, your leader...!\"",
154875: "Hanyuu's solemn words rang out for inhuman ears alone.",
154876: "The rioters stood there slack-jawed, blinking as if half asleep.",
154877: "One by one they sat down right on the ground and stared into space.",
154878: "Ferocious as Takano had made them, they were still Hanyuu's kin. They could not escape the power of her voice.",
154879: "Mion and the others stared in disbelief, but they understood — they had escaped death by the narrowest margin.",
154880: "\"Everyone, now while you can......!\"",
154881: "\"W-What is this...? What's going on?!\"",
154882: "\"Oyashiro Power, nipah~☆\"",
154883: "\"Thank you for saving us, Rika-chan! Tomitake-san!\"",
154884: "\"I heard the commotion. Good thing we rushed over. What were you all doing out here?\"",
154885: "\"Mion-san's Sonozaki Group office is just right beyond here.\"",
154886: "\"We didn't know about the barricade and got cornered like rats.\"",
154887: "\"How embarrassing. You cut it that close with my sis on your side?\"",
154888: "\"Shion!\"",
154889: "Beyond the barricade were Shion, Kasai, and a few men in black.",
154890: "They all carried guns, but none of them wore the ferocious expressions of the rioters.",
154891: "It seemed the Sonozaki Group had kept their sanity and focused on holding out inside.",
154892: "\"Give us a break. We really don't want to get tangled up with those lunatics.\"",
154893: "\"Sorry for causing such a commotion.\"",
154894: "\"If you're safe, Shion-san, then there's nothing to be afraid of anymore.\"",
154895: "\"That's right. Alone I'm worth about ten of my sister. Kasai, let them in.\"",
154896: "\"Come in, everyone.\"",
154897: "Kasai undid the padlock on the chains that had been securely fastened to the barricade gate.",
154898: "\"But what on earth happened here? What did you do to them?\"",
154899: "\"Just what, on earth......\"",
154900: "\"Don't worry about it. Leave them alone and they'll wander off on their own.\"",
154901: "\"Now, now! Let's be grateful for this chance granted to us by Oyashiro-sama's miraculous power, hahaha!\"",
154902: "\"Come on, Une-chan, you're safe now!\"",
154903: "\"With Shion-san here too, there's absolutely nothing to worry about!\"",
154904: "\"That's right. At least Satoko gets it. ......By the way, who's this girl?\"",
154905: "\".........H-Hello......\"",
154906: "\"This is Une-chan. She saved our lives!\"",
154907: "\"......What's wrong, Hanyuu?\"",
154908: "\"........................\"",
154909: "\".....................\"",
154910: "\"......You are............\"",
154911: "Everyone slipped through the barricade and was welcomed into the Sonozaki Group office.",
154912: "That sight...... was being observed from a distance through binoculars......",
154913: "\".........Hehe, hehe. ......Found you. ......So that's the one......\"",
}

with open('kamikashimashi_5.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0
for entry in data:
    if entry.get('type') not in ('MSGSET', 'LOGSET'):
        continue
    mid = entry.get('MessageID')
    if 'TextENGNew' in entry:
        continue
    if mid in translations:
        entry['TextENGNew'] = translations[mid]
        count += 1
    else:
        print(f"WARNING: No translation for MessageID {mid}")

with open('kamikashimashi_5.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Verify
with open('kamikashimashi_5.json') as f:
    data2 = json.load(f)
total = sum(1 for e in data2 if e.get('type') in ('MSGSET','LOGSET'))
has_new = sum(1 for e in data2 if e.get('type') in ('MSGSET','LOGSET') and 'TextENGNew' in e)
print(f"Added {count} TextENGNew entries to kamikashimashi_5.json")
print(f"total={total}, has_new={has_new}, needs={total-has_new}")
